### ISSUE TITLE
Synthetic time budget analysis missing columns

### ISSUE THREAD

**Issue by JulienGAMartin** [olivierfriard/BORIS#104]
The synthetic time budget analysis provides only the total time and the number of time a behaviour has been observed. 
I understand the mean duration of bout and the proportion of time the behaviour is seen could be estimated from total time and number of time, but it would be nice to have those varaible directly estimated by BORIS.
In addition, it is not possible to estimate the variance in bout duration (i.e. SD column) based on the information available in the table.
It would be great if the synthetic time budget analysis could provide for each behaviour the following:
* total duration (already in)
* number of time (already in)
* mean of a bout
* proportion of time (total duration / length of observation)
* variance or SD in bout duration

So I am just asking to have the same variable available in the synthetic time budget analysis that you have in the time budget analysis
Thanks

**Comment by olivierfriard** [comment]
Hi,
you will find a pre-release of BORIS (v.6.1.5) in the following google drive directory:
https://drive.google.com/drive/u/1/folders/0B0KTzxkLpPJ_Z0tfYklfd2RxWmc

May you test the improved synthetic time budget and let me know if it is working?.
I added the missing variables.

**Comment by olivierfriard** [comment]
features added in v. 6.2
