### ISSUE TITLE
Geometric measurements over successive frames

### ISSUE THREAD

**Issue by EminentCodfish** [olivierfriard/BORIS#120]
I have an application where I am trying to measure the speed/distance traveled of an object over successive frames.  The geometric measurement tool is handy to measure distance in a single frame, but cannot track distance over time.  Could that function be added?  Even if we could measure and export points over time (i.e. the outputs would be time, frame and x,y).

Thank you.  I love the software!

**Comment by olivierfriard** [comment]
Hi,
thank you for your suggestion.
In your opinion adding a single point object and recording its position over frames could be an improvement?
