### ISSUE TITLE
Zoom  Feature Still Not Working on Mac

### ISSUE THREAD

**Issue by hadyng** [olivierfriard/BORIS#122]
2014 MacBook Air, running macOS High Sierra Version 10.13.4 (17E202)

Has there been some sort of solution to the zoom feature malfunction for Macs?

**Comment by olivierfriard** [comment]
Hello,
the v. 7.3 has a function for focusing an area of the video.
Click on the video to try it and let mo know if it is working
Another click on the video will restore the previous visualization.
