### ISSUE TITLE
View Modifiers During Observation

### ISSUE THREAD

**Issue by mmulholland** [olivierfriard/BORIS#124]
During an observation, we can see the active behavior codes at the top of the screen:

![image](https://user-images.githubusercontent.com/25001552/41067221-60473f5c-69aa-11e8-83cd-4aa9400bc1cf.png)

Can an option be added to show the modifier as well (above would look something like "Locomote/Run, Proximity/Near")? Maybe this could be an option people could turn on/off based on how they use modifiers in their project? I make use of a lot of modifiers and it would be really helpful to quickly see which ones are currently active during an observation. Thanks!

**Comment by olivierfriard** [comment]
Hi,
modifiers are visualized
