### ISSUE TITLE
BORIS crashes when trying to export events

### ISSUE THREAD

**Issue by erikaroper** [olivierfriard/BORIS#125]
Whenever I try to export my events BORIS crashes, meaning that I cannot export my data for analysis.

Mac OS 10.13.5
Boris v 6.3.1

I've been trying the "export events" and "export aggregated events" options and both cause BORIS to crash. I can send the Apple generated crash report if required.

Thanks

**Comment by olivierfriard** [comment]
Hi,
can you specify exactly when BORIS crash?
Thanks

**Comment by olivierfriard** [comment]
v.6.3.2 just released should fix this issue.
Please let me know
