### ISSUE TITLE
Canceling doesn't work when behavior selected accidentally

### ISSUE THREAD

**Issue by mmulholland** [olivierfriard/BORIS#132]
v. 6.3.3 for Windows

During an observation, if I accidentally hit the wrong behavior key then choose cancel it still stops my current behavior(s) and starts the accidentally selected behavior. The Cancel and OK button are essentially doing the same thing.

For example, I have behavior "L" with modifiers "W" and "C". I start "L-C" as I should, but then when the subject changes behavior I accidentally clicked "W" instead of "L-W". I click cancel hoping to avoid the mistake, and it still stops "L-C" and starts "W".

This seems like a bug, shouldn't the cancel button "undo" my accidental selection and keep the current behaviors running? 

Thanks, Michele

**Comment by olivierfriard** [comment]
should be fixed in v. 6.3.5 just released
thank you for your collaboration!
