### ISSUE TITLE
frame-by-frame mode step back steps forward

### ISSUE THREAD

**Issue by manuelbaum** [olivierfriard/BORIS#137]
Hi,

First of all, thanks for the software!

The bug: when I switch to frame-by-frame mode and click the button for forward stepping, it steps forward -- good! But when I click on the button for backward stepping, it also steps forward!

I am on Ubuntu 14.04 and have BORIS v. 6.3.5 - 2018-06-28.

**Comment by olivierfriard** [comment]
Hello,
I can not reproduce this problem.
Can give me more details?
What is the value of the "fast forward/backward speed" parameter? (See File > Preferences)

**Comment by olivierfriard** [comment]
Hi,
I can not find the screenshot...

**Comment by Jennifer500** [comment]
resending - should be at the bottom of this mai …
J

**Comment by manuelbaum** [comment]
The parameter is set to 1. I also attached a screenshot of my preferences, because I can't see Jennifer500s attachment

![boris](https://user-images.githubusercontent.com/2357765/43396224-35325e42-9401-11e8-9cd5-b58a2b49e494.png)

**Comment by Jennifer500** [comment]
So our settings are
10
0
0,1
0

Jennifer

**Comment by manuelbaum** [comment]
Our current theory is that it actually depends on the observation that is supposed to be annotated, because stepping back actually works for some of our observations.

More precisely, we believe the bug occurs for observations with two different videos with delay between them. It seems that it works for observations where the main video starts earlier than the second video, but the bug occurs when the second video starts earlier than the main video.
