### ISSUE TITLE
Extract data only while specific behaviour is shown

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#139]
It would be great if there was a possibility to extract data for periods when a certain behaviour was shown.

**Comment by saraewise** [comment]
I would also appreciate this. Specifically, the ability to extract the number of point events that occur during a specific state event.

**Comment by olivierfriard** [comment]
this feature was added.
See Analysis > Advanced event filtering
User guide:
https://www.boris.unito.it/user_guide/analysis/#advanced-event-filtering
