### ISSUE TITLE
display current behaviour directly

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#151]
Is it possible to have the current behaviour shown under “Focal subject” directly when it is entered, without having to press “play” or to enter another behaviour? (working with version 7.0.4)

**Comment by olivierfriard** [comment]
added in v. 7.0.6

**Comment by boswel** [comment]
Maybe there was a misunderstanding, because what I meant still doesn't work (in v. 7.0.10). When I record behaviour, I often press "pause" when I see that something happens (and this might have been the missing information...) - when I then enter a new behaviour, it does not show under "Focal subject", but only if I enter another behaviour or press play. 
![bild1](https://user-images.githubusercontent.com/40495106/46213741-adb9fe80-c339-11e8-8d1f-39abfea6f2ed.png)
