### ISSUE TITLE
single 'pause/play' button

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#152]
Is it possible to have one single „play/pause“ button? Because you only ever need one of the two, and if you're working with the mouse, it would be very convenient not to have to change the position of the mouse pointer to switch between pause and play. 
This sounds like a small thing but was the single issue that irritated me most when I switched from a commercial software to BORIS, because you have to look up - if the button is the same, the mouse pointer can just stay where it is to do rapid changes between pause and play.

**Comment by olivierfriard** [comment]
added in v. 7.0.6
