### ISSUE TITLE
Jumping forward/backward - wrong frame displayed or jump to far

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#153]
When I use the “jump backward” button or jump to a certain behaviour using the events widget, I sometimes get a quite “random” frame (or maybe one from the start of the video?) in the media player widget and not the one I jumped to. The intended frame is only displayed once I start playing the video. It would be helpful to see the frame that I selected, for orientation within the media file (e.g. “go back to the last time when I could still see the eye” – if I get random frames, that makes it much harder for me to find the right place in the vid). And sometimes the video jumps back to the start although I pressed “jump forward” or back to the previous video (> 1 min) although I have the “jump” buttons set at an interval of 2 s. 
(working with version 7.0.4)

**Comment by olivierfriard** [comment]
Hi,
this problem is (probably) related to the video format you are using.
I have the same problem using the MOD format.
Please try to re-encode your video with the BORIS tool:
Tools > re-encode/resize video
The output will be an avi file (video in MPEG4 format) that should work with BORIS.
