### ISSUE TITLE
Data visualization won't redraw when jump forward/backward while paused

### ISSUE THREAD

**Issue by wliao229** [olivierfriard/BORIS#174]
I use the macOS version. When I use v7.3, I can pause the video and jump forward/backward while having the data visualization refreshed correctly. However, in the lastest version (7.4.2), the visualization will refresh only when the video is playing. 

Is this a bug, or could you bring the older behavior back?

**Comment by olivierfriard** [comment]
I will fix this.
Thank you for your collaboration
o

**Comment by olivierfriard** [comment]
The bug should be fixed in pre-release of v.7.4.3
https://github.com/olivierfriard/BORIS/releases/tag/v7.4.3
Can you confirm that?

**Comment by wliao229** [comment]
I confirm that the problem is fixed in 7.4.3
