### ISSUE TITLE
stop ongoing state events between successive media time

### ISSUE THREAD

**Issue by 4399999999** [olivierfriard/BORIS#175]
I have a little problem, I have the Mac version when I try to sync two videos, I should click on the option (stop ongoing state events between video), but it does not give me the chance to select it

**Comment by olivierfriard** [comment]
The **stop ongoing state events between video** option is disabled for now because it is not working well.

Anyway, this option is not useful for synchronizing video.
See the documentation: https://boris.readthedocs.io/en/latest/observations.html?highlight=spectrogram#media-based-observation
