### ISSUE TITLE
"Limit to time interval" produces wrong time spans (>100%) and proportions in data

### ISSUE THREAD

**Issue by sbraem** [olivierfriard/BORIS#176]
I want to produce my output through 'Synthetic time budget' analysis and I only need the first 20 minutes of observation. However, when looking at the output, there were multiple observations (mostly the ones that were much longer than 20 minutes) that gave the wrong proportions. Many had proportions that were >1. It seems that the proportions are still relative to their original total length. Is this an error or am I doing something wrong? In the attachment you can find an example.
![image](https://user-images.githubusercontent.com/47149812/51919123-1649e280-23e3-11e9-90fd-afe8ecea3648.png)

I am using BORIS 7.4.2

**Comment by olivierfriard** [comment]
Hi,
this bug should be fixed in v.7.4.5
Could you confirm that?
Thank you for your collaboration

**Comment by sbraem** [comment]
this issue has been resolved, indeed.
Thank you for the quick response
