### ISSUE TITLE
Timestamp for each registry

### ISSUE THREAD

**Issue by Atchoi** [olivierfriard/BORIS#183]
Hi Boris team, 

I have a set of IR trap cams, that are used to monitor seabird activity at the breeding colony. These generate short videos ~10sec, triggered by movement. They span over a few weeks/months, a few videos each night. They are not continuous and can skip a few seconds or minutes before being triggered again, even if the subject is still in focus (for example still walking about). Thus true behavior duration is longer than what the video actually recorded.  

I want to classify the subjects and their behavior(s) for each night (date) and so far Boris is perfect. However, I also need to measure the behavior duration (calculate amount of 'out of the burrow movements' for eg.), and since the videos from the IR camera are not continuous, ideally each behavioral event line would have the **actual date/time of the video for each behavior line,** thus enabling a more exact approximation of the behavior duration, based on the actual time lapsed. 

Is this in any way possible? to extract for each behavioral registry (csv line), the actual timestamp of the video? 

Thank you very much!

**Comment by olivierfriard** [comment]
Sorry for the late answer...
Do you mean adding to the events the current video position and not the cumulative time?
