### ISSUE TITLE
Adding waveforms of sound media

### ISSUE THREAD

**Issue by Butterflyfish14** [olivierfriard/BORIS#184]
Hi Boris team!

One great enhancement I would recommend is that you can add the waveform of a sound (rather, or in addition to the spectrogram), sometimes it is actually easier to correlate some sounds with the soundwave and you may miss some info with the spectrogram.
Thank you for your consideration!

Best wishes

**Comment by olivierfriard** [comment]
Hi,
the waveform visualization was added in the v. 7.4.13. This version is only on github releases for now:
https://github.com/olivierfriard/BORIS/releases
I am working to improve it. Can you test it and let me know?

Thank you for your collaboration
Olivier

**Comment by olivierfriard** [comment]
added in v.7.4.14
