### ISSUE TITLE
"Jump backward" changes media file

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#185]
Hi,
I have an observation including two media files, in BORIS portable 7.4.11 (64x). If I press the "jump backward" button while playing the first media, BORIS jumps to some place in the next media file. I re-encoded both videos, to no avail. In addition, the total duration shown is only about 2 min, whereas each of the videos is about 15 min long. 
Edit: I just found out that the same thing happens if I double-click on an entry in the event widget - I end up in the other video instead of at the time when the behaviour occurred.
Edit2: Now, clicking on "jump backward" doesn't do anything at all, and neither does clicking on the event...
Edit3: Just noticed that the timing of the whole observations seems to be messed up. I'm in the second video and BORIS records events stating the time as "00:12:20" where they should be at > 00:15:00. Also, the duration of the logged events seems to be much longer than it should be.
Thanks for looking into this.

![time messed up](https://user-images.githubusercontent.com/40495106/54279706-07378200-4596-11e9-9007-9a58da187f5b.jpg)

**Comment by olivierfriard** [comment]
Hi,
I can not reproduce this problem.

1) can you check if this problem occurs on your system using the video samples (from the download page on the BORIS web site)?

2) Using the pre-release v. 7.4.12, can you use the "Check project integrity" and report me the output ?
https://github.com/olivierfriard/BORIS/releases/tag/v7.4.12
(I added a function to check the availability of the media file duration.)

Thanks
Olivier

**Comment by boswel** [comment]
Actually, no surprise there - I tried to reproduce the error myself and found that I had re-encoded the videos but not actually entered them in the observation... could have saved me a lot of trouble. Sorry for bothering you...
