### ISSUE TITLE
.csv output displays modifiers where there should be none

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#186]
Hi,
I analysed several observations with the time budget analysis in BORIS portable versions 7.4.6 and 7.4.11 (64x). In the saved .csv, there is a modifier "-" displayed for some behaviours that should have no modifier at all; this seems to be the case if the total duration of the behaviour is 0. As this messes up the data set quite a bit - could you please do something about that? Or tell me if I did something wrong or whether there's a workaround?
Thanks!

**Comment by olivierfriard** [comment]
This is fixed in v.7.5
