### ISSUE TITLE
Exclusion problems

### ISSUE THREAD

**Issue by OccitanGudgeon** [olivierfriard/BORIS#188]
Dear Boris team, 

I would like first to thank you for your great work on this software. 

_The report_ : Since I'm using the version 7.4.14 64bits (i'm using win 10 64bits) I have a problem with one behaviour (here "repos") which does not exclude the other one (here "mouvement") while it is specified in the exclusion matrix (see the first attached image). 
This problem does not appear when using the version 7.4.11 and previous one (see second attached image). 
(I want to specify I used the same ethogram in both trials)

![Exclusion-v7 4 14](https://user-images.githubusercontent.com/48917906/54928170-cd5e6800-4f13-11e9-8e42-f3b70be97301.png)

![Exclusion-v7 4 11](https://user-images.githubusercontent.com/48917906/54927548-a5223980-4f12-11e9-8c68-31a1bc30f0e3.png)

Thanks a lot for your great work. 

Best regards. 

Quentin.

**Comment by olivierfriard** [comment]
Hello,
can you send me a copy of your project file?
You can remove all observations (leaving the ethogram) and send it by email if you prefer.
Best regards
Olivier

**Comment by OccitanGudgeon** [comment]
Hi Olivier,

You can find the BORIS project attach to this email. Hope it will help.

Kind regards.

Quentin.

*Quentin Petitjean.*
*PhD Student at *
*Université Paul Sabatier Toulouse III*



*UMR 5245 EcoLab -- Laboratoire d'Ecologie Fonctionnelle &EnvironnementUMR
5174 EDB -- Laboratoire Evolution & Diversité Biologique**+33662920214*
*------*
*http://www.ecolab.omp.eu/profils/PETITJEAN_Quentin
<http://www.ecolab.omp.eu/profils/PETITJEAN_Quentin> *
*------*


Le lun. 25 mars 2019 à 16:30, Olivier Friard <notifications@github.com> a
écrit :

**Comment by olivierfriard** [comment]
fixed in v.7.4.15
