### ISSUE TITLE
Mac Download - Failing to Open

### ISSUE THREAD

**Issue by sskiba5** [olivierfriard/BORIS#197]
I have downloaded version 7.5.3 for my macbook air (version 10.10.5). I have changed all of the security settings to allow my mac to open the download from the internet. Once I add the BORIS icon to the application's folder, it verifies. Once I go to run BORIS, the icon appears on the dock for 3 seconds and then disappears. There is no error message. There is no security pop-up. BORIS never "runs" or opens. I have tried removing BORIS from my computer and re-downloading multiple times and I am still getting the same issue. 

Any help is much appreciated!

**Comment by olivierfriard** [comment]
Hi,
your OS is a little bit old. I will check the minimal version of mac OS and let you know
Olivier
