### ISSUE TITLE
Synchronized ASF files

### ISSUE THREAD

**Issue by benjiebob** [olivierfriard/BORIS#198]
Hi there,

Firstly, love BORIS -- great stuff 👍 

I have various ASF media files containing video data from 4 camera views of the same scene over a 24hr period. Since ASF files encode timestamps etc. does (could) BORIS to use this to ensure the frames are synchronized when annotating multiple videos at the same time?

I assume that the only solution currently is to manually enter the "Offset (seconds)" in the "New Observation" window. However, this is tricky to calculate between multiple videos without examining the internals of the ASF file directly.

Alternatively, I could try write an app that creates a "2x2" video by combining the videos before loading into BORIS. Interested to know if you recommend this instead...

My ideal output is, for each **synchronized** frame: 

- 1 image per camera (e.g. frame01_cam01, frame01_cam02, frame01_cam03, frame01_cam04)
- 1 behaviour label per animal (e.g. dog 1: walking, dog 2: sleeping)

Any tips appreciated :)

Thanks,
Ben

**Comment by olivierfriard** [comment]
Hi,

what do you mean by "ASF files encode timestamps"?
Can you send me a sample of an ASF media file

Olivier
