### ISSUE TITLE
BORIS crashes when Exporting observation list

### ISSUE THREAD

**Issue by GustavoBerumen** [olivierfriard/BORIS#200]
Hi, 

BORIS closes and doesn't create a file when trying to "Export Observation List." BORIS waits a couple of seconds and then closes without any warning. I am using BORIS v 7.6 version in a 64 bit Windows 10. 

Best,

**Comment by GustavoBerumen** [comment]
I also, found that BORIS also crashes when trying to add more than 8 behaviours to an Ethogram

**Comment by olivierfriard** [comment]
Hi,
the bug should be fixed in v.7.6.1 just released.
Can you confirm?

I am not able to reproduce the crash with more than 8 behaviors in ethogram.
Can you send me more details?
Thank you for your collaboration

Regards

**Comment by GustavoBerumen** [comment]
Hi Olivier, 

Both bugs have been solved with the newest version. 

Thank you very much,
