### ISSUE TITLE
Possibility to stop an observation after a certain time 

### ISSUE THREAD

**Issue by saham18** [olivierfriard/BORIS#210]
It would be nice to have the possibility to have specifically timed
observations, i.e. have an observation that stops when it has reached a
certain time. This would be useful in the situation when you make live
focal observations that are time defined (such as focal observations).

**Comment by olivierfriard** [comment]
this feature was added in the pre-release of v.7.8 available at https://github.com/olivierfriard/BORIS/releases/tag/v.7.8

See the **Limit observation to a time interval** option when creating/editing and observation.

Please test it and let me konw

Thank you for your collaboration.

Olivier
