### ISSUE TITLE
error when exporting events of multiple observations

### ISSUE THREAD

**Issue by Korvuskorax** [olivierfriard/BORIS#219]
Hello,
I'm trying to export the events of multiple observations using "export aggregated events" (exporting them as separate xslx files), but this gives the error message: "'NoneType' object has no attribute 'replace'" when trying to create the xslx files. Exporting the observations one at a time does not give any problems.
Using the most recent version of BORIS (7.7.3) on Win10.

The issue does not occur when trying to export as CSV, so that's what I'm doing now.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting.
The bug will be fixed in the next release at mid-august.
o

**Comment by olivierfriard** [comment]
fixed in v.7.7.4
