### ISSUE TITLE
Problem trying to exclude "out of site" behaviour

### ISSUE THREAD

**Issue by sgperrott** [olivierfriard/BORIS#225]
Hi

I am trying to produce a synthetic time budget for my observations which has been working but for some its coming up with this error when I exclude the "out of site" behaviour. 

TypeError
unsupported operand type(s) for -: 'float' and 'NoneType'
Line number: 272

When I don't exclude the "out of site" behaviour it works fine but I want to exclude this from my analysis.

Thanks!

Sara

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this issue.
I will fix it in the next release
o

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 7.8.2
Can you confirm this?

**Comment by sgperrott** [comment]
Hi
Yes thank you it’s working again!

Kind regards

Sara

Sent from my iPhone

On 6 Sep 2019, at 8:00 am, Olivier Friard <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
this issue should be fixed in v. 7.8.2
Can you confirm this?
