### ISSUE TITLE
Automatic relocation & resizing of widgets

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#229]
Hi,
A widget will adjust to a certain shape/size if you drag it into one of the pre-defined areas in the main window. Working with several students, I found that everyone of them, and myself as well, usually drag the widgets into these areas unintentionally, resulting in involuntary relocation and resizing of the widget, which is most inconvenient. Is there an option to switch this feature off?
Thanks!

**Comment by olivierfriard** [comment]
A new option in v. 7.9 allows to lock the dockwidgets on the main window.
See Tools > Lock dockwidgets
