### ISSUE TITLE
use arrows for media navigation

### ISSUE THREAD

**Issue by livethedance** [olivierfriard/BORIS#23]
I am using your program to code for ant behavior. I must often work backwards to determine the location an ant started from before it performed an action. I think it would be great if you could connect the media navigation buttons to the keyboard; for instance I would like to use the arrow keys for stepping forward and backward. This would make navigation much more quick and more exact. I have tried the frame-by-frame option, but the layout of the / and * keys is not user-friendly on a US keyboard, you have to use "shift" to get to the * (and sometimes I would like to go faster than frame-wise and still use the keyboard to navigate the video/frames). Adding in the ability for users to set their own preferences for media navigation keys on the keyboard would be the most awesome solution, if possible.

So far, your program is great, and it looks like it will meet my needs quite well. Thank you for sharing it!

**Comment by olivierfriard** [comment]
I added some key to make media navigation easier in the development version:

**For the both modes (VLC and frame-by-frame)**:
**Page Up** key: switch to the next media
**Page Down** key: switch to the previous media
**Up arrow** key: jump forward in the current media
**Down arrow** key: jump backward in the current media
**ESC**: switch between VLC and frame-by-frame mode

**Only for the frame-by-frame mode:**
**Left arrow** key: go to the previous frame
**Right arrow** key: go to the next frame

**Comment by livethedance** [comment]
That’s great. I will try it out!

Thank you,
Courtney Rockenbach

**Comment by livethedance** [comment]
It works great! Thank you!
