### ISSUE TITLE
suggestion: adjust for play-rate in seeking

### ISSUE THREAD

**Issue by kdquine** [olivierfriard/BORIS#231]
Currently, skipping forward or back takes you forward relative to 1x speed; how do folks feel about switching this to, relative to the currently chosen speed?  I have been playing with in my private build and it seems like a large improvement.

To illustrate:
  your current play-rate is 0.2x
  your current time index is 15s
  seek-distance is 1s
  you saw something happen just now, hit pause, rewind
  you currently jump back to t=14s, and the thing you were interested in appears again in 5.0 viewing-seconds. with subjective time adjustment, you seek back to t=14.8s, and then the event of interest is seen again after 1.0s of viewing time. 

  Or, at play rate 2.0x, 
  your current time index is 15s
  seek-distance is 1s
  you saw something happen just now (t=15s), hit pause, rewind
  you currently jump back to t=14s, and the thing you were interested in appears again in 0.5 viewing-seconds. with subjective time adjustment, you seek back to t=13s, and then the event of interest is seen again after 1.0s of viewing time.

**Comment by kdquine** [comment]
this is what I've been using locally:

https://github.com/kdquine/BORIS/tree/subjective_time_seek

**Comment by olivierfriard** [comment]
Your commit has been merged in the BORIS code base.
Thank you for your collaboration
