### ISSUE TITLE
suggestion: keyboard shortcuts for play_rate adjustment

### ISSUE THREAD

**Issue by kdquine** [olivierfriard/BORIS#232]
the interface for BORIS is fairly close to not needing the mouse once you've settled into coding.

One thing I have found helpful locally is binding keys to play_rate adjustments.

I haven't taken a detailed look at different keyboard layouts to figure out what sensible bindings for these keys would be if they must be hardcoded, and I guess adding bindings would potentially be a breaking change for folks.

**Comment by kdquine** [comment]
I've been using these changes locally [bindings for '[', ']', and '\'].

https://github.com/kdquine/BORIS/tree/kara/keyboard_shortcuts_for_playrate

**Comment by olivierfriard** [comment]
your commit has been merged in the BORIS code base.
Thanks
