### ISSUE TITLE
edit multiple observations

### ISSUE THREAD

**Issue by sbraem** [olivierfriard/BORIS#235]
Hi,
When I want to edit multiple observations from observed events or point observations, I only can do this one by one. However, it does not seem to be possible to edit multiple events at the same time (right click on selected events and select edit) to a new event AND a new modifier. For example,if I want to change multiple behaviours of "no motion" with behaviour "locomotion" with modifier "walk", "run", "crawl", I would only be able to edit multiple events to "locomotion" without modifier.
This is only a small detail, but it would be nice if this was fixed.
With friendly regard,
Simon

**Comment by olivierfriard** [comment]
this should be fixed in recent versions
