### ISSUE TITLE
Mac version events not working or not visible

### ISSUE THREAD

**Issue by savoieje** [olivierfriard/BORIS#237]
I started having this issue on 10/09/2019. I am using Mac Mojave 10.14.6. I am using Boris version 7.8.2 . I redownloaded Boris on 10/10/2019 and it is the same version 7.8.2 (7.8.4 not available for mac download?).
When I edit an existing observation or start a new one the events window does not pop up. The subjects and the coding windows appear. When I tried to add a behavior I think it added it, because it asks for the modifier, but it is not visible.

**Comment by olivierfriard** [comment]
Hello,

I started having this issue on 10/09/2019. I am using Mac Mojave 10.14.6. I
> am using Boris version 7.8.2 . I redownloaded Boris on 10/10/2019 and it is
> the same version (7.8.4 not available for mac download?).
>
7.8.4 is a pre-release available at
https://github.com/olivierfriard/BORIS/releases/tag/v7.8.4
Download boris-7.8.4.mac64-10.14.dmg file.



> Yesterday -when I edit an existing observation or start a new one the
> ethogram window did not pop up. The subjects window and coding window did
> appear. When I tried to add a behavior I think it added it, but it is not
> visible.
> Today - the ethogram window appeared along with the subjects window. Now
> the coding window did not appear. When I tried to add a behavior using the
> coding pad it acts like it has been added (it asks for the modifier), but
> the ethogram does not update.
>
> —
>
To fix your problem with the window that are not visible see the FAQ at
http://www.boris.unito.it/pages/faq.html

It is normal that the ethogram does not update when you are coding.
The event will be added to the events list only after setting the
modifier(s)

o

**Comment by savoieje** [comment]
I thought I might be the issue and not Boris. Thanks for your assistance.
