### ISSUE TITLE
MacOS error when trying to open new versions 7.8.4 or 7.9.1

### ISSUE THREAD

**Issue by savoieje** [olivierfriard/BORIS#241]
I am using MAC OS Mojave 10.14.6
I tried downloading versions 7.8.4 and 7.9.1. I am prompted to allow the download from an unidentified developer to be opened, which is typical.  But then I get a window popping up that says 
"The operation couldn’t be completed. (OSStatus error -67062.)"

This did not happen with the previous version 7.8.2

**Comment by sevtrannoy** [comment]
I have exactly the same issue. Did you fix the problem? Thank you very much!!!

**Comment by katydonegan** [comment]
I am using macOS Catalina 10.15 and get an error "boris-7.9 cannot be opened because the developer cannot be verified". I did not have this problem with 7.8.2, the previous version I was using

**Comment by PauMontoya** [comment]
I am using macOs Catalina 10.15 and I can't modify the window player #1 it is too big or too small. Also Boris crashes when I try to upload two media in the same observation. Thank you!

**Comment by Chinca-lang** [comment]
@katydonegan right click on the app -> open -> allow. After the first time, it won't ask you any more permission to open it.

**Comment by olivierfriard** [comment]
Hi,
the issue should be fixed in the modified release 7.9.1.
https://github.com/olivierfriard/BORIS/releases/tag/v7.9.1
Please test and let me know
o

**Comment by Chinca-lang** [comment]
Hi,
it's working now!
Thank you very much for your support.
Cheers,
M

**Comment by sevtrannoy** [comment]
Hi. It is working. Thanks a lot!
