### ISSUE TITLE
Import of subjects doesn't work

### ISSUE THREAD

**Issue by boswel** [olivierfriard/BORIS#242]
Hi,
My students noticed strange behaviour when trying to import subjects from an excel spreadsheet to a BORIS project. BORIS seems to only import one column. As soon as you select and copy more than one column, a warning occurs, stating: “ The clipboard content does not have a constant number of fields. […]”
If you select only one column, BORIS automatically categorizes the column as “KEY” and imports only single symbols (1-9 and letters). 
Thank you!

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting
This issue will be fixed in the next release

**Comment by olivierfriard** [comment]
this should be fixed in v. 7.9 just released
