### ISSUE TITLE
Boris crashes on Ubuntu 18.04 and 19.10

### ISSUE THREAD

**Issue by ladiode** [olivierfriard/BORIS#251]
Hi,
I have tried to use Boris on several PCs using Linux and every time, when I try to create a new observation, the app crashes without any explanation.
I tried a workaround and used Wine 4 with the Windows version but it is highly unstable.
Did anyone find a way to get Boris to work on Ubuntu?

Thanks,

Ladiode

**Comment by olivierfriard** [comment]
Hi,
the v.7.9.1 (https://github.com/olivierfriard/BORIS/releases/tag/v7.9.1) updated this morning should fix this issue. Please try the file boris-7.9.1.linux64-18.04.tar.gz and let me know if it works on your system.
You will have to install vlc (sudo apt install vlc).
o

**Comment by ladiode** [comment]
It works, thanks a lot!
