### ISSUE TITLE
modifier-maps crash when polygon on a second map is pressed

### ISSUE THREAD

**Issue by andre-wi** [olivierfriard/BORIS#252]
Hey guys,

I want to use an ethrogram with several (behavioural) modifier maps.

Problem is, that when I open a map after I opened another map before, the boris-gui closes.
This is happening in an observation AND in the map creator..

Version tested: windows (7.0. & 7.9), mac (7.4 & 7.9), ubuntu (not tested)

debug output on windows (for map creator):

`Traceback (most recent call last):
  File "C:\Users\XMG\Desktop\coding\boris_debug-7.9.RC1.win64\BORIS-master\src\map_creator.py", line 323, in viewMousePressEvent
    self.selectedPolygon.setPen( QPen(designColor, penWidth, penStyle, Qt.RoundCap, Qt.RoundJoin) )
RuntimeError: wrapped C/C++ object of type QGraphicsPolygonItem has been deleted`

**Comment by olivierfriard** [comment]
Hi,
this bug should be fixed in v. 7.9.4.
Please check and let me know.
Thank you for reporting
o
