### ISSUE TITLE
BORIS jumps to random location further along the video when going backwards.

### ISSUE THREAD

**Issue by JoKunkel** [olivierfriard/BORIS#259]
The problem only shows up in long ( 1.5 h upwards) mp4 videos.

**Comment by olivierfriard** [comment]
The problem is present in VLC too.

ffprobe information about file:
Duration: 10:59:24.36, start: 88574.281956, bitrate: 154 kb/s
Stream #0:0[0x1e0]: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
VLC indicates a different duration: 5:04:13.000

**Comment by olivierfriard** [comment]
The problem was due to the file that contain many errors.
I re-encoded it with ffmpeg and the problem disappeared.
VLC indicates the same total duration than ffprobe: 10:59:24
