### ISSUE TITLE
Location of object in video (x-y position)

### ISSUE THREAD

**Issue by imgross** [olivierfriard/BORIS#275]
Dear Olivier,

I was wondering whether it is possible to not only have the timestamps for certain behaviors that one wants to annotate, but whether one can also assign by clicking somewhere in the video to report also the position of where you have clicked in x-y coordinates next to obtaining the timestamps?

That would be an amazing addition, or maybe it is already there but I have not found it yet.

Best wishes,
Isa

**Comment by imgross** [comment]
Hi Olivier,

I found the geometric measurements option, which is interesting to me.

Can you explain how the number for annotation a point in the specific frame is calculated?

Best,
Isa

**Comment by imgross** [comment]
Hi Olivier,

sorry for all the messages. But I figured now also the numbers for the point annotations. A little confusing to me is that the resolution of the image in pixel is probably changed, because the values differ consistently by a being 70 % of the true pixel value from the full resolution. And in the 'Media File Information' it says that it is not changing the resolution even though that seems to be the case.

Another question that I have regarding the locations is, whether it is possible to track a slowly drifting object, by frame-by-frame wise changing a point that was marked? 

Cheers,
Isa

**Comment by olivierfriard** [comment]
Hello,

sorry for all the messages. But I figured now also the numbers for the
> point annotations. A little confusing to me is that the resolution of the
> image in pixel is probably changed, because the values differ consistently
> by a being 70 % of the true pixel value from the full resolution. And in
> the 'Media File Information' it says that it is not changing the resolution
> even though that seems to be the case.
>
>
I will check this as soon as possible.


> Another question that I have regarding the locations is, whether it is
> possible to track a slowly drifting object, by frame-by-frame wise changing
> a point that was marked?
>
>
If you have to track an object position for many frames perhaps you will be
interested by another program I mave for this purpose.
It is not very user friendly, it depends on your computer skills
(principally the use of the terminal).
Please let me know.

Olivier

**Comment by imgross** [comment]
Hi Olivier,

thanks very much for your answer.

And yes, I would be quite interested in checking out your other software for object tracking.

Cheers,
Isa

**Comment by imgross** [comment]
Hi Olivier,

I just got back to this message after quite a while and was wondering, whether you found out, where that single number outputted when choosing a point geometric measurement, is coming from and whether it is transformed in any way?

Best,
Isa
