### ISSUE TITLE
Media offset, queue and synchronization

### ISSUE THREAD

**Issue by GiacomoRina** [olivierfriard/BORIS#283]
Hi
I wish to report the following problem
 I have my longest media in player 1. I can offset the media in player 2 fine with just the two medias, and have made observations fine. I can load a second video into player one with no problems, but when I put a second media in player 2, the player with the offset, the offset won't save and all media start playing at the same time. Also, why exactly cant the synchronization work if there are more videos in the 1st player? Is it just a limitation of the program? I hope there is a way around it

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this. In the last version (7.9.8) I added a check that do not allow to play another media suynchronously when many media are queued in the first media player. It was to difficult to manage the synchonization.
To fix this limitation I plan to add a tool for concatenating many video in a unique video file.
Regards
o
