### ISSUE TITLE
Know which subjects are in the same place at the same time

### ISSUE THREAD

**Issue by annanai** [olivierfriard/BORIS#287]
I'm just wondering if there's an existing way to determine who is with whom during an observation. 

I have multiple subjects in a single observation, and I would like to know when the subjects are sheltering together (each shelter is coded as a unique state event). Is there a feature that I'm yet to find that will provide analysis on subjects being in the same place at the same time? Ideally I would like to say 'Subject A spent 60 seconds with Subject B in Shelter 1'.

Thanks for your help!

![Screen Shot 2020-06-05 at 12 28 05 pm](https://user-images.githubusercontent.com/66452762/83830323-2e90e680-a728-11ea-94bd-734b154eaa9a.png)

**Comment by olivierfriard** [comment]
Hi Annanai,

First define all your subjects A, B, C ...
Then code all your subjects (shelter choice with a behavior defined as a
state event) on a single observation.
If you have many subjects you can code them one-by-one.
Export the all the coded events as a behaviors binary table choosing the
adapted time interval (Observations > Export events > behaviors binary
table).
Combine the behaviors of all subjects with your favorite spreadsheet
program and extract the shelter co-presence with formula like
=IF(AND(A1=1,B1=1);"A and B", "")

Regards

o


University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://penelope.unito.it/friard/
http://orcid.org/0000-0002-0374-9872
