### ISSUE TITLE
Problem with Video

### ISSUE THREAD

**Issue by Fragariavesca23** [olivierfriard/BORIS#291]
hi i have a little problem.
On my MacBook the Audio of a MP4 data is working but I have no video.
Does anyone know the problem 
Thanks

**Comment by uvictori** [comment]
I'm having the same issue. The time continues to count up but the video is just a black screen (see below). I haven't been able to find a fix for this online anywhere.
<img width="1560" alt="Screen Shot 2020-06-24 at 1 28 19 PM" src="https://user-images.githubusercontent.com/67430701/85754825-6366dc80-b6db-11ea-9da7-53985c933f57.png">

**Comment by kapilsaxena33** [comment]
Click on frame by frame button it should work.

Sent from a very tiny keyboard of a phone.
________________________________

**Comment by uvictori** [comment]
Thank you! That worked!
