### ISSUE TITLE
Data File Plot Issues

### ISSUE THREAD

**Issue by skyexobile** [olivierfriard/BORIS#292]
I noticed that sometimes when editing an observation, the plot preview after clicking 'show plot' does not always refresh, especially after changing the values for time interval or start time. This actually affects how the plot is displayed when starting an observation.

Also, when an observation is playing, the plot will freeze after some time. Closing the window and reopening the data file plot does not resolve this.

The OS I'm using is MacOS Catalina v. 10.15.4
I have Boris v. 7.9.8

**Comment by olivierfriard** [comment]
This should be fixed in v. 8
