### ISSUE TITLE
Allow for same event to occur at the same time

### ISSUE THREAD

**Issue by saraewise** [olivierfriard/BORIS#312]
I'm coding a single behavior that occurs in very quick succession and is difficult to capture each instance, even in frame-by-frame mode. Is it possible to allow for the same behavior to be coded at the same time for our purposes? 

![Window_2020-08-24_12-23-31](https://user-images.githubusercontent.com/52932103/91076147-acb4a900-e604-11ea-8d0e-8dc3c1852cc5.png)

**Comment by olivierfriard** [comment]
This should be fixed using the v. 8 because the MPV player is much more reactive.
