### ISSUE TITLE
Media file playing but screen black

### ISSUE THREAD

**Issue by eithnekavanagh** [olivierfriard/BORIS#321]
Hi,
I'm having a problem where when I start an observation I can hear the media file playing but the screen is black. Am using MacOS Catalina 10.15.6 on BORIS v. 7.9.16. Have not been able to resolve this and would love help.

Here are details about media file:
LC analysis
State: State.Paused
Media Resource Location: file:///Users/eithnekavanagh/Desktop/Stress%20Study/PPT_01.mp4
File name: PPT_01.mp4
Track: 0/2
Number of media in media list: 1
get time: 9401
duration: 00:01:20.448
Position: 0.1168559193611145 %
FPS: 25.0
Rate: 1.0
Video size: (1080, 1080)
Scale: 0.0
Aspect ratio: None
is seekable? Yes
has_vout? Yes

FFmpeg analysis
File path: /Users/eithnekavanagh/Desktop/Stress Study/PPT_01.mp4
Duration: 00:01:20.450
Bitrate: 3324k
FPS: 25
Has video: True
Has audio: True

Total duration: 00:01:20.450 (hh:mm:ss.sss)

**Comment by CarolineHuuu** [comment]
Hi, I am running into the same problem. My videos are also .mp4 and play fine with VLC. Would really appreciate help getting BORIS to work because it would be a big boost to my work-from-home capabilities. Thanks!

macOS Catalina 10.15.6
BORIS v. 7.9.19

**Comment by eithnekavanagh** [comment]
Hi,
I actually was given a very simple solution by my colleague. Try pressing the rewind button, and then press play. It worked for me!


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by CarolineHuuu** [comment]
!!! Just worked for me too! Thank you so much!

**Comment by eithnekavanagh** [comment]
Great !!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
