### ISSUE TITLE
Issues on MacOS Catalina 

### ISSUE THREAD

**Issue by mjay1999** [olivierfriard/BORIS#327]
Hello! I'm new to BORIS and will be using it for my thesis project. After adding my media in as a new observation, the video opens as a black window that covers the entire screen and I cannot move the window at all. If i click the window or try and move it or adjust the size, I get the following error message: "The Focus area function is not yet available in frame-by-frame mode." If you have any tips or ways to get around this please let me know, thanks in advance!

**Comment by mjay1999** [comment]
Just to clarify a point I missed, the video is clearly playing because I can hear the audio, I am just missing the actual video part. Sorry for not mentioning that before! 

Also, I have been able to constrain the video window now but it is still just completely black.

**Comment by drgrizz** [comment]
I've had this issue as well, though I don't recall seeing the same error message above. All I needed to do was to click the "reset" button (3rd from left in toolbar). Video then appears. 

Hope this helps!

**Comment by mjay1999** [comment]
Like MAGIC! Thank you so much!

**Comment by laomesss** [comment]
Hello I have exactly the same problem. Can anyone help me?
