### ISSUE TITLE
Coding sheet comments do not save

### ISSUE THREAD

**Issue by livethedance** [olivierfriard/BORIS#33]
In the coding sheet, event comments that are entered via edit event screen's comment box are not saved when I click OK. I'm pretty sure this worked in previous versions, but not in 2.66 & 2.7.

OS: Ubuntu 14.04
Boris: 2.7

**Comment by olivierfriard** [comment]
I can not reproduce this problem on my system.
Can you send me the exact procedure in order to reproduce the error you have encountered?
If you run BORIS from sources it will be useful to have the terminal output when the error appears.
Thank you

**Comment by livethedance** [comment]
Sorry it took me so long to get back to this. I tried it on our lab's other computer (same versions of ubuntu and Boris), and I could not reproduce it there either, although it continued to be a problem on the other one. Today we updated linux and Boris (to 2.72) and the comments now save as they should on both computers. Thanks for your time!
