### ISSUE TITLE
Mac OS 10.15.7 video playback issue

### ISSUE THREAD

**Issue by Jml1015** [olivierfriard/BORIS#331]
Hi! 
Whenever I try to run any version more recent than 6.3, I get one of two repeated errors: 

Either the playback screen is black, or any video I do get (i.e. when I hit 'rewind' and a thumbnail appears in place of the black screen), it plays for approx. 2 seconds then the counter continues to run while the screen remains still. 

I've tried re-formatting the video using the tools menu in BORIS to no avail (.avi file that runs fine in VLC). 

Is there anything else I should try? 

Thanks

**Comment by ntowko** [comment]
I have experienced this bug as well on the latest version of BORIS. Running macOS Big Sur on the M1 Macbook Air

**Comment by StephPeriquet** [comment]
I have the same issue as well Boris v. 7.10.2  and macOS Big Sur V11.1 on Mac mini. Using the horizontal bar to move within a video clip has an erratic behaviour.
