### ISSUE TITLE
Runing BORIS on Ubuntu 20.04

### ISSUE THREAD

**Issue by pessoaneto** [olivierfriard/BORIS#339]
Greetings,

I know this section is not for educational purposes, however, I couldn't found a more appropriate place for this. I'm not familiar with the way to install this kind of software. When I try to run the script "start_boris" the terminal doesn't give any feedback. I've permitted it to be executed.

If anyone can offer me a tutorial for installing BORIS it will help me immensely.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
I updated the BORIS Linux download page with some warnings if the program does not run on Ubuntu 20.04:
http://www.boris.unito.it/pages/download_linux
Can you please try if it fixes your problem?

Thank you for your collaboration

Olivier

**Comment by olivierfriard** [comment]
Hi,
I added a deb package that you can download and install with the **Software install** program
It should install all the dependencies automatically.
See https://github.com/olivierfriard/BORIS/releases/tag/v7.9.24
