### ISSUE TITLE
Issues exporting tabular events

### ISSUE THREAD

**Issue by Wallefer94** [olivierfriard/BORIS#350]
I can't export any data in Excel anymore. 
When I try exporting in tabular events an error appears:"'dataset' object has no 'dataset' attribute". Boris saves me an empty .xlsx file (o kb). The only formats I can export are csv and tsv. 

I have a MacBook Pro with macOS Big Sur (Version 11.01) and BORIS v. 7.9.24 - 2020-12-18.

**Comment by olivierfriard** [comment]
bug present only on Mac version

**Comment by olivierfriard** [comment]
This bug should be fixed in the pre-release of v. 7.10.2.
please test it and let me know: https://github.com/olivierfriard/BORIS/releases/tag/v7.10.2

**Comment by Wallefer94** [comment]
Works perfectly now. Thank you very much
