### ISSUE TITLE
boris_7.9.24-0.deb installation error on ubuntu 18.04 

### ISSUE THREAD

**Issue by JXuann** [olivierfriard/BORIS#353]
Hello,

I encountered the error when installing boris on Ubuntu 18.04. Your hints are highly appreciated!

(base) am@lme72:~/Downloads$ sudo apt install ./boris_7.9.24-0.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'boris' instead of './boris_7.9.24-0.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 boris : Depends: python3-tablib (>= 0.9.11) but it is not installable
E: Unable to correct problems, you have held broken packages.
(base) am@lme72:~/Downloads$ sudo dpkg -i /home/am/Downloads/boris_7.9.24-0.deb 
Selecting previously unselected package boris.
(Reading database ... 292508 files and directories currently installed.)
Preparing to unpack .../Downloads/boris_7.9.24-0.deb ...
Unpacking boris (7.10-0) ...
dpkg: dependency problems prevent configuration of boris:
 boris depends on python3-pyqt5 (>= 5.10.1); however:
  Package python3-pyqt5 is not installed.
 boris depends on python3-pyqt5.qtmultimedia (>= 5.10.1); however:
  Package python3-pyqt5.qtmultimedia is not installed.
 boris depends on python3-tablib (>= 0.9.11); however:
  Package python3-tablib is not installed.
 boris depends on graphviz; however:
  Package graphviz is not installed.

dpkg: error processing package boris (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 boris

**Comment by olivierfriard** [comment]
Hi Rachael,

Unfortunately there is no package for tablib for python3 (python3-tablib) for Ubuntu 18.04.
See https://pkgs.org/download/python3-tablib

You have 2 alternatives:
1) upgrade your distribution from 18.04 to 20.04 and you will be able to install BORIS with the deb package
2) use BORIS from the linux64.tar.gz file. you can try the BORIS pre-release available here: https://github.com/olivierfriard/BORIS/releases/tag/v7.10.2

Best,
Olivier

**Comment by JXuann** [comment]
Hi Olivier,

Thanks for your reply! 

How do I install and run Boris from the Boris pre-release linux64.tar.gz file? I saw there is bash script 'start_boris' but nothing happened after I clicked it.

Many thanks in advance!

Best,
Rachael

**Comment by olivierfriard** [comment]
Hi Rachel,
thank you for reporting this
I updated the boris-7.10.2-linux64.tar.gz file in the 7.10.2 pre-release (https://github.com/olivierfriard/BORIS/releases/tag/v7.10.2).
It should now work with Ubuntu 18.04.
If BORIS does not start after double-click on the start_boris file you have to allow the execution of text files from "Files":
Files > Preferences > Behavior > Executable Text Files > Run them
The alternative is to open a terminal from the directory containing the start_boris file (right-click > Open in terminal) and type:
./start_boris
Best regards
o
