### ISSUE TITLE
BORIS issue

### ISSUE THREAD

**Issue by sv14a** [olivierfriard/BORIS#354]
Dear Olivier, 

BORIS v. 7.9.24 on Mac OS worked fine initially, but now the videos are not visible, being replaced by sound only (as described for pre v.7). Any suggestions?

Many thanks, 

Steve

**Comment by Kat687** [comment]
Hi Steve,
I'm using MacOS Mojave and this happens to me as well. What worked for me was to turn on and off the frame-by-frame-mode (i.e. 1. play the video 2. turn on the frame-by-frame-mode 3. play the video again 4. turn off the frame-by-frame-mode again 5. play the video again). If the video is then shown in zoom-mode, just change the size of the video window and it should jump back to normal. It's not a very elegant solution, but it works for me. ;) Hope this helps!
Cheers,
Kat
