### ISSUE TITLE
Repeated crash when trying to save time budget analysis

### ISSUE THREAD

**Issue by CNdJ10** [olivierfriard/BORIS#357]
Hello, I am using BORIS v. 7.9.22 on macOS Mojave 10.14.6. I am unable to save analysis data as the program crashes whenever I try to save the file. I have tried all file type versions. I am running the same BORIS project on a windows OS and everything is working fine. Notes for error message below, I have it saved in it's entirety but not sure what to look for/what any of it means.

Any help much appreciated!

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread

**Comment by olivierfriard** [comment]
Hello,

Is this issue present in the last version of BORIS (v.7.10.2)?
If yes, send me the boris_error.log file
see http://www.boris.unito.it/pages/report_a_bug.html for details

o

**Comment by CNdJ10** [comment]
Hi Olivier,

I just updated to v.7.10.2 and seems to work fine. Thanks so much!

While you are here, where is the best place to ask questions about specific functions of BORIS? (trying to compare inter-rater reliability from two live observations, eg an observation from 2 different projects/computers)

**Comment by olivierfriard** [comment]
There is Gitter:
https://gitter.im/BORIS_software
or the GitHub discussions:
https://github.com/olivierfriard/BORIS/discussions

o
