### ISSUE TITLE
post-hoc adding focal animals and multiple video file locations

### ISSUE THREAD

**Issue by weejosdf** [olivierfriard/BORIS#359]
Greetings:   Our students have been using Boris for coding video collected by black bears wearing camera collars.  As I dig into the datasets it appears the ethogram the students are using does not have any entries for subjects (focal animals), but does have entries for an independent variable labeled "Animal ID".  I can not edit the observations to add subject animal ID because the ethogram section for subjects is blank.  I want to add subjects to the ethogram, but will that affect the observations already collected?  If not, I will then be able to edit those observations to include subjects as appropriate.

And wait, there's more! Various video segments (using this subject-less-ethogram) have been scored for the bear videos, but the videos are stored on multiple different hard drives. Is it possible to move all the videos and observation lists to a single drive without having to re-record the data?  How will that affect the path name?

thanks for the help.....I am hoping this is the worst of the issues!
Sean

**Comment by olivierfriard** [comment]
Hi,

On Sat, Feb 6, 2021 at 1:37 AM weejosdf <notifications@github.com> wrote:

> Greetings: Our students have been using Boris for coding video collected
> by black bears wearing camera collars. As I dig into the datasets it
> appears the ethogram the students are using does not have any entries for
> subjects (focal animals), but does have entries for an independent variable
> labeled "Animal ID". I can not edit the observations to add subject animal
> ID because the ethogram section for subjects is blank. I want to add
> subjects to the ethogram, but will that affect the observations already
> collected? If not, I will then be able to edit those observations to
> include subjects as appropriate.
>

You can add your subjects to the project file without affecting the
observations. Removing subjects or behaviours can be dangerous.
It is always better to do regular backups (with different file names on
different devices) of your project file.
Once the subjects are added to the project you can add it to the recorded
events by editing the event(s)


> And wait, there's more! Various video segments (using this
> subject-less-ethogram) have been scored for the bear videos, but the videos
> are stored on multiple different hard drives. Is it possible to move all
> the videos and observation lists to a single drive without having to
> re-record the data? How will that affect the path name?
>
> 1) move your video in a single directory.
2) save your BORIS project file in the SAME directory
3) Remove the path from the media file (see
https://boris.readthedocs.io/en/latest/#removing-path-of-media-files)

It is better to try first on a copy of your project file

thanks for the help.....I am hoping this is the worst of the issues!
>

Unfortunately no!

o

**Comment by weejosdf** [comment]
Thank you again.  I’ll try these fixes.

You say “unfortunately no!”   What can I expect?

Sean

**Comment by olivierfriard** [comment]
>
>
> You say “unfortunately no!” What can I expect?
>
>
Your issue was not a real issue, just a request of help.

o

**Comment by weejosdf** [comment]
Gotcha….thanks for the help, the program is great.  We really could not score these files without BORIS.

Sean

**Comment by weejosdf** [comment]
Greetings:
I hope I can bother you with some questions regarding our bear research.  Anchorage has a population of urban/wild bears and we employed camera collars to collect energy and diet budgets for the animals.
There are 8 bears, each with a camera collar.  Each camera collar would record a minute of video every 5 minutes, 24 hrs a day.  Every minute of video was in its own file, generating thousands of files.  We combined a bear’s video from one day into a single file for scoring. Thus, we have 8 bears, 24 minutes of video each per day per animal, for about 2 months.  
We have been using BORIS (6.2.4) to score the videos.  The student set up one project with 4 keys for r behaviors, the then added multiple sub keys as modifiers.  The student did not set up subject animal IDs in the ethogram but opted to use independent variable set to animal id.  When scoring the videos the student did not start a new project but would simply continue with the original project.  Each line of the project is an observation of 24 min of video.  Observations from different bears are in the same project but identified by animal id variable (see figure).
I added subject animal to the original ethogram so that observations/events can be edited and newer observations can be assigned a subject animal.  However we then noticed that when scoring video an inadvertent key stroke would change the subject animal.  
Is there a way to lock in a subject animal for an observation session?
If we use JWatcher and Boris analysis programs is a subject animal designation required?  Or can we get by with identifying each line of observation by the independent variable?                                                                                                                                         
Do you foresee problems with continuing to lump everything into one project, rather than have each bear be its own project?  See any pitfalls coming up?  If I download and run the most current version of BORIS (7.10.2) will it still read the files from 6.2.4?

Thank you for any assistance.
Sean
![Captureboris](https://user-images.githubusercontent.com/38670651/107838705-8a9a1900-6d53-11eb-9165-8f7ace5aea79.JPG)
