### ISSUE TITLE
All modifers reset to "none" when editing selected event

### ISSUE THREAD

**Issue by steelemp** [olivierfriard/BORIS#36]
Just upgraded from BORIS 2.55 to latest version 2.72, (running on Windows 7, VLC 2.1.5).

I've noticed that now when editing an existing event, all modifiers are reset to "none". Could this be changed back to how it used to be in earlier versions (I think...) so that selected modifiers are remain unchanged when editing an event and can then be changed only if needed? 

Thanks!

**Comment by olivierfriard** [comment]
fixed in version 2.9

**Comment by steelemp** [comment]
Thanks!
