### ISSUE TITLE
Data analysis crashes

### ISSUE THREAD

**Issue by Brum17** [olivierfriard/BORIS#365]
I have been trying to analyse data footage, that is from a CCTV camera set up, however each time I begin the observation and try to log a behaviour, using a behaviour coding map, the system crashes... is there anything I can do to prevent this?

**Comment by olivierfriard** [comment]
Hi,
If you are using the current version (7.2.10) please send me the
boris_error.log file. See the web site on how to find it (how to report a
bug).
If not, please update your BORIS installation.
Best regards
Olivier


On Saturday, February 20, 2021, Brum17 <notifications@github.com> wrote:
> I have been trying to analyse data footage, that is from a CCTV camera
set up, however each time I begin the observation and try to log a
behaviour, using a behaviour coding map, the system crashes... is there
anything I can do to prevent this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/C1nmPESlNOh0UMZ7eItC9yDvj47xgtzr38w7nsLIhU1VtbokxEuFrqr_phqD9LWPB50LhAFsjHTUb3r6yLLTejJ6t_xSeUa8OUo5yWQImBhCnwZbEkSd4rhhCPI1Fn60DHblI1iw_vKTR53UYK_xr3sSqkBU1OxbG4Gnq-gG4UV2QAd6TvSAILC7GHBFhTJM3miVpKJxbKGLtOPsvR8woL8s3fI=s0-d-e1-ft#https://github.com/notifications/beacon/ABR2AYRMFACIPX5RG7JOWYTS76OSHA5CNFSM4X5ZRJ6KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4MDPEFQA.gif
>

-- 
University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://penelope.unito.it/friard/
http://orcid.org/0000-0002-0374-9872

**Comment by Brum17** [comment]
Hi,

I reinstalled the software and it seems to have solved the problem.
However, when analysing footage I have programmed the ‘fast forward’ button
to 10 minutes but every time I press it, the software skips to random
points within the footage. Is there any way that this can be fixed?

Kind regards,

Ellie

**Comment by olivierfriard** [comment]
Hi,
maybe your video format is not seekable.
Try to re-encode it with the BORIS function (Tools > ..)
https://boris.readthedocs.io/en/latest/#re-encoding-and-resizing-a-video-file
Best,
o

**Comment by Brum17** [comment]
Hi,

I tried this, however this did not work and the video format did not change
format for some reason.
Is there anything else I can do?

Kind regards,

Ellie
