### ISSUE TITLE
Allow manual input of FPS

### ISSUE THREAD

**Issue by Ax3man** [olivierfriard/BORIS#37]
BORIS doesn't recognize the FPS for my video's. They play just fine, but means I cannot use the frame by frame command. Would it be possible to manually edit that value?

**Comment by olivierfriard** [comment]
Hi Ax3man,

what version of BORIS are you using?

Can you send me a sample of your video? Or the output of ffmpeg.

If ffmpeg is not able to extract parameters of your video it would not be
able to extract frames.

Olivier


On Thu, Feb 11, 2016 at 3:05 PM, Ax3man <notifications@github.com> wrote:

> BORIS doesn't recognize the FPS for my video's. They play just fine, but
> means I cannot use the frame by frame command. Would it be possible to
> manually edit that value?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olivierfriard/BORIS/issues/37>.
>



-- 

Dipartimento di Scienze della Vita e Biologia dei Sistemi - Life Sciences
and Systems Biology
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://www.di.unito.it/~friard/
<http://www.personalweb.unito.it/olivier.friard/>

**Comment by Ax3man** [comment]
I used `ffmpeg -i input.wmv -ss 300 -c copy -t 30 output.wmv` to get a file for 30s of one of the video's. You can find that [here](https://drive.google.com/folderview?id=0B-kyqZzMV4v7aWtvRjRIbWlFalE&usp=sharing). The quality has decrease enormously, but the same problem still exists.

Please let me know if I can send you something else that would be of use.

Thanks!
Wouter.

**Comment by olivierfriard** [comment]
The output.wmv file seems to have 30000 frames...
The output of ffprobe is:
```
 Duration: 00:00:30.09, start: 0.000000, bitrate: 21819 kb/s
    Stream #0:0: Video: msmpeg4v3 (MP43 / 0x3334504D), yuv420p, 1920x1080, 1k tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: wmav2 (a[1][0][0] / 0x0161), 48000 Hz, 2 channels, fltp, 128 kb/s
```
note the **1k** value before tbn and tbc, For a 25 FPS video the output is:

`Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 400x400 [SAR 1:1 DAR 1:1], 77 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc
`

The output of ```ffmpeg -i output.wmv -vcodec copy -acodec copy -f null /dev/null 2>&1``` is

```
...
frame=30000 fps=0.0 q=-1.0 Lsize=N/A time=00:00:30.04 bitrate=N/A    
video:2812kB audio:469kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

I extracted all the 30043 frames and noticed that the first 100th frames are identical (i used https://huddle.github.io/Resemble.js/) so I think that it is an artefact of your codec. Do you have some specification about your video recorder?

If you are using v. 2.8 you can:
* create a new project and an observation based on the input.wmv media file.
* Save the project and close it 
* edit the project file (it is a JSON file) replacing the fps value (that should be 0.0) by 25 or whatever you want.

In this case the registred time for the coded events will not match you media time.

```
           "media_info": {
                "length": {
                    "/tmp/input.wmv": 30.09
                },
                "fps": {
                    "/tmp/input.wmv": 25
                }
            }
`

**Comment by Ax3man** [comment]
Ok, if I run `ffmpeg -i output.wmv -vcodec copy -acodec copy -f null /dev/null 2>&1` on the original video file, I get this:

```
Input #0, asf, from 'trial2-1.wmv':
  Metadata:
    WMFSDKNeeded    : 0.0.0.0000
    DeviceConformanceTemplate: @
    WMFSDKVersion   : 12.0.7601.17514
    IsVBR           : 1
    VBR Peak        : 6900097
    Buffer Average  : 105292
  Duration: 02:03:45.13, start: 0.000000, bitrate: 13772 kb/s
    Stream #0:0(eng): Audio: wmav2 (a[1][0][0] / 0x0161), 32000 Hz, 1 channels, fltp, 20 kb/s
    Stream #0:1(eng): Video: wmv2 (WMV2 / 0x32564D57), yuv420p, 1920x1080, 6843 kb/s, 1k tbr, 1k tbn, 1k tbc
```
The video's are recorded from Logitech webcams (C615), using the Logitech webcam software (LWS).

I'll mess around a bit with the JSON file. Otherwise I'll just have to do without the frame by frame.

**Comment by Ax3man** [comment]
If I edit something into the file as the fps, the frame by frame will open. However, regardless of what value I use, the video will only progress every second. So if I put in 25 as the frame rate, it will jump 1 second every 25 frames I skip.

Not sure what is going on, but the 'normal' mode works perfectly fine, so I'll keep using that.

**Comment by olivierfriard** [comment]
You are right for the 25 FPS value

Your camera shoud record at 30 FPS as specified on various web sites.

**Comment by olivierfriard** [comment]
One more question: what are your coding on your video?
We are working on a video tracking software that is beginning to work with mice and ants.
Bye

**Comment by Ax3man** [comment]
Yes, I've tried 30 and 15 as well. The result is the same, it will just, for example, step one second between frames 29 and 30, 59 and 60, etc. These videos are odd though. Windows sees them as having 15fps (by looking at the properties) but there seems to be actually 30fps (when opened in a tracking program like idtracker).

Not exactly sure about the encoding! I can get you a full video tomorrow, if you'd like.
