### ISSUE TITLE
Boris exporting excel files

### ISSUE THREAD

**Issue by HBORIS17** [olivierfriard/BORIS#372]
Good afternoon, 

I have a Mac and every time I try to export aggregated events as excel files I receive these warning messages. Boris and Excel work separately perfectly fine. However, every time I try to export the aggregated events as excel files it does not work. 

<img width="420" alt="Screen Shot 2021-03-02 at 1 48 43 PM" src="https://user-images.githubusercontent.com/79938939/109705924-53ef3b80-7b66-11eb-872f-bc6f1d5ef1c3.png">

<img width="366" alt="Screen Shot 2021-03-02 at 1 49 42 PM" src="https://user-images.githubusercontent.com/79938939/109705897-4afe6a00-7b66-11eb-8ab4-3ffb0d951ba0.png">

**Comment by olivierfriard** [comment]
Hi,
What version of BORIS are you using?
O

On Tuesday, March 2, 2021, HBORIS17 <notifications@github.com> wrote:
> Good afternoon,
>
> I have a Mac and every time I try to export aggregated events as excel
files I receive these warning messages. Boris and Excel work separately
perfectly fine. However, every time I try to export the aggregated events
as excel files it does not work.
>
> <
https://ci4.googleusercontent.com/proxy/v_mybaw8ZZHSUagEDn-ymhhwfs-CSpxbrlUMlqerdTBWSVOMquWMnbRg3lKA3h6k7aJLayiwW5fro8lYEt808PBFBJFbFJItXKSN_pS1lChzHxPOiiLZutLY5ESTCNwbEF8BN1uPRiJRJJdD94RkhhAoyFfNXLiA=s0-d-e1-ft#https://user-images.githubusercontent.com/79938939/109705924-53ef3b80-7b66-11eb-872f-bc6f1d5ef1c3.png
>
>
> <
https://ci4.googleusercontent.com/proxy/7NlcKUZK_3af8O6qJ78yAFSiQOTDzNoUpiMZuH_a040XEtqOlWwCcFBzdpOPL8X3ITrs5-33MkB9PkiAlTftE_138g04I9F7olwGNC9WluCHHx1yePfnqNwody3IjQJo0laZJDAo6qWO1ZECzfSdE2hv4Y3-PAEC=s0-d-e1-ft#https://user-images.githubusercontent.com/79938939/109705897-4afe6a00-7b66-11eb-8ab4-3ffb0d951ba0.png
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/xGMDRAuEdtJSSgZVweiAB-zgR7bkso_GqnVz9Z5Rcn6ERgh-0MJ6C9QxTtSiAIAP81gVmP7Qg295xCo5CrtYdJ37Lu7A6q_hmp5TjJxzBylB6FT907HfaD9tU5qrJwcndakrLLcKdhq0R5MU_Qn8WHtVg1KPghZ0ZFBqqUCCVP_dKJomvObxbMb7SeNh3gbZ3y8e9Ovtn_drtFfgaNDUZFz1cl8=s0-d-e1-ft#https://github.com/notifications/beacon/ABR2AYV7FQ2WBBRJZ4JDL7TTBU6SDA5CNFSM4YPUGG72YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4MHFJPMQ.gif
>

-- 
University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://penelope.unito.it/friard/
http://orcid.org/0000-0002-0374-9872

**Comment by HBORIS17** [comment]
Hello, 

I am using 7.10.2
