### ISSUE TITLE
Calculating time budgets for individual observations

### ISSUE THREAD

**Issue by l-johnsonulrich** [olivierfriard/BORIS#38]
The time budget tool is great, but it'd be nice if it could summarize it by individual observation even when I select all observations. Otherwise I have to analyze time budget by each observation by hand and export by hand which takes forever with 100+ observations.

**Comment by olivierfriard** [comment]
thank you for the suggestion.

**Comment by olivierfriard** [comment]
Feature added in v. 2.99
