### ISSUE TITLE
Enable output annotated frame-by-frame

### ISSUE THREAD

**Issue by galvari** [olivierfriard/BORIS#381]
First of all, many thanks for the software!

Since I work in behavior imaging, a feature I'd like to see implemented is the possibility to extract the output as a time-series indexed by frame instead of by time-stamp.

This way, for example, you can evaluate an AI model performance, by comparing the resulted frames-series to the BORIS-hand-coded output.

cheers!

**Comment by olivierfriard** [comment]
Hi,

this is not possible for now. I plan to add it in a near future.
For now you can add a manually add a column as the results of the time (in seconds) multiplied by the FPS value

Regards

**Comment by olivierfriard** [comment]
the frame index is now present in output

**Comment by galvari** [comment]
many thanks!
