### ISSUE TITLE
BORIS App- Project server- BORIS error

### ISSUE THREAD

**Issue by maharasztra** [olivierfriard/BORIS#387]
Helo,
I try to use BORIS App on a tablet, the problem is that every time I want to transfer the project from my pc to tabled through the Project server as is explained in the guide the project cannot be saved. There is always the note: "BORIS- Error Projet not saved!".
Later the project is visible in "open project" files, but it has very little kb (not as much as on a laptop) and the program automatically closes when you try to open the project. 
Any advice?
Thank You,
Natalia

**Comment by olivierfriard** [comment]
The function to load the BORIS project was changed.
