### ISSUE TITLE
Editing observations where video location is incorrect 

### ISSUE THREAD

**Issue by l-johnsonulrich** [olivierfriard/BORIS#39]
<img width="1157" alt="screen shot 2016-03-28 at 2 22 59 pm" src="https://cloud.githubusercontent.com/assets/14129174/14085976/de283e3e-f4f0-11e5-9a00-6824107870df.png">

I moved to a new computer and was in the process of updating the video locations. The newer versions of  BORIS do not let me edit the observations with the old locations. When I click the "edit" button nothing happens.

**Comment by olivierfriard** [comment]
Hi, thank you for rporting problems.
I will try to reproduce this error as soon as possible

**Comment by olivierfriard** [comment]
This bug should be fixed in the version I released today (2.95)

**Comment by l-johnsonulrich** [comment]
Great thank you!

Best,
Lily
