### ISSUE TITLE
Boris not loading 

### ISSUE THREAD

**Issue by babaeza** [olivierfriard/BORIS#391]
I am trying to use boris to view videos for a project and the system is taking a while to process each step. It takes me about 45 minutes to be able to successfully get to the video. I have deleted and reinstalled Boris onto my laptop 2 times in order to try to fix the problem. The first time, it worked but the second time, which was today, it still took a long time to process each step.

**Comment by olivierfriard** [comment]
Hi,

please see http://www.boris.unito.it/pages/report_a_bug.html

o
