### ISSUE TITLE
Batch Output using "Export Events as Behavior Binary Table"

### ISSUE THREAD

**Issue by MrSh0res** [olivierfriard/BORIS#393]
When using the "Export Events as Behaviors Binary Table" option on multiple observations at once, and selecting the "Full Observation(s)" option, the tables are generated using one singular "full observation" length from the batch (presumably the longest one) rather than making each table the length of the observation it refers to. For example, if a 30-second observation, 60-second observation, and 90-second observation are exported simultaneously, all 3 tables that are created are 90 seconds in duration. The 30-second observation has the relevant 1s and 0s up until that 30-second mark at which point the columns all return 0s up until 90 second mark. The same applies to the 60-second video. The 90-second video is normal since it was originally 90 seconds to begin with. This causes all of the output graphs to be the same size and complicates analysis since the size of the arrays suggests that the trials are longer than they actually are and shearing off extra rows of zeros is another step. Currently, the only way I have been able to get them to come out the correct size is to export them individually; however, when you have 50+ observations the process becomes tedious very fast.

<img width="960" alt="boris 1" src="https://user-images.githubusercontent.com/72987193/117334045-8c154200-ae67-11eb-8177-824405b760ce.png">
<img width="846" alt="boris 2" src="https://user-images.githubusercontent.com/72987193/117334050-8cadd880-ae67-11eb-8028-2dcf72e66842.png">
<img width="960" alt="boris 3" src="https://user-images.githubusercontent.com/72987193/117334053-8d466f00-ae67-11eb-9333-f8ad35aae540.png">

**Comment by olivierfriard** [comment]
Hi,

thank you for reporting this issue.
The problem should be fixed in the v. 7.10.4 just released.
Please confirm

Best regards

o

**Comment by MrSh0res** [comment]
The update fixed the issue. Thank you.
