### ISSUE TITLE
Can playback speed be capped at 60x instead of 8x?

### ISSUE THREAD

**Issue by TeresaLIglesias** [olivierfriard/BORIS#395]
I'm finding BORIS very helpful! Thank you!
I have tons of video and watching at 60x on QuickTime helps me spot events. I can scroll through the video in BORIS but it's making my RSI scream. 8x is the current playback speed cap. Can this be increased to 60x, please?
Thanks!
-Teresa

**Comment by olivierfriard** [comment]
The max play rate was increased to 30 (VLC does not support higher values).
Can you test it and close this request if it is working?

**Comment by olivierfriard** [comment]
With the new version (v. 8) you play your media up to 100x
See http://www.boris.unito.it/pages/boris_v8.html

**Comment by TeresaLIglesias** [comment]
Wow! Thank you! Yes, I got the 30X playback working fine and will install v. 8 to get up to 100x and see how that works for my video analysis too.

**Comment by TeresaLIglesias** [comment]
Done! Thank you so much!


______________________________
*Teresa L. Iglesias, Ph.D.*
Team Leader for Cephalopod Support
Okinawa Institute of Science and Technology (OIST)
OIST Animal Resources Section
email: ***@***.***
Skype: Teresa.L.Iglesias33
Skype Phone Number: +81 (Japan code) 050-5534-0364
https://teresaliglesias.com/
______________________________
