### ISSUE TITLE
Is there a way to set limits on how many times a modifier may be used?

### ISSUE THREAD

**Issue by bensilver95** [olivierfriard/BORIS#413]
For our video coding project, we have one event with many modifiers. We want to make sure every modifier is used exactly once, so I was wondering if there was a way to flag if a modifier has already been used or hasn't been used yet. A bonus would be if a modifier could disappear from the list of modifiers upon it being used.

**Comment by olivierfriard** [comment]
Hi,
there is no such option.
Best regards
