### ISSUE TITLE
Observation recording from participant in locked down environment possible?

### ISSUE THREAD

**Issue by ggogos** [olivierfriard/BORIS#416]
We are attempting to assist a research project at the university that requires participants to view a video and then tap a key like the spacebar at points they watch in the video to register where they are feeling uncomfortable. The environment must be such that they cannot stop the video via a toolbar or media player controls. The video must run it's course (or they may abort with a specific keypress). The client must only be allowed to press the spacebar to log their events and be locked out of doing anything else. They are only to see the video and not any accompanying windows like ethnograms, subjects and event listings. Is this possible? Are there command line calls or configuration settings that can be made to facilitate this?

**Comment by olivierfriard** [comment]
Hi,
it is not possible with BORIS (the space bar is used to play/pause the video) but it should not be so difficult to write a dedicated program to do that.
