### ISSUE TITLE
Data File/Code

### ISSUE THREAD

**Issue by jeb549** [olivierfriard/BORIS#425]
Hello, 

I'm looking to export data from my observational coding in Boris. The most useful format I've found is the Time Budget. However, there are other variables I'm interested in looking at (specifically max and min duration of certain behaviors). Because the time budget output calculates mean duration of a behavior bout, I assume you have some background data file (or at least code for computing this) containing all the durations of bouts of a behavior. Is that something you'd be willing to share with me? I appreciate your help tremendously!!

**Comment by olivierfriard** [comment]
Hello,

you can export your observation(s) in the aggregated events format and extract other variables with Excel or equivalent software.
