### ISSUE TITLE
Offset making video lag

### ISSUE THREAD

**Issue by smallstuff** [olivierfriard/BORIS#427]
Hello! 

The issue I am having is when I add 2 media files (1 in player 1 and 1 in player 2) and I offset either of the videos, the video in player 2 continuously lags and does not play smoothly. For this task I recorded using 2 different cameras to capture 2 different angles of a scene, so I need to offset 1 of the videos so that the video feed is in synch. I have tried converting the videos into a smaller size to see if that helped but it didn't. And I'm having the same issue whether I run BORIS on a MAC or Windows. When I play both medias without any offsetting the video lag goes away and both video play perfectly. I would appreciate any help/ advice with this! Thank you!!

**Comment by smallstuff** [comment]
*Update: Even when I don't offset any of the videos the video in Player #2 begins to lag and kind of stutter. I have tried using different videos and resizing the videos but nothing has made it so both of the videos play smoothly continuously. Has anyone else had that problem/ might know a solution to it?

**Comment by olivierfriard** [comment]
Hi,
Please see http://www.boris.unito.it/pages/report_a_bug.html
