### ISSUE TITLE
Export to .xls doesn't work

### ISSUE THREAD

**Issue by kipstert** [olivierfriard/BORIS#43]
Hi,

I'm trying to export all point and state events of my observations to an excel file for further analysis.
I use the most recent version of BORIS on mac. 
But when I choose 'observations' -> 'export events' -> 'xls' -> 'select all',
I only get to pick a place to save the file, and then nothing happens. 

This isn't only on my mac, but also on the pc's of my colleagues. 
Hope you can help us out, thanks in advance!

**Comment by sskiba05** [comment]
I am having the same issue. Have you found a solution to this? I have the newest version on a MAC

**Comment by olivierfriard** [comment]
Hi,
this bug is fixed in the version 2.98 (experimental).
Installing the v. 2.98 will not overwrite the current installed version.

Thank you for reporting bugs!
