### ISSUE TITLE
Video time does not appear during observation

### ISSUE THREAD

**Issue by DeboraHashiguchi** [olivierfriard/BORIS#431]
I had Boris version 7.10 but VLC was crashing during observations. I downloaded version 8 and the MPV and the video runs normally but the timer doesn't appear during the observation. I need to see the video timing to analyze a behavior. How do I get the timer?

**Comment by olivierfriard** [comment]
Hi,

Delete the configuration file (see https://boris.readthedocs.io/en/latest/#configuration-files) and try again.
