### ISSUE TITLE
Error during the execution of "update_events_start_stop"

### ISSUE THREAD

**Issue by SamantaEsse** [olivierfriard/BORIS#433]
![image](https://user-images.githubusercontent.com/89524837/130790551-80b5e660-6f21-40e6-9d6d-7f9f64f8ebe0.png)

Hi to all,
I have this error coming out when I try to open and start an observation on BORIS (updated to version 7.10.7). If I give the "ok", then the software opens the selected observation without the timings and the start and stop of all the already coded behaviours.
How can I solve this problem and is there a way to recover the missing data of all the coded behaviours?

Many thanks in advance!

**Comment by eineLeipzigerin** [comment]
we have the same issue here. 
many thanks!
cheers, Petra

**Comment by olivierfriard** [comment]
shoud be fixed
