### ISSUE TITLE
Can hear the audio but the video shows black screen

### ISSUE THREAD

**Issue by sakaname** [olivierfriard/BORIS#435]
Duration: 00:40:25.900
Bitrate: 10388k
FPS: 30
Has video: True
Has audio: True

My computer is Mac and it's macOS 11.5.2. I use BORIS v. 7.11.1 - 2021-09-09. When I try to open a new observation, the opened video didn't show anything but a black screen. I can hear the audio though. Can you help me? Thanks.

**Comment by olivierfriard** [comment]
Hello,

I do not have a physical Mac to test (only a VM that do not show the playing video) so it is not easy to fix this kind of problem.

**Comment by olivierfriard** [comment]
Try to use the frame-by-frame mode
