### ISSUE TITLE
Cannot change speed of video

### ISSUE THREAD

**Issue by groocie** [olivierfriard/BORIS#436]
Hello, I am using a MacBook Pro with macOS 11.5.2. I am using BORIS v.7.12.2. For some reason, I can increase the speed of the video showing to make it faster. However, I cannot decrease the speed of the video. For example, if I would like to make the video 0.5x speed, it does not let me. But, it does allow me to make the video 2x speed or 3x speed. I am wondering if it is an issue with BORIS on Mac. Can you please help me? Thanks!

**Comment by olivierfriard** [comment]
Hello,
can you check the "Playback speed step value" in the File > Preferences > Project ?

**Comment by groocie** [comment]
That worked! Thank you!!
