### ISSUE TITLE
Lack "Permission" To Open BORIS (Big Sur 11.6)

### ISSUE THREAD

**Issue by lilyb903** [olivierfriard/BORIS#438]
Hello,

I am unable to open BORIS after downloading the package. My OS is completely up to date, and I'm unsure of what to do because it is not simply an issue of an unidentified developer, but a matter of permissions. 

The error message I get is:
"You do not have permission to open the application “BORIS”.
Contact your computer or network administrator for assistance."

I have tried adjusting the security settings in my system preferences (I'm never given the option to allow BORIS to open despite the developer) and I've also tried most of the terminal code hacks to disable my gatekeeper, which also have had no effect on opening BORIS. I've also tried changing the permissions by double clicking over the file in my finder, using >info >permissions, which are already set to read and write. 

The BORIS version I'm attempting to use us 7.12.2 but I tried the last couple versions as well and it wasn't working.

I'm quite lost and would really appreciate help!

**Comment by olivierfriard** [comment]
Hello,

I cannot reproduce the problem because I do not have an access to MacOS 11.6. I am using a VM with Mac OS 10.14 for development.
Try to launch the program from the terminal to see what are the messages exactly.
The path of the executable should be BORIS.app/Contents/MacOS/boris

**Comment by olivierfriard** [comment]
Hi,
you can try to use Parallels in order to run the Windows version on your mac
Best
Olivier
