### ISSUE TITLE
Boris 2.98 version link not working

### ISSUE THREAD

**Issue by sskiba05** [olivierfriard/BORIS#44]
The download link is no longer working.

**Comment by olivierfriard** [comment]
Hi,

do you mean v. 2.98?
May you send me the link that is not working because I can not reproduce
the problem.

Thank you

Olivier

On Mon, Jun 27, 2016 at 6:26 PM, sskiba05 <notifications@github.com> wrote:

> The download link is no longer working.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/olivierfriard/BORIS/issues/44>, or mute the thread
> <https://github.com/notifications/unsubscribe/AGOgYmoIQXLu1LgIDiccrp_qP__kwPqkks5qP_m6gaJpZM4I_RS6>
> .
>



-- 
University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://www.di.unito.it/~friard/

**Comment by sskiba05** [comment]
Hi Olivier,

Thank you for your response. I am trying to download the Mac 2.98 version. Here is the link:

It states "404: not found" upon clicking it. http://penelope.unito.it/boris/static/archive/boris-2.98.dmg

Thank you for your help.

Best,
Sara

----- Original Message -----

**Comment by olivierfriard** [comment]
Hi,

you have a problem with the redirection from the old site (
penelope.unito.it/boris) to the new one (www.boris.unito.it).

Go to www.boris.unito.it and then on the download page and you will find
the newest versions of BORIS.

Best regards

Olivier

On Mon, Jun 27, 2016 at 8:51 PM, sskiba05 <notifications@github.com> wrote:

> Hi Olivier,
>
> Thank you for your response. I am trying to download the Mac 2.98 version.
> Here is the link:
>
> It states "404: not found" upon clicking it.
> http://penelope.unito.it/boris/static/archive/boris-2.98.dmg
>
> Thank you for your help.
>
> Best,
> Sara
>
> ----- Original Message -----
> From: "Olivier Friard" <notifications@github.com>
> To: "olivierfriard/BORIS" <BORIS@noreply.github.com>
> Cc: "Sara Skiba" <sskiba@kennesaw.edu>, "Author" <
> author@noreply.github.com>
> Sent: Monday, June 27, 2016 2:43:51 PM
> Subject: Re: [olivierfriard/BORIS] Boris 2.98 version link not working
> (#44)
>
> Hi,
>
> do you mean v. 2.98?
> May you send me the link that is not working because I can not reproduce
> the problem.
>
> Thank you
>
> Olivier
>
> On Mon, Jun 27, 2016 at 6:26 PM, sskiba05 <notifications@github.com>
> wrote:
>
> > The download link is no longer working.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/olivierfriard/BORIS/issues/44>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AGOgYmoIQXLu1LgIDiccrp_qP__kwPqkks5qP_m6gaJpZM4I_RS6
> >
> > .
> >
>
>
>
> --
> University of Torino
> Life Sciences and Systems Biology department
> Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
> tel: +39 011 6704542
> http://www.di.unito.it/~friard/
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/olivierfriard/BORIS/issues/44#issuecomment-228837395
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/olivierfriard/BORIS/issues/44#issuecomment-228839742>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGOgYo36pwGEa_wk9zhvyr2VvAnAQ8sAks5qQBvHgaJpZM4I_RS6>
> .
>



-- 
University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://www.di.unito.it/~friard/

**Comment by sskiba05** [comment]
Hi Olivier,

When using the new website, upon clicking the Mac 2.98 download link it immediately redirects to the main download page. It does not unfortunately download any files. 

Best,
Sara

----- Original Message -----

**Comment by olivierfriard** [comment]
Hi Sara,

I really do not understand why the new download page redirects you on the
old one.

In any case the download link is:
http://www.boris.unito.it/static/archive/boris-2.98.dmg

I hope it will work

Best regards

Olivier

On Tue, Jun 28, 2016 at 8:20 PM, sskiba05 <notifications@github.com> wrote:

> Hi Olivier,
>
> When using the new website, upon clicking the Mac 2.98 download link it
> immediately redirects to the main download page. It does not unfortunately
> download any files.
>
> Best,
> Sara
>
> ----- Original Message -----
> From: "Olivier Friard" <notifications@github.com>
> To: "olivierfriard/BORIS" <BORIS@noreply.github.com>
> Cc: "Sara Skiba" <sskiba@kennesaw.edu>, "Author" <
> author@noreply.github.com>
> Sent: Monday, June 27, 2016 5:56:17 PM
> Subject: Re: [olivierfriard/BORIS] Boris 2.98 version link not working
> (#44)
>
> Hi,
>
> you have a problem with the redirection from the old site (
> penelope.unito.it/boris) to the new one (www.boris.unito.it).
>
> Go to www.boris.unito.it and then on the download page and you will find
> the newest versions of BORIS.
>
> Best regards
>
> Olivier
>
> On Mon, Jun 27, 2016 at 8:51 PM, sskiba05 <notifications@github.com>
> wrote:
>
> > Hi Olivier,
> >
> > Thank you for your response. I am trying to download the Mac 2.98
> version.
> > Here is the link:
> >
> > It states "404: not found" upon clicking it.
> > http://penelope.unito.it/boris/static/archive/boris-2.98.dmg
> >
> > Thank you for your help.
> >
> > Best,
> > Sara
> >
> > ----- Original Message -----
> > From: "Olivier Friard" <notifications@github.com>
> > To: "olivierfriard/BORIS" <BORIS@noreply.github.com>
> > Cc: "Sara Skiba" <sskiba@kennesaw.edu>, "Author" <
> > author@noreply.github.com>
> > Sent: Monday, June 27, 2016 2:43:51 PM
> > Subject: Re: [olivierfriard/BORIS] Boris 2.98 version link not working
> > (#44)
> >
> > Hi,
> >
> > do you mean v. 2.98?
> > May you send me the link that is not working because I can not reproduce
> > the problem.
> >
> > Thank you
> >
> > Olivier
> >
> > On Mon, Jun 27, 2016 at 6:26 PM, sskiba05 <notifications@github.com>
> > wrote:
> >
> > > The download link is no longer working.
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/olivierfriard/BORIS/issues/44>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AGOgYmoIQXLu1LgIDiccrp_qP__kwPqkks5qP_m6gaJpZM4I_RS6
> > >
> > > .
> > >
> >
> >
> >
> > --
> > University of Torino
> > Life Sciences and Systems Biology department
> > Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
> > tel: +39 011 6704542
> > http://www.di.unito.it/~friard/
> >
> >
> > ---
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/olivierfriard/BORIS/issues/44#issuecomment-228837395
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/olivierfriard/BORIS/issues/44#issuecomment-228839742
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AGOgYo36pwGEa_wk9zhvyr2VvAnAQ8sAks5qQBvHgaJpZM4I_RS6
> >
> > .
> >
>
>
>
> --
> University of Torino
> Life Sciences and Systems Biology department
> Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
> tel: +39 011 6704542
> http://www.di.unito.it/~friard/
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/olivierfriard/BORIS/issues/44#issuecomment-228888012
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/olivierfriard/BORIS/issues/44#issuecomment-229136805>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGOgYo5GZH5rPQy-vMhqh6XEGJSKpCtyks5qQWXVgaJpZM4I_RS6>
> .
>



-- 
University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://www.di.unito.it/~friard/

**Comment by sskiba05** [comment]
Hi Olivier,

Thank you so much for all of your help! Got it downloaded.

Best,
Sara

----- Original Message -----
