### ISSUE TITLE
Boris getting uninstalled from Macbook Air

### ISSUE THREAD

**Issue by PallabiK** [olivierfriard/BORIS#440]
macOS Big Sur Version 11.6
Processor: 2.2 GHz Dual-Core intel Core i7
RAM 8GB 1600NHz DDR3

I can install BORIS and work on it, but as soon as I out my computer to sleep or turn it off, BORIS gets uninstalled. 
I downloaded BORIS from here http://www.boris.unito.it/pages/download_mac.html
 
Please help me resolve this issue.

**Comment by olivierfriard** [comment]
Hi,

did you fix the problem?

Best 

Olivier

**Comment by PallabiK** [comment]
Hello Olivier

I got access to a windows computer and used BORIS there. I have not tried
to use it on my mac.

Thanks,
Pallabi.

*Pallabi Kundu*

Graduate Teaching Asst

University of Nebraska–Lincoln

School of Biological Sciences
