### ISSUE TITLE
Linux based Python error: "No matching distribution found"

### ISSUE THREAD

**Issue by Newbyc37** [olivierfriard/BORIS#444]
I am attempting to install BORIS on a chromebook using the instructions provided by the BORIS site. I've gone through the process three times, and I always end up with the same two error codes when I finally try the BORIS installation. They are as follows: "Could not find a version that satisfies the requirement PyQt5-Qt5>=5.15.2 (from pyqt5->boris-behav-obs) (from versions: )
No matching distribution found for PyQt5-Qt5>=5.15.2 (from pyqt5->boris-behav-obs)"

Any help would be greatly appreciated!

**Comment by olivierfriard** [comment]
Hi,

sorry for the delay.
I cannot reproduce this problem because I did not have a Chromebook to test.

Best

Olivier
