### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by arielrosea** [olivierfriard/BORIS#452]
Hello I tried to start  the program but after the black screen it crashed and did not go to main BORIS app.

I am using Windows 10 Enterprise V 1909
64 bit operating system
installed RAM is 16GB with 15.8 usable
The processor for the computer is Intel (R) Core (TM) i79700CPU @3.00GHz
The crash error file is C:\Users\alappaar\boris_error.log
I am worried it is because I downloaded BORIS under the same username on three different computers
Please let me know how to fix it!

**Comment by olivierfriard** [comment]
Hi,

I did not receive the boris_error.log file.
Can you attach it?

o
