### ISSUE TITLE
Unable to edit modifiers in events

### ISSUE THREAD

**Issue by cjyun103** [olivierfriard/BORIS#467]
Hi, I'm not sure if I understand correctly but I thought we can edit modifiers within each recorded event. When I clicked on the selected event and chose "edit event", I can only modify the subject, the code (behaviour) and the comment, and I do not see any modifiers (I have multiple sets of modifiers coded). Is this a bug or did I not do it correctly?

![image](https://user-images.githubusercontent.com/64484366/151800633-1286404f-0cd9-4768-a4a4-ab4e2b0a59d5.png)

Thanks!

**Comment by olivierfriard** [comment]
The modifiers should be asked when you close this window.
Please tell me if it is not working

Olivier

**Comment by cjyun103** [comment]
Hi Olivier, thanks so much for the reply! You're right it asks after I "ok" this window. Sorry I kept just closing this window with "x" so never got to see the modifiers! Thanks a million!
