### ISSUE TITLE
Request: option to use key depression instead of key presses for state events

### ISSUE THREAD

**Issue by GHarmata** [olivierfriard/BORIS#47]
It would be nice to have the option to have the option to press and hold a key during a state event, instead of only being able to press the key once for "start" and "stop" of a state event.  This would be helpful in scoring rapidly changing state events to avoid accidentally reversing your observation scoring.  For example, if you accidentally hit a the button twice, all of the subsequent "start" times will become "stop" times.  Having the option to hold down a button to indicate a state behavior would be more of a binary and less confusing.

**Comment by olivierfriard** [comment]
Hi,
BORIS was designed in another way. It would be difficult to add the feature you described.
