### ISSUE TITLE
On-going bar not showing all on-going behaviours

### ISSUE THREAD

**Issue by schertoff** [olivierfriard/BORIS#471]
Hello! Love BORIS, thank you so much for providing this software. I'm having a small problem in that the section of the screen under the time is not showing all of the on-going behaviours. I'm confident that the behaviour is on-going, but it isn't showing up. Any help would be greatly appreciated! Thank you!

**Comment by olivierfriard** [comment]
Hello,

please see: http://www.boris.unito.it/pages/report_a_bug.html
