### ISSUE TITLE
App closes when I send observation to BORIS on my laptop

### ISSUE THREAD

**Issue by Morganelegoff** [olivierfriard/BORIS#474]
When I want to send an observation from my phone (Hyawei 7YP) to BORIS, I enter the URL provided by BORIS, then hit 'send observation' and my app closes without any error messag
e or anything and I have got nothing sent to my BORIS project. Can you help?

**Comment by olivierfriard** [comment]
Hi Morgane,
Please see http://www.boris.unito.it/pages/report_a_bug.html
Best,
Olivier
