### ISSUE TITLE
Project file corrupted

### ISSUE THREAD

**Issue by Lianvv** [olivierfriard/BORIS#478]
Hi! 
We are coding video data and one of the files is corrupted. The file size still is 64KB so it is not empty. 
Is there something that we can do to make it work again? 

Best,
Lian

**Comment by Lianvv** [comment]
Hi! 
I hope you can help me with this, as I was already half way with the video and usually a video takes about 6-8h of work! 

Best,
Lian

**Comment by olivierfriard** [comment]
hi,

did you send me the file by email ?

**Comment by Lianvv** [comment]
Hi! 

Did you already have time to check my file? I have send you the file on March 30th to the e-mail indicated on the website.

Best,
Lian

**Comment by Lianvv** [comment]
HI Olivier, 

That is unfortuneate. I have used that e-mail before. I have resent it a minute ago. 
I hope you'll receive it now. Maybe I am ending up in your spamfolder? 

Best,
Lian
