### ISSUE TITLE
BORIS index error

### ISSUE THREAD

**Issue by tsumtsumi** [olivierfriard/BORIS#481]
Hi, I'm new to GitHub, so not sure how to talk report this, but I am using BORIS for coding some audios for a project. I've made some changes to the ethogram I had initially, and along the way I added some new behaviors. But there is this one behavior that codes fine when I insert it as behavior, but when I insert the wrong behavior and try to change it after by right clicking and editing it, I get this Error: list index out of range in core.py at line #10004
I'm using BORIS version 7.10.5, not sure if this is a bug or something I did wrong when editing the ethogram...

Thanks,
Natsumi

**Comment by olivierfriard** [comment]
Hi,

thank you for reporting this.
Can you reproduce the same error with the last version of BORIS (v. 7.13)?

Best,

Olivier

**Comment by tsumtsumi** [comment]
Hi, the link for the version 7.13 is empty on the site (Page not found · GitHub Pages (unito.it)  I get a 404 error saying. is there somewhere else I can update?
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.
Read the full documentation for more information about using GitHub Pages.    Em quinta-feira, 14 de abril de 2022 11:46:43 BRT, Olivier Friard ***@***.***> escreveu:  
 
 

Hi,

thank you for reporting this.
Can you reproduce the same error with the last version of BORIS (v. 7.13)?

Best,

Olivier

**Comment by olivierfriard** [comment]
Please see http://www.boris.unito.it/pages/download.html
