### ISSUE TITLE
Observation wont play

### ISSUE THREAD

**Issue by LisaHB0** [olivierfriard/BORIS#482]
Hi,
Currently when I try to play my observation the video will play for a split second and then pause itself again. I have deleted and redownloaded the software and this is still an issue.
Unsure if there is a simple fix I am missing. 
Any help would be great
Thank you in advance, 

Lisa

**Comment by olivierfriard** [comment]
Hi Lisa,

please see http://www.boris.unito.it/pages/report_a_bug.html

Best,

Olivier

**Comment by olivierfriard** [comment]
Please try the last version
