### ISSUE TITLE
Frame by Frame crash

### ISSUE THREAD

**Issue by Devanshi128** [olivierfriard/BORIS#483]
I'm using BORIS v 7.13 Windows 11. When I use the frame by frame option the video observation goes blank and the whole program crashes. Also, in one case when I was able to use frame by frame the videos could not be slowed down.

**Comment by olivierfriard** [comment]
Hello,

can you send me the boris_error.log file just after the crash?
See http://www.boris.unito.it/pages/report_a_bug.html for details

Thank you for your collaboration

**Comment by Devanshi128** [comment]
Hello,

11:13:31,983  core l.5740 DEBUG frame_cache_size: 1
11:13:31,984  core l.5794 INFO read recent projects
11:13:31,984  core l.11962 DEBUG args: ['stdout']
[0000022bff8e59f0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
QObject::~QObject: Timers cannot be stopped from another thread
^C


Thank you for your help
Devanshi

**Comment by olivierfriard** [comment]
I do not see any crash info...
Are you sure that it is the boris_error.log file obtained just after the crash?

Olivier

**Comment by Devanshi128** [comment]
Hello,
I have also added a video.

17:40:17,251  core l.560 DEBUG menu_options function
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Desktop\boris-7.13-win64\lib\site-packages\boris\core.py", line 8770, in switch_playing_mode
    globalCurrentFrame = round(globalTime / (1000 / self.fps))
ZeroDivisionError: float division by zero


17:50:13,628  core l.154 DEBUG BORIS started
17:50:13,628  core l.155 DEBUG BORIS version 7.13 release date: 2022-02-22
17:50:13,629  core l.160 DEBUG Operating system: Windows 10 10.0.22000
17:50:13,629  core l.161 DEBUG CPU: AMD64 Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
17:50:13,629  core l.162 DEBUG Python 3.8.2 (64-bit)
17:50:13,629  core l.163 DEBUG Qt 5.15.2 - PyQt5.15.6
17:50:13,809  core l.167 DEBUG Memory (RAM)  Total: 7969.48 Mb  Free: 1779.38 Mb


https://user-images.githubusercontent.com/104515449/165795197-2a1b8fab-4712-4963-b768-accacfe9f63c.mp4

Thank you,
Devanshi

**Comment by olivierfriard** [comment]
Hello,

this bug should be fixed in v. 7.13.3.
Can you confirm please?

You can also try the experimental new version (v. 8) that should work better.
See http://www.boris.unito.it/pages/boris_v8.html for details

**Comment by Devanshi128** [comment]
Hello,

I am unable to get any error report past this.  

[000001f6932959f0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001f6939e2000] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001f6939e2640] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001f6939ed5d0] avcodec decoder: Using D3D11VA (Intel(R) UHD Graphics, vendor 8086(Intel), device 8a56, revision 7) for hardware decoding
[000001f693ad0720] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4


I again attach a video 
https://user-images.githubusercontent.com/104515449/166334943-03d7b11c-c4b2-4774-aebc-817e85475a88.mp4

Thank you
Devanshi

**Comment by Devanshi128** [comment]
Hello,
I received this message while working frame by frame, forward and backward.

BORIS version: 7.13.3
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.6
2022-05-21 01:02

Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Desktop\BORIS\lib\site-packages\boris\core.py", line 10906, in keyPressEvent
    newTime = 1000 * self.FFmpegGlobalFrame / self.fps
ZeroDivisionError: float division by zero

Thank you
Devanshi

**Comment by olivierfriard** [comment]
Hi, this should be fixed in v. 7.13.8
Can you confirm this?
