### ISSUE TITLE
Problem with Boris 7.10 version

### ISSUE THREAD

**Issue by paulabrito016** [olivierfriard/BORIS#484]
I have been using 7.10 Boris version but but the program stops responding and does not work again. 
I've tried to download a newer version without deleting the previous one because my observations are saved in the old version. The new app does not open even after half an hour of waiting. How can I update the program without deleting the previous program with my observations?

**Comment by olivierfriard** [comment]
Please see http://www.boris.unito.it/pages/report_a_bug.html
