### ISSUE TITLE
Repeating sections of video

### ISSUE THREAD

**Issue by tnwilli2** [olivierfriard/BORIS#485]
With the new version, 7.13.3, when a video is uploaded it is sectioned into pieces of video and repeated. For example, a video with 15 frames per second is converted to 67 frames per second; and the total video is quadrupled.

**Comment by olivierfriard** [comment]
Hi,
can you send me a sample of this video?
Do this video play well with previous versions of BORIS?

See http://www.boris.unito.it/pages/report_a_bug.html for details
