### ISSUE TITLE
Issue with double clicking on observations to jump to the time

### ISSUE THREAD

**Issue by JoKunkel** [olivierfriard/BORIS#488]
Hi, 
I upgraded to version 7.13.4 since my old version stopped working after the upgrade to pop!_OS 22.04. It is working now again, except that double clicking on an observation to jump to it in the video causes an error message.
my computer:
Pop!_OS 22.04 LTS, ThinkCentre M81, 16GB RAM, Intel i7-2600
BORIS 7.13.4
video was an .mp4 file without sound

The error log:
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f0873c86740 (most recent call first):
BORIS version: 7.13.4
OS: Linux 5.17.5-76051705-generic #202204271406~1651504840~22.04~63e51bd SMP PREEMPT Mon May 2 15:
CPU: x86_64 x86_64
Python 3.10.4 (64-bit)
Qt 5.15.3 - PyQt 5.15.6
2022-05-11 10:01

Traceback (most recent call last):
  File "/opt/boris/boris/core.py", line 12355, in twEvents_doubleClicked
    self.seek_mediaplayer(newTime)
  File "/opt/boris/boris/core.py", line 3636, in seek_mediaplayer
    self.dw_player[player].mediaplayer.set_time(new_time)
  File "/opt/boris/boris/vlc.py", line 3725, in set_time
    return libvlc_media_player_set_time(self, i_time)
  File "/opt/boris/boris/vlc.py", line 7760, in libvlc_media_player_set_time
    return f(p_mi, i_time)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

**Comment by olivierfriard** [comment]
Hi,
can you send me the version of VLC installed on your system? (vlc --version)
Was VLC installed with snap (check with the "snap list" command) or from a deb package?

Thank you for your collaboration.

**Comment by olivierfriard** [comment]
It was a problem running BORIS with Python 3.10.

The bug should be fixed in v. 7.13.5 just released.
Can you confirm that and eventually close the ticket?

Thank you for your collaboration

**Comment by JoKunkel** [comment]
It now works perfectly.

Thanks a lot!
