### ISSUE TITLE
Boris hangs and crashes when trying to load video file observation

### ISSUE THREAD

**Issue by GHarmata** [olivierfriard/BORIS#49]
This has happened with .wmv and .avi video files.  I was able to get a video to load only one time, in .wmv format.  All other times the application froze.  I am running the program on Mac OS X 10.9.

[EDIT] I believe the problem was having invalid directory name in the folder containing the videos.  It might be nice to have a warning in such cases, instead of crashing the whole program.

**Comment by olivierfriard** [comment]
hi,
can you send me an example of invalid directory name in order to reproduce the crash?

**Comment by GHarmata** [comment]
A folder entitled "ItemA/ItemB" -- apparently Mac OS X 10.9 allows for such a folder name, even though it probably shouldn't
