### ISSUE TITLE
Error when using keypress in v8.4

### ISSUE THREAD

**Issue by JuleMKru** [olivierfriard/BORIS#492]
Hello and thank you very much for this amazing program.
I started working with BORIS, and wanted to try the experimental 8.4 version. When using a keypress for coding, I am receiving this error:

BORIS version: 8.4
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.4
2022-05-14 14:08

Traceback (most recent call last):
  File "C:\Users\Jule\BORIS\lib\site-packages\boris\core.py", line 4725, in keyPressEvent
    if self.dw_player[0].mediaListPlayer.get_state() == self.vlc_playing:
AttributeError: 'DW_player' object has no attribute 'mediaListPlayer'

Is there something that I did wrong in the installation process/something I can do that might help here? I will for now move to v.7.13.5, where this error does not appear, but maybe this feedback is helpful for you anyways.

Best,
Jule

**Comment by olivierfriard** [comment]
Hello,
thank you for reporting, it is very useful.
I will check this as soon as possible
Olivier

**Comment by olivierfriard** [comment]
Hello,
the bug should be fixed in the  v.8.4.1 that was just released. https://github.com/olivierfriard/BORIS/releases/tag/v8.4.1
Can you confirm this?

Thank you for your collaboration

**Comment by JuleMKru** [comment]
Yes, this seems to work now, thanks a lot!
