### ISSUE TITLE
Modifiers not exported in binary table

### ISSUE THREAD

**Issue by scail001** [olivierfriard/BORIS#498]
Hi, 

I am exporting my behavioural data as binary tables for each subject and I would like to have a column for each combination of behaviour+modifier. To do that, I select all my behaviours and tick the box "Include modifier", however on the extracted file I only get the behaviours as columns and none of the behaviours appear (even though they were coded).

Should I do something esle during the extraction process or is there something wrong with this feature? 
I am using BORIS v. 7.13.6

Thanks in advance!
Alice

**Comment by olivierfriard** [comment]
Hi,
I am not able to reproduce the bug.
Can you send me a project file and a detailed procedure?
By email please

**Comment by scail001** [comment]
Hi, 
No actually it works well. Sorry for the inconvenience, I will close this issue.
