### ISSUE TITLE
media file not loading properly

### ISSUE THREAD

**Issue by gina-williams** [olivierfriard/BORIS#499]
**Describe the bug**
When attempting to edit a new observation, the file appears to open but there is no video, or time information, but sound plays. This is true for new and old projects and new and old observations, regardless of video location or type. If I download much older versions of BORIS (ones that have the download as mac64 instead of macos, such as 7.7.3), the software works properly but at a terribe resolution, so older versions are not an option.

**To Reproduce**
1. Go to 'Edit Observation'
2. Click on '[any observation]'
3. Scroll down to 'Start'

**Expected behavior**
Video should play and display time information at the top of the screen.

**Screenshots**
<img width="1276" alt="Screen Shot 2022-06-09 at 1 28 03 PM" src="https://user-images.githubusercontent.com/44176092/172939056-d46d59ba-79ec-4c98-804c-0e0eada1670b.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey (v12.4)
 - BORIS Version: 7.13.6

**Comment by olivierfriard** [comment]
Hello,

thank you for reporting this.
Unfortunately I cannot reproduce this issue because I cannot access a mac computer with 12.4.

You have various possibilities to circumvent this issue:
* use the frame-by-frame mode (check the Preferences to maybe save the frame in memory). You will not have audio.
* use a program that will let you running Windows or Linux programs on your mac (like Parallels Desktop)
* use a Windows or Linux based computer

**Comment by gina-williams** [comment]
Hi,

Thank you for your response. Frame-by-frame mode shows the video, so I will use this for now.

**Comment by AlexandraChilds** [comment]
I experienced the same problemas gina-williams running on OS BigSur version 11.6.6
with a 2.2 GHz Quad-Core Intel Core i7 processor
and 16 GB 1600 MHz DDR3 memory
using BORIS v.7.13.6
The video and audio were both working when I was coding 2 days ago, unfortunately the frame-by-frame solution did not work for me
I have tried re-downloading and installing the program but that has not worked either. Unfortunately I don't have access to a Linux or Windows computer so I will try Parallels Desktop however I in the past I have found that this has caused its own problems. At least I will be able to use v 8 though!
It could also be that my computer is quite old and tired

**Comment by katie-beachem** [comment]
I am having the same issue and need the sound as I am looking at communication behaviors. I do not have Parallels desktop, has anyone found another solution?
I also have a Mac running macOS Monterey 12.4.

**Comment by katie-beachem** [comment]
I have also tried re-encoding and resizing the video but that won't work either.

**Comment by katie-beachem** [comment]
@olivierfriard I also tried the frame-by-frame mode to see if that would work. It will not show the video still.
