### ISSUE TITLE
Error when editing exclusion matrix in BORIS 8.6.1

### ISSUE THREAD

**Issue by tsumtsumi** [olivierfriard/BORIS#500]
Hi, I recently updated my BORIS v 7.10 to 8.6.1 and some behaviors werent excluding ones they were used to, and some would pop up at the end of where my observation was, not at the time I stamp I was retroactively trying to insert or change the bahavior. When I try to edit the exclusion matrix of my ethogram I get an pop up error saying:

Traceback(most recent call last): File "C:\Users\MyName\BORIS\lib\site-packages\boris\project.py", line 733, in twBehaviors_cellDoubleClickedself.pbExclusionMatrix_clicked()
AttributeError: 'projectDialog' object has bo attribute 'pbExclusionMatrix_clicked'

It the gives me the option to abort or ignore option and try to continue. And when I clicked abort (bc I was affraid to loose my super long ethogram, not sure how these things work...) the whole program shut down and I had to relaunch it.
I'm using Windows 10 10.019041

Thanks
Natsumi

**Comment by olivierfriard** [comment]
Hi,
should be fixed in v. 8.6.2
https://github.com/olivierfriard/BORIS/releases/tag/v8.6.2

Thank you for reporting this
