### ISSUE TITLE
Error when clicking frame by frame button

### ISSUE THREAD

**Issue by AYP1098** [olivierfriard/BORIS#501]
**Describe the bug**
Error message:
BORIS version: 7.13.6
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64
CPU: x86_64 i386
Python 3.8.1 (64-bit)
Qt 5.15.2 - PyQt 5.15.6
2022-06-14 18:35

Traceback (most recent call last):
File "/Users/phoenixauyeung/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/boris/core.py", line 13770, in play_activated
self.play_video()
File "/Users/phoenixauyeung/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/boris/core.py", line 13686, in play_video
logging.debug(f"position: {self.getLaps()}")
File "/Users/phoenixauyeung/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/boris/core.py", line 11911, in getLaps
memLaps = Decimal(self.FFmpegGlobalFrame * (1000 / self.fps) / 1000).quantize(Decimal(".001"))
ZeroDivisionError: float division by zero

**To Reproduce**
1. Go to Observations
2. Create new observation, import media (wmv file) 
3. click on "frame by frame" button

**Expected behavior**
the video is usually not visible when starting, but clicking the frame by frame button would give me a centered image / frame to begin. 

**Desktop (please complete the following information):**
 - OS: [macOS Catalina 10.15.7 ]
 - BORIS Version 7.13.6

**Comment by AYP1098** [comment]
Hi Oliver,

This is the information that I was able to find: 
Data rate 1160kbps
Total rate 2572kbps 
Frame rate 15.00 frames / second 

I have also attached a screen shot of the media info. Please let me know if there is anything else I can provide. Thank you so much!

**Comment by olivierfriard** [comment]
Please use Tools > Media file information and paste the output

**Comment by AYP1098** [comment]
Hi Oliver, 

Please find the info below:

FFmpeg analysis

File path: /Volumes/ADATA UFD/Galea/Cohort 3 FST2/LIKT_FOBX_FST2 o(OPPOSITEORDER).wmv
Duration: 00:06:16.520
Number of frames: 0
Bitrate: 355k
FPS: 0
Has video: True
Has audio: True

Thanks!

**Comment by olivierfriard** [comment]
Hi,
the number of frames and frame by second are not recognized.
You have to re-encode your video.
See https://boris.readthedocs.io/en/latest/#re-encoding-and-resizing-a-video-file

**Comment by AYP1098** [comment]
Thank you Oliver!
