### ISSUE TITLE
Move away the "Delete all events" from "Delete selected events": too dangerously close!

### ISSUE THREAD

**Issue by luiandresgonzalez** [olivierfriard/BORIS#502]
The proximity between these two items in the contextual menu is not very functional. The "Delete all events" is not in the context of the selected items, nor foolproof (someone might accidentally click on it when intending to delete just selected events). I would move this nuclear option out of the contextual menu and leave it in the Observations menu bar item.

**Comment by olivierfriard** [comment]
Implemented in v. 8.6.2
https://github.com/olivierfriard/BORIS/releases/tag/v8.6.2

Thanks
