### ISSUE TITLE
Unable to Launch in windows 10

### ISSUE THREAD

**Issue by AlexandraChilds** [olivierfriard/BORIS#504]
**Describe the bug**
Unable to Launch BORIS 8.6.1 or 7.13.6 on Windows 10
Running through Parallel Desktop on a MacOS BigSur 11.6.6  

**To Reproduce**
1. Go to 'start_boris' in both win64 versions
2. Click on file, the program lunch window opens for less than a second before crashing

**Expected behavior**
I expected BORIs to launch after a while as it did when I first downloaded it yesterday.

**Screenshots**
Unfortunately I can't do that as there is no error message.

**Desktop (please complete the following information):**
 - OS: Windows 10 run by Parallel Desktop on MacOS BigSur 11.6.6 - 2.2 GHz Quad-Core Intel Core i7
 - Tried BORIS Version 8.6.1 and 7.13.6
 - I was experiencing problems with the Mac version (again worked perfectly for the first few days) where when playing the video there was audio but no visual and frame-by-frame did not work for me which is why I switched to windows
 - I have tried reinstalling and redownloading

**Comment by olivierfriard** [comment]
Hi,

did you install BORIS in the Windows file system?
C:\Users\...

**Comment by AlexandraChilds** [comment]
Fourth installment seemed to be the charm, couldn't source the problem but thank you for you help and creating the software!

**Comment by AlexandraChilds** [comment]
and use I did use the file system, could be that my computer is just old
