### ISSUE TITLE
Total length in synthetic time budhey does not match trial length

### ISSUE THREAD

**Issue by janayfox** [olivierfriard/BORIS#505]
**Describe the bug**
When exporting the synthetic time budget the total length (s) does not match the total length of the trial. It seems to be random numbers (I can't figure out a pattern). I have limited the trial to 600s specifically and checked that it is running for that long when coding.

**Expected behavior**
I expected that it would be the length of the trial but maybe this is not right?

**Desktop (please complete the following information):**
 - OS: Big Sur 11.6
 - BORIS Version BORIS v. 7.12.2

**Comment by olivierfriard** [comment]
Hi,
what do you mean by "total length of the trial"?
What time interval do you chose for your analysis?
