### ISSUE TITLE
This project file seems corrupted 7.12.2 and update-event-starts-stop

### ISSUE THREAD

**Issue by Alice5432** [olivierfriard/BORIS#506]
I was working on BORIS when it crashed. It was version 7.12.2. Not doing anything unusual, when I tried to re-open the file, it flashed "Project file seems corrupted" -- the file is now 0 bytes so I'm assuming the data is lost. This file is gone completely. It's sad, I"ve been working on it for a long time and just left a few hours I'll finish all of them.
I can reopen the other files, it shows "update-events-start-stop", the timing record is gone, and the video play normally, but I can't record anything. 

Thank you!!!

**Comment by olivierfriard** [comment]
Hi,
remember to backup your important data.

What do you mean by "it shows update-events-start-stop" ?

Please send me a detailed procedure to reproduce the problem.

Thank you for your collaboration
