### ISSUE TITLE
Transition Matrix

### ISSUE THREAD

**Issue by gakleven** [olivierfriard/BORIS#51]
The analysis for Transition Matrix appears to be missing from version 2.995. That's too bad as I started using Boris primarily for that analysis. Any plans to reincorporate it?

**Comment by olivierfriard** [comment]
Hello,

the **transitions matrix** and **flow diagram** tools were added in the v. 2.996 (the current version now).
See the history for details:
https://github.com/olivierfriard/BORIS/wiki/BORIS-revision-history
