### ISSUE TITLE
Modifiers duplicating on ethogram. 

### ISSUE THREAD

**Issue by stemcdo** [olivierfriard/BORIS#510]
**Describe the bug**
When I try to add a modifier to my observation of events some of the modifiers will duplicate modifiers that I am not using a keycode for. For example, if I place modifier VIII, it will also place XVIII at that same time interval and then place it at the bottom of the observation page as well. 

**To Reproduce**
1. Have observation open. 
2. Click on keycode.
3. Observe keycode placement of modifier (VIII) and simultaneously separate start keycode (XVIII)
4. When you try to delete the XVIII it will delete the VIII as well. This is not only happening to those specific state modifiers, but to others such as V and X. 

**Expected behavior**
I expect one keycode to attach one modifier when pressed and not add in a modifier that did not occur. 

**Screenshots**
![image](https://user-images.githubusercontent.com/108446455/176590586-99ea6f36-34c7-4894-9946-fd90688ca3e7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BORIS Version 8.6.1

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).
BORIS version: 8.6.1
OS: Windows 10 10.0.19041
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.6
2022-06-29 23:08

Traceback (most recent call last):
  File "C:\Users\16602\BORIS\lib\site-packages\boris\project.py", line 770, in twBehaviors_cellDoubleClicked
    addModifierWindow = add_modifier.addModifierDialog(
  File "C:\Users\16602\BORIS\lib\site-packages\boris\add_modifier.py", line 75, in __init__
    dummy_dict = json.loads(modifiers_str) if modifiers_str else {}
  File "C:\Users\16602\BORIS\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\16602\BORIS\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\16602\BORIS\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by olivierfriard** [comment]
Hi,
can you reproduce the problem with version 8.6.2 ?
