### ISSUE TITLE
Essential Video Effects (Brightness, Contrast, Saturation, Etc)

### ISSUE THREAD

**Issue by DigDigDig** [olivierfriard/BORIS#515]
Hello,

I utilize BORIS for analysis of towed seafloor video and frequently need to analyze footage that is impaired by low light and high turbidity (cloudy water).

In the past I have used VLC to perform my analysis work and greatly benefited from the basic video effect controls that they have attached to the player.  Having control over video Hue, Saturation, Brightness, Contrast, Sharpness, etc. during playback would be hugely helpful for me in BORIS.  

Thank you for the wonderful bit of software!

-Steve

**Comment by olivierfriard** [comment]
Hello Steve,

some of these features are implemented in v. 8
see http://www.boris.unito.it/pages/boris_v8.html for details and the relative documentation:
https://boris.readthedocs.io/en/master/#video-equalizer

**Comment by DigDigDig** [comment]
Brilliant!  Thank you for letting me know, I'll be downloading the experimental version today and trying things out!
