### ISSUE TITLE
Focal subjects inconsistent when editing 

### ISSUE THREAD

**Issue by Redbull1931** [olivierfriard/BORIS#518]
**Describe the bug**
When reviewing annotated video, new behaviors timestamp correctly but at the bottom of the table, instead of where they should. Not sure if related, but this results in the "active" state event being omitted from the listed state events 

**To Reproduce**
1. Start an observation. Start a behavior that is exclusive of another
2. Switch to the exclusive behavior. 
3. Repeat. 
4. Go back to sometime between the events and start another exclusive state event. 
5. Scroll down to the bottom of the Events table. 
6. See error.
7. For further evidence, play video from the edited portion; behavior will not be listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/110257868/181827971-f21b0586-9baa-4a83-85b2-721a2f3d7fc9.png)

**Desktop (please complete the following information):**
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - BORIS Version

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

**Comment by olivierfriard** [comment]
Hi,

some improvements were made in v. 8.8.
Can you test if the issue is still present and let me know?
