### ISSUE TITLE
[BORIS version 8.6.3] Filter Events Error

### ISSUE THREAD

**Issue by rvtmsw** [olivierfriard/BORIS#519]
**Describe the bug**
The Filter Events feature is error, while accessing it from right-click menu on the Events for observation table.

**To Reproduce**
1. Go to 'Events for ... observation table'
2. Right-click on 'an event in the table'
3. Select the 'Filter Event'
4. See the error window.

**Expected behavior**
I want to filter the event by subject.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11, but registered as Win10 in BORIS
 - BORIS Version 8.6.3

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

--------------------------------------------
BORIS error occured
An error has occured:
BORIS version: 8.6.3
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, Genuinelntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.7
2022-07-30 17:13
Traceback (most recent call last):
File "E:\OneDrive - Institut Teknologi Bandung \BORIS\00 Software\boris-8.6.3-
win64\lib\site-packages\boris\connections.py", line 89, in
self.actionFilter_events.triggered.connect(lambda:
event_operations.filter_events(self))
File "E:\OneDrive - Institut Teknologi Bandung\BORIS\00 Software\boris-8.6,3-
win64yib\site-packages\boris\event_operations.py",line 166, in filter_ events
parameters = select_subj_behav.choose_obs_subj_behav_category(
File "E: \OneDrive - Institut Teknologi Bandung BORIS\00 Software boris-8.6.3-
win64)lib\site-packages\boris\select_subj_behav.py",line84,in
choose_obs_subj_behav_category
if maxTime.is nanO:
AttributeError: 'int' object has no attribute 'is_nan'
to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard
Thank you for your collaboration!

**Comment by olivierfriard** [comment]
Hi,
should be fixed in v. 8.6.5 
https://github.com/olivierfriard/BORIS/releases/tag/v8.6.5
Thank you for your collaboration

**Comment by rvtmsw** [comment]
Again, Thank You @olivierfriard
V.8.6.5 works great!
