### ISSUE TITLE
[BORIS version 8.6.3] Create Transition Matrix Error

### ISSUE THREAD

**Issue by rvtmsw** [olivierfriard/BORIS#520]
**Describe the bug**
I want to make a transition matrix for the transition flow diagram.

**To Reproduce**
1. Go to the 'Observation tab on the menu bar'
2. Click on 'Create transition matrix'
3. Select 'Frequency of transition'
4. See an error

**Expected behavior**
Creating a saved file of a transition matrix (.tsv)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit
 - BORIS Version 8.6.3

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

- BORIS error occurred
An error has occurred:
BORIS version: 8,6,3
OS: Windows 10 10.0,22000
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, Genuinelntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.7
2022-07-31 13:54
Traceback (most recent call last):
File "E: \OneDrive - Institut Teknologi Bandung\BORIS\00 Software\boris-8.6.3-
win64 lib\site-packages\boris\connections.py", line 144, in
self.actionAll_transitions.triggered.connect(lambda:
transitions.transitions_matrix(self, "frequency"))
File "E:) OneDrive - Institut Teknologi Bandung\BORIS,00 Software\boris-8.6.3-
win64)lib\site-packages\boris\transitions.py", line 183, in transitions_matrix
plot_parameters = select_subj_behav.choose_obs_subj_behav_category(
File "E: \OneDrive - Institut Teknologi Bandung\BORIS\00 Software\boris-8.6.3-
win64\lib\site-packages\boris\select_subj_behav.py",line84,in
choose obs_subj _behav_ category
if maxTime.is nanO:
AttributeError: 'int' object has no attribute 'is nan'
to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

**Comment by olivierfriard** [comment]
Hi,
should be fixed in v. 8.6.5 
https://github.com/olivierfriard/BORIS/releases/tag/v8.6.5
Thank you for your collaboration

**Comment by rvtmsw** [comment]
@olivierfriard,

NO, I Thank You.
Well done!
