### ISSUE TITLE
[BORIS Version 8.6.3] 'pause' button lagging and 'edit event' button not working

### ISSUE THREAD

**Issue by cbirdferrer** [olivierfriard/BORIS#521]
Hi! I wanted to start by saying that BORIS is an awesome software. I'm using it to annotate over 2000 videos for my PhD and have found it suits the needs of my project very well.

I started using it on a Mac (BORIS v7) but found that the video files were loading very slowly and the video would freeze and then skip ahead a few seconds. I switched to frame by frame mode which worked for a bit, but recently the frame by frame play back has slowed down substantially enough that its no longer efficient for me to annotate the videos using that mode. From reading through some other issues on this GitHub and you description of BORIS v8, I decided to try switching to that. Since I have a Mac I tried testing v8 both through parallels and on a windows 10 desktop in my lab.

I have encountered two major issues. Any solutions or advice would be much appreciated. 

_**First, the 'pause' button is lagging and BORIS is temporarily freezing.**_

**Describe the bug**
Typically, the first observation I annotate after launching BORIS runs smoothly, after that, the 'pause' button stops working (I've tried using both the space bar and the pause button in the top bar). The video continues playing, but at the top of the screen it says '(Not Responding)' and hitting pause does not pause the video.

**To Reproduce**
1.Create observation
2.Hit pause button at any point in the video

**Expected behavior**
The video will continue playing without pausing. Eventually the program will say "Not Responding", then after some time the video will resume. 

**Screenshots**
Screenshot attached
![Screen Shot 2022-08-01 at 10 37 11 AM](https://user-images.githubusercontent.com/30982700/182431717-f7d7f427-16ec-43fd-a355-d0b03b936b5f.png)

**Desktop (please complete the following information):**
 - windows 10 (this has happened to me when running windows through both parallels and on a desktop windows machine)
 - BORIS Version 8.6.3

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).
It doesn't crash but I've attached the log files from parallels and the desktop and a error log from one BORIS run.

[boris_windows10_desktop.log](https://github.com/olivierfriard/BORIS/files/9244199/boris_windows10_desktop.log)
[boris_error_windows10_parallels.log](https://github.com/olivierfriard/BORIS/files/9244200/boris_error_windows10_parallels.log)
[boris_windows10_parallels.log](https://github.com/olivierfriard/BORIS/files/9244201/boris_windows10_parallels.log)

_**Second, the 'edit event' button is not working**_

**Describe the bug**
When I try to edit an event timestamp by right-clicking on the event and selecting 'edit event', it allows me to edit but when I hit "OK", nothing happens, the window does not go away, the change is not saved, and I end up having to cancel the edit.

**To Reproduce**
1.Create new event
2.Right click on event
3.Select 'edit event'
4.Change the timestamp
5.Hit 'ok'

**Expected behavior**
The 'edit event' window will not close and the changes will not save

**Desktop (please complete the following information):**
 - windows 10
 - BORIS Version 8.6.3

**Comment by olivierfriard** [comment]
Hi,
sorry for the delay
Is the issue still present in the last version?

**Comment by cbirdferrer** [comment]
Hi,  Nope! These issues are no longer present in the current version. Thanks!
