### ISSUE TITLE
Crash when attempting to use geometry tool (v. 8.6.5)

### ISSUE THREAD

**Issue by PavoPavan** [olivierfriard/BORIS#523]
**Describe the bug**
BORIS (v. 8.6.5 2022-08-01) crashes when attemting to use "Geometric measurement" from "Tools" menu.

**To Reproduce**
1. Open a project
2. edit an observation
3. try to use geometric measurement
4. crash

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10, 64bit
 - BORIS Version 8.5.6

16:55:18,273  core l.140 INFO BORIS started
16:55:18,273  core l.141 INFO BORIS version 8.6.5 release date: BETA 2022-08-01
16:55:18,273  core l.142 INFO Operating system: Windows 10 10.0.19041
16:55:18,273  core l.143 INFO CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
16:55:18,273  core l.144 INFO Python 3.8.2 (64-bit)
16:55:18,273  core l.145 INFO Qt 5.15.2 - PyQt 5.15.7
16:55:18,442  core l.149 INFO Memory (RAM)  Total: 7872.26 Mb  Free: 2156.14 Mb
16:55:19,504  utilities l.882 DEBUG test ffmpeg path output: b'ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers\r\nbuilt with gcc 9.2.1 (GCC) 20200122\r\nconfiguration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt\r\nlibavutil      56. 31.100 / 56. 31.100\r\nlibavcodec     58. 54.100 / 58. 54.100\r\nlibavformat    58. 29.100 / 58. 29.100\r\nlibavdevice    58.  8.100 / 58.  8.100\r\nlibavfilter     7. 57.100 /  7. 57.100\r\nlibswscale      5.  5.100 /  5.  5.100\r\nlibswresample   3.  5.100 /  3.  5.100\r\nlibpostproc    55.  5.100 / 55.  5.100\r\n'
16:55:19,504  utilities l.883 DEBUG test ffmpeg path error: b''
16:55:19,819  menu_options l.31 DEBUG function: menu_options
16:55:19,819  menu_options l.190 DEBUG function: menu_options finished
16:55:19,819  config_file l.42 DEBUG read config file: C:\Users\utente\.boris
16:55:19,819  config_file l.65 DEBUG restore geometry
16:55:19,841  config_file l.76 DEBUG saved state: b'\x00\x00\x00\xff\x00\x00\x00\x00\xfd\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\xbe\x00\x00\x00\x9c\xfc\x02\x00\x00\x00\x01\xfb\x00\x00\x00\x14\x00d\x00w\x00S\x00u\x00b\x00j\x00e\x00c\x00t\x00s\x01\x00\x00\x03G\x00\x00\x00\x9c\x00\x00\x00u\x00\xff\xff\xff\x00\x00\x00\x02\x00\x00\x07\x80\x00\x00\x03\x05\xfc\x01\x00\x00\x00\x02\xfc\x00\x00\x00\x00\x00\x00\x07\x80\x00\x00\x05\x84\x00\xff\xff\xff\xfc\x01\x00\x00\x00\x02\xfb\x00\x00\x00\x14\x00d\x00w\x00E\x00t\x00h\x00o\x00g\x00r\x00a\x00m\x01\x00\x00\x00\x00\x00\x00\x00\xcd\x00\x00\x00]\x00\xff\xff\xff\xfb\x00\x00\x00\x0e\x00p\x00l\x00a\x00y\x00e\x00r\x001\x01\x00\x00\x00\xd2\x00\x00\x06\xae\x00\x00\x05"\x00\xff\xff\xff\xfb\x00\x00\x00\x1c\x00d\x00w\x00O\x00b\x00s\x00e\x00r\x00v\x00a\x00t\x00i\x00o\x00n\x00s\x03\x00\x00\x029\x00\x00\x00:\x00\x00\x05B\x00\x00\x03\xcd\x00\x00\x06\xbd\x00\x00\x00\x9c\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x08\xfc\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x0e\x00t\x00o\x00o\x00l\x00B\x00a\x00r\x01\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00'
16:55:19,841  config_file l.84 DEBUG time format: hh:mm:ss
16:55:19,841  config_file l.92 DEBUG Time/fast_forward_speed: 1
16:55:19,841  config_file l.100 DEBUG Time/Repositioning_time_offset: 0
16:55:19,841  config_file l.108 DEBUG Time/play_rate_step: 0.1
16:55:19,841  config_file l.122 DEBUG Autosave: 0
16:55:19,841  config_file l.132 DEBUG behavioural_strings_separator: |
16:55:19,841  config_file l.140 DEBUG close_the_same_current_event: False
16:55:19,841  config_file l.148 DEBUG confirm_sound: False
16:55:19,841  config_file l.155 DEBUG alert_nosubject: False
16:55:19,841  config_file l.161 DEBUG beep_every: 0
16:55:19,841  config_file l.168 DEBUG tracking_cursor_above_event: False
16:55:19,841  config_file l.190 DEBUG check_for_new_version: True
16:55:19,841  config_file l.199 DEBUG pause_before_addevent: True
16:55:19,841  config_file l.207 DEBUG last_check_for_new_version: None
16:55:19,841  config_file l.216 DEBUG ffmpeg_cache_dir: 
16:55:19,841  config_file l.225 DEBUG ffmpeg_cache_dir_max_size: 0
16:55:19,841  config_file l.234 DEBUG frame_bitmap_format: PNG
16:55:19,841  config_file l.315 INFO read recent projects
16:55:19,841  core l.5263 DEBUG args: []
16:57:03,279  project_functions l.883 DEBUG open project: G:/.shortcut-targets-by-id/1oybwJrKogz2mnVJv65-Pl9WfKCCt-ilX/zz. Sbobinature Davide/Clerprem/BORIS/MR - CP2 - Finitura su Espansi (C2) - POSTURE.boris
16:57:03,295  core l.2580 DEBUG initialize new project...
16:57:03,295  menu_options l.31 DEBUG function: menu_options
16:57:03,295  menu_options l.190 DEBUG function: menu_options finished
16:57:14,994  core l.2129 DEBUG function: display statusbar info: Cleprem_FinituraEspansi_POSTURE
16:57:14,995  observation_operations l.864 DEBUG media_info: {'length': {'G:/.shortcut-targets-by-id/1oybwJrKogz2mnVJv65-Pl9WfKCCt-ilX/zz. Sbobinature Davide/Clerprem/MR - CP2 - Finitura su Espansi (C2).MOV': 424.76}, 'fps': {'G:/.shortcut-targets-by-id/1oybwJrKogz2mnVJv65-Pl9WfKCCt-ilX/zz. Sbobinature Davide/Clerprem/MR - CP2 - Finitura su Espansi (C2).MOV': 29.99}, 'hasVideo': {'G:/.shortcut-targets-by-id/1oybwJrKogz2mnVJv65-Pl9WfKCCt-ilX/zz. Sbobinature Davide/Clerprem/MR - CP2 - Finitura su Espansi (C2).MOV': True}, 'hasAudio': {'G:/.shortcut-targets-by-id/1oybwJrKogz2mnVJv65-Pl9WfKCCt-ilX/zz. Sbobinature Davide/Clerprem/MR - CP2 - Finitura su Espansi (C2).MOV': True}, 'offset': {}}
16:57:14,995  observation_operations l.1061 DEBUG function: initialize new observation for media file(s)
16:57:15,72  observation_operations l.1161 DEBUG media file: G:/.shortcut-targets-by-id/1oybwJrKogz2mnVJv65-Pl9WfKCCt-ilX/zz. Sbobinature Davide/Clerprem/MR - CP2 - Finitura su Espansi (C2).MOV
16:57:15,73  observation_operations l.1165 DEBUG media_full_path: G:\.shortcut-targets-by-id\1oybwJrKogz2mnVJv65-Pl9WfKCCt-ilX\zz. Sbobinature Davide\Clerprem\MR - CP2 - Finitura su Espansi (C2).MOV
16:57:16,131  core l.1418 DEBUG paused? False
16:57:16,131  menu_options l.31 DEBUG function: menu_options
16:57:16,133  menu_options l.190 DEBUG function: menu_options finished
16:57:16,136  core l.2129 DEBUG function: display statusbar info: Cleprem_FinituraEspansi_POSTURE
QWindowsWindow::setGeometry: Unable to set geometry 1710x743+0+0 (frame: 1710x743+0+0) on QWidgetWindow/"QWidgetClassWindow" on "\\.\DISPLAY2". Resulting geometry: 1710x743+2130+108 (frame: 1710x743+2130+108) margins: 0, 0, 0, 0)
16:57:16,153  core l.1930 DEBUG begin load events from obs: Cleprem_FinituraEspansi_POSTURE
16:57:16,153  core l.1985 DEBUG end load events from obs
16:57:16,153  menu_options l.31 DEBUG function: menu_options
16:57:16,154  menu_options l.190 DEBUG function: menu_options finished
QWindowsWindow::setGeometry: Unable to set geometry 1710x718+0+0 (frame: 1710x718+0+0) on QWidgetWindow/"QWidgetClassWindow" on "\\.\DISPLAY2". Resulting geometry: 1710x718+2130+108 (frame: 1710x718+2130+108) margins: 0, 0, 0, 0)
16:57:20,987  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
QWindowsWindow::setGeometry: Unable to set geometry 1710x695+0+0 (frame: 1710x695+0+0) on QWidgetWindow/"QWidgetClassWindow" on "\\.\DISPLAY2". Resulting geometry: 1710x695+2130+108 (frame: 1710x695+2130+108) margins: 0, 0, 0, 0)
16:57:21,488  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,518  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,552  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,599  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,630  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,662  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,693  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,726  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,757  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,790  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,821  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,853  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,884  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,916  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,948  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:21,995  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,25  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,58  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,89  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,121  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,152  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,187  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,785  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:22,977  core l.4417 DEBUG text ##  event key: 16777236 Modifier: 
16:57:26,182  menu_options l.31 DEBUG function: menu_options
16:57:26,182  menu_options l.190 DEBUG function: menu_options finished
[boris.log](https://github.com/olivierfriard/BORIS/files/9301417/boris.log)

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this issue.
Bugs were fixed in the v. 8.6.8 that was just released.
Can you check if this issue was fixed?

**Comment by PavoPavan** [comment]
Hi,
thanks for the reply. I installed version 8.6.8 and checked: the issue was not fixed in the last release, attached is the log file.

Thank you
[boris.log](https://github.com/olivierfriard/BORIS/files/9451555/boris.log)

**Comment by olivierfriard** [comment]
Thank you for testing.
Can you send me the boris_error.log file just after the crash (before relaunching BORIS)?

**Comment by PavoPavan** [comment]
I found no file named "boris_error.log", but just "boris.log" which I attached there

[boris.log](https://github.com/olivierfriard/BORIS/files/9461501/boris.log)

**Comment by olivierfriard** [comment]
Hi,
the file is now called boris.log sorry for this mistake.
The issue should be fixed in v. 8.7.
Could you test it and let me know?

Thank you for your collaboration

**Comment by PavoPavan** [comment]
Hi,
the issue is solved in v. 8.7
Thanks for your support
