### ISSUE TITLE
Export Ethogram WITH modifiers

### ISSUE THREAD

**Issue by EllisJGL** [olivierfriard/BORIS#528]
When exporting an ethogram and saving as a csv, the modifiers are not included. This would be really useful.

**Comment by olivierfriard** [comment]
Hi,
modifiers are included in the export output since v. 8.7
At the moment they cannot be imported again from XLSX/CSV/TSV output
In v. 8.7.1 (not released yet) you can export the ethogram as a BORIS project file.
