### ISSUE TITLE
"Previous frame" and "Next frame" buttons not working (MacOS M1)

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [olivierfriard/BORIS#531]
**Describe the bug**
The Next and Previous frame buttons are grayed out and not working neither the right and left arrows shortcuts. (The jump `n` frames forward or backward work correctly, and the up and down arrow as well)
![image](https://user-images.githubusercontent.com/18050620/188112460-8b859c67-27c4-405f-a225-56cb6d71379f.png)

I'm working on macOS Monterey 12.3.1 with Apple M1 Pro chip.
In case it might help:
```
BORIS v. 7.13.8 - 2022-07-27
```

```
$ BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/boris/misc/ffmpeg -version                                                                          MBP2022-Gabriel
ffmpeg version 4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
```

Media file information
```
VLC analysis
State: State.Paused
Media Resource Location: file:///Users/gabriel/video.mp4
File name: video.mp4
Track: 0/2
Number of media in media list: 1
get time: 96655
duration: 00:15:37.667
Position: 0.10308046638965607 %
FPS: 15.0
Rate: 1.0
Video size: (2988, 1180)
Scale: 0.0
Aspect ratio: None
is seekable? Yes
has_vout? Yes

FFmpeg analysis
File path: /Users/gabriel/video.mp4
Duration: 00:15:37.670
Number of frames: 14065
Bitrate: 8142k
FPS: 15
Has video: True
Has audio: False

Total duration: 00:15:37.670 (hh:mm:ss.sss)
```

**Comment by olivierfriard** [comment]
Hi, did you switch to the frame-by-frame mode?
see:
https://boris.readthedocs.io/en/v7/#media-based-coding
https://boris.readthedocs.io/en/v7/#frame-by-frame-mode

**Comment by gabriel-vanzandycke** [comment]
Thanks for your reply. Indeed, the frame-by-frame mode was not enabled and I can now use the two buttons. Thanks, and sorry for not reading the manual :)
