### ISSUE TITLE
BORIS crashes when you open Geometric Measurements

### ISSUE THREAD

**Issue by Sarah2022A** [olivierfriard/BORIS#532]
**BORIS v 8.6.8 crashes when you open "Geometric Measurements" window**

**To Reproduce**
1. Go to 'Tools" drop down menu
2. Click on 'Geometric measurement'
3. Window partly opens (outline but no text), BORIS freezes for a second then closes. 

**Expected behavior**
Open geometric measurement window. 

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - BORIS Version 8.6.8

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.7 (see issue #523)
Thank you for your collaboration.

**Comment by PavoPavan** [comment]
The issue is solved in v. 8.7
