### ISSUE TITLE
geometric measurements glitchy

### ISSUE THREAD

**Issue by Sarah2022A** [olivierfriard/BORIS#535]
**Repeated errors using geometric "point" measurements and unable to scroll frame by frame**
(1) I would like to apply a point measurement to an object in multiple frames. When I open the geometric measurements window, the window appears in the middle of the screen, partly obscuring my video. At this stage I am able to scroll frame by frame using the arrow keys. But I have to move the geometric measurements window off the middle of the screen to view the my video. When I use my cursor to move the geometric measurements window, I can no longer scroll through my video frame by frame using the arrow keys. To be able to scroll, I need to click on the video. But when I click on the video to activate arrow key scrolling, doing so creates a point measurement in what is now the wrong frame because I haven't start scrolling yet.

(2) If I uncheck "measurements are persistent", I can create one point measurement initially but after that, every time I try to create one, an error messages occurs (attached) and no data are recorded. I can ignore the message and close the error window, but it reappears each time I create a new point measurement. 

If I leave "measurements are persistent" checked, the error message issue does not occur. But I would prefer not to have my screen full of old point measurement markers. The issue of how to move the geometric measurements window then scroll without creating a unwanted point measurement persists either way. 

As a workaround, I am documenting and manually deleting the false point measurements from my dataset, and living with the cluttered screen full of obsolete point measurement targets. 

**To Reproduce**
1. Open tools menu
2. Select geometric measurements
3. Select "point"
4. Uncheck "measurements are persistent"
5. Use cursor to apply point measurement
6. Success, point measurement created
7. Move "geometric measurements" window so it is not obscuring the video.
8. Attempt to scroll forward one frame using RH arrow key. 
9. Nothing happens
10. Click on the video. 
11. Doing so creates a second unwanted point measurement. 
12. Attempt scroll forward one frame using RH arrow key
13. Success, video moves forward one frame. 
14. Click on the video to create a point measurement.
15. Point measurement "marking" appears on video but no measurement data are recorded in "geometric measurements" window. 
16. Simultaneously, error window also opens. 
17. Ignore error, close window.
18. Click on the video to create a point measurement.
19. Point measurement "marking" appears on video but no measurement data are recorded in "geometric measurements" window.
20. Simultaneously, error window also opens. Etc. 

**Expected behavior**
1. Open tools menu
2. Select geometric measurements
3. Select "point"
4. Uncheck "measurements are persistent"
5. Use cursor to apply point measurement
6. Success, point measurement created
7. Move "geometric measurements" window so it is not obscuring the video.
8. Scroll forward one frame using RH arrow key. 
9. Use cursor to apply point measurement
10. Success, point measurement created

Operating system: windows 10. 
BORIS version 8.8

![Screenshot 2022-09-15 112905](https://user-images.githubusercontent.com/57016893/190281678-021d2bca-8f15-439a-b9c4-39023248dbb7.jpg)

**Comment by olivierfriard** [comment]
Hi,

issues 1) and 2) should be fixed in v. 8.8.1 (see https://github.com/olivierfriard/BORIS/releases/tag/v8.8.1)

May you confirm that?

Thank you for your collaboration

Olivier

**Comment by Sarah2022A** [comment]
Thanks Olivier,

I can confirm that issues 1 and 2 are fixed in v 8.8.1, awesome!
