### ISSUE TITLE
Import subjects from clipboard

### ISSUE THREAD

**Issue by martacomin** [olivierfriard/BORIS#541]
I know that this is an old issue, but I faced the same problem with "Import from clipboard" for subjects. I tried to delete ".boris" file and launched again the software, but it didn't work. My list of subjects include 89 individuals. I used an excel sheet and I tried to fill the key column with number from 1 to 89 and the subject name column with "ag1" to "ag89" with text format and blank cells for the description. I also tried to leave blank cells for the Key (optional).
The warning message is “ The clipboard content does not have a constant number of fields. […]”.

Boris version 7.13.8 on a Window 11 Home (version 22H2) x64 , 8GB RAM and Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz

Thank you very much!

**Comment by olivierfriard** [comment]
The functions for importing subjects and  ethogram were greatly improved in version 8 .
Please try it and let me know if the issue with subjects import is fixed.
See http://www.boris.unito.it/pages/boris_v8.html
