### ISSUE TITLE
"Synthetic time budget with time bin" fails when not observed behaviors are selected 

### ISSUE THREAD

**Issue by florianduclot** [olivierfriard/BORIS#548]
**Describe the bug**
During the "Synthetic time budget with time bins" feature, if ALL behaviors are selected, including behaviors with no events, the process fails with the following error:
```
File "/home/florian/Documents/Tools/boris/boris_venv/lib/python3.8/site-packages/boris/time_budget_functions.py", line 199, in synthetic_time_budget_bin
    behaviors = init_behav_modif_bin(pj[ETHOGRAM], selected_subjects, distinct_behav_modif, include_modifiers,
File "/home/florian/Documents/Tools/boris/boris_venv/lib/python3.8/site-packages/boris/time_budget_functions.py", line 81, in init_behav_modif_bin    
    if behav_modif_str not in behaviors[subj]: TypeError: unhashable type: 'list' 
```

**To Reproduce**
1. Create a project with more than one behavior
2. Score at least one observation with at least one behavior without any event
3. Go to "Analysis > Synthetic time budget with time bin"
4. In the "Select subjects and behaviors" window, select ALL behaviors, including those without any event.
5. Press OK and move along with the process
6. When Clicking OK after choosing a filename for the output, the error described above is observed.

The procedure above has been reproduced on Windows 10 using Boris v7.
Note that if one select ONLY the behaviors with at least one event, the error does not occur.

**Expected behavior**
The output file should be created.

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed 20221013, Windows 10
 - BORIS Version: BORIS v. 8.0.14 - BETA 2022-02-24. BORIS v7

**Possible cause**
It seems that the bit dealing with not observed behaviors should append a tuple (as it is the case for the observed behaviors) instead of a list as it is currently the case:
https://github.com/olivierfriard/BORIS/blob/33dba03d7acb89eb69b0bd2161923311e737b4d0/boris/time_budget_functions.py#L191-L194

Hope this helps,

**Comment by olivierfriard** [comment]
Hi Florian,

thank you for your PR. I updated the 2 BORIS versions to 7.13.9 and 8.9.
I also load the v. 8.9 as the current version on PYPI: https://pypi.org/project/boris-behav-obs/

**Comment by florianduclot** [comment]
Thanks a lot, @olivierfriard !
