### ISSUE TITLE
Bug - Import behaviors from a BORIS project

### ISSUE THREAD

**Issue by jamiahuswalton** [olivierfriard/BORIS#55]
Hello, 

I believe we discovered the problem and found a solution. 

We created a new project and we wanted to import the behavior code from an existing project. We used the "Import behaviors from a BORIS project" feature. This appeared to work. 

The Category Information displays correctly and everything. However, it turns out the categories themselves did not actually import. In other words, I had to add all of the categories ("Behavioral Categories" > "Add category"). Once I did that, everything seemed to work as it should. I believe that this is a bug in the program and I wanted to bring that to your attention. This seems like it should be a simple fix. 

I really enjoy your program and I want to do what I can help! Thanks!

**Comment by olivierfriard** [comment]
fixed in v. 3.47
