### ISSUE TITLE
Feature to number events sequentially

### ISSUE THREAD

**Issue by elizabethirenewarren** [olivierfriard/BORIS#550]
Hello! Thank you so much for this project, it has been incredibly useful and I am so impressed by its flexibility and function.

Is it possible to add a feature that can sequentially number the same type of event automatically? I use this software for experimental data, and it would be particularly useful if I could set a state event (like trial) to automatically be numbered sequentially (i.e., the first time I use that event within a video, it is automatically given the number 1, the second time I use it, the number 2, and so on). Even more helpful would be if it were possible to set it so that every event contained within the numbered state event (any event occurring between the start and end of the trial event) could be given the same number as that state event (i.e. all events occurring during trial 1 are numbered with the trial number).  Right now, I have to either manually add it is a comment to every event, or manually add it in Excel after it is exported. 

I have no idea if this is possible or not, but I thought I would post the request in case it was!

**Comment by olivierfriard** [comment]
Hi,
I am sorry it will be too tricky to implement
