### ISSUE TITLE
Error when using export events > aggregated events

### ISSUE THREAD

**Issue by Pirotte-H** [olivierfriard/BORIS#555]
Hello,

I cannot use "export agregated events" when I do it under a xlsx file. I can neither export one or multiple state events. I have an error message saying "'NoneType' object has no attribute 'replace'". 

I'm using Windows10 professionnal and BORIS v.8.9.4.

Exporting under csv works, so does exporting under version 7.13.9.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting that.
I need the complete error message (you should find the full messgae in the clipboard)

**Comment by Pirotte-H** [comment]
I don't know how to do that, sorry.

**Comment by olivierfriard** [comment]
hi,
just send me a screenshot of the error message.

**Comment by Pirotte-H** [comment]
Hello, I always have this same text box that pops up when i want to export the agregated events.

![image](https://user-images.githubusercontent.com/119300661/205329584-9c78076c-78c2-44c1-b8b6-ca7833b48bf1.png)

**Comment by olivierfriard** [comment]
Hi,
can you send me your project file?
Please by email see the About page on the BORIS web site
