### ISSUE TITLE
BORIS 7.13.9 will open but I am not able to interact with the site (for macOS Monterey 12.6.2)

### ISSUE THREAD

**Issue by Jennaguarneri** [olivierfriard/BORIS#556]
**Describe the bug**
BORIS 7.13.9 will open but I am not able to interact with the site (for macOS Monterey 12.6.2)

**To Reproduce**

**Expected behavior**
I expected to be able to click on icons on the toolbar at the top of the site and interact with the site

**Screenshots**
<img width="1201" alt="Screen Shot 2022-12-21 at 4 04 47 PM" src="https://user-images.githubusercontent.com/121200923/209011028-5241856e-9569-4a0d-9d67-2df624f7cd85.png">

**Desktop (please complete the following information):**
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - BORIS Version

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

**Comment by olivierfriard** [comment]
Hi,
I need more info.
Did you create a project?
