### ISSUE TITLE
Boris 7.13.9-macos opens on mini Ipad but just shows black screen 

### ISSUE THREAD

**Issue by kyl10** [olivierfriard/BORIS#559]
Hi Olivier, 

Should it be possible to run Boris on a mini Ipad 6th generation (64 GB, software version 15.6.1)? I've downloaded Boris 7.13.9-macos and I can open it, but then it just shows a black screen. 
I'd really appreciate it if you could help me with this. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - BORIS Version

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).
![Uploading DSC_2435.JPG…]()

**Comment by olivierfriard** [comment]
Hi,

BORIS (v. 7) should run on MacOS but not on iPadOS
Regards
