### ISSUE TITLE
Extract frames from media files - not all frames are extracted

### ISSUE THREAD

**Issue by Clarasauphar** [olivierfriard/BORIS#560]
Hi :) 

I want to extract all frames on which I registered an event, the function extract frames is working but it does not extract all the frames I was expecting. I recoded 951 events on 951 frames (spread on 16 videos in the same "observation file") but I only get 497 pictures out of it. I have selected all categories.

Any idea of what I could have done wrong? or are we limited in the number of frames we can extract?

**Screenshots**
![image](https://user-images.githubusercontent.com/122974304/213140407-c82406ff-bc12-4d26-97b1-62edf616db99.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - BORIS Version: 7.13.9-2022-10-25

Thank you in advance for your help !

**Comment by olivierfriard** [comment]
Hi,

can you reproduce this issue with v. 8 of BORIS?
See http://www.boris.unito.it/pages/boris_v8.html

v.7 will be deprecated very soon!

Regards

**Comment by Clarasauphar** [comment]
I did the same procedure on the newest version now and 496 images extracted :/ i also tried on a file with less events recorded (only 300) and only 173 frames were extracted.

**Comment by Clarasauphar** [comment]
In case that helps the steps I take to extract the images of the first observation file:
![image](https://user-images.githubusercontent.com/122974304/213150498-940d3905-5a7d-479b-80f1-e91ee1419acc.png)
![image](https://user-images.githubusercontent.com/122974304/213150652-13a4259f-f00d-4dac-8978-1f366b17fb94.png)
![image](https://user-images.githubusercontent.com/122974304/213150699-de360e25-2a32-4b56-ab1d-4e93db668069.png)

And selection of the output file

**Comment by olivierfriard** [comment]
Can you send me your BORIS project file and your video by email or wetransfert / equivalent?

Thank you for your collaboration

**Comment by Clarasauphar** [comment]
It is sadly 96GB of video for only one observation, and we can multiply by 4 if you would need all the videos for the 4 observations. I am not sure how I could transfer that :/ Maybe I should try using only one video per observations to see if I get the number of frames (60) I need ?

**Comment by olivierfriard** [comment]
Yes,
you should try to send me a minimal set of files in order to reproduce the issue.

**Comment by Clarasauphar** [comment]
Okay so it worked well for the observation with one video file and 60 frames to extract. I guess it might struggle with the 16 video files.

**Comment by Clarasauphar** [comment]
The issue starts once I have 2 video files in the same observation file. Registering 60 events on 60 frames on the first video, same on the second video, but getting 116 frames extracted instead of 120.

**Comment by olivierfriard** [comment]
Thanks for the information.
I will try to reproduce this case

**Comment by olivierfriard** [comment]
I am able to reproduce the issue.
I will fix it as soon as possible

Thank you for your collaboration

**Comment by olivierfriard** [comment]
This issue should be fixed in the v. 8.9.12 just released:
See https://github.com/olivierfriard/BORIS/releases/tag/v8.9.12

Can you please confirm this?

**Comment by Clarasauphar** [comment]
It works !!! Thank you so so much, making my PhD life so much easier now !

Thank you for such a great software and making collaboration that easy.

**Comment by olivierfriard** [comment]
Thank you for your collaboration!
