### ISSUE TITLE
Import events and export frame index

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [olivierfriard/BORIS#562]
I'm using BORIS 8.9.14 with observations from a video (mp4) file.
Is it possible to import (previously exported) events ? I'm not sure I find that option, and so far I had to re-annotate the whole video whenever I leave the application.

Is it possible to have a frame index saved in the CSV?

**Comment by olivierfriard** [comment]
It is not yet possible to re-import exported events.
A solution could be to copy the events from a worksheet (or text file) and paste them into a BORIS observation.

I am working to have the frame index recorded into the events table (and so also exported)
