### ISSUE TITLE
Problem with rotating video

### ISSUE THREAD

**Issue by clearwingMSV** [olivierfriard/BORIS#565]
**Describe the bug**
When I try to use the tool "rotate video", a broken avi file is generated, it's only about 4-5kb and cannot be opened. I was trying to rotate an mp4 file. I tried closing BORIS, deleting the configuration file and re-opening it, but that didn't resolve the problem.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Rotate video'

**Expected behavior**
Generation of rotated video file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - BORIS Version 7.13.9

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

**Comment by olivierfriard** [comment]
Hi,

can you reproduce this issue with v.8 ?

**Comment by clearwingMSV** [comment]
Hello,

same issue with v.8.9.14

I get a file e.g. "C0005.MP4.rotated180" but it's broken.

**Comment by olivierfriard** [comment]
hi,

can you send me more info about your video?
see Tools > Media info

Can you send a sample of your video in order to reproduce the issue?

**Comment by clearwingMSV** [comment]
OK, below info on the analysed video:


MPV information
Video format: h264
Number of media in media list: 1
Current time position: 0.0
duration: 109.44
FPS: 25.0
Video size: 3840x2160
Aspect ratio: 1.778

ffmpeg analysis


Duration: 109.44 seconds (00:01:49.440)
Resolution: 3840x2160
Number of frames: 2736
Bitrate: 98421 k
FPS: 25
Has video: True
Has audio: True
File size: NA
Video codec: NA
Audio codec: NA
Total duration: 109.44 (00:01:49.440)


It's a big file, can I send you a several-second piece here via email?

**Comment by olivierfriard** [comment]
Maybe better with wetransfer or equivalent

**Comment by olivierfriard** [comment]
check the about page of the BORIS web site
www.boris.unito.it

**Comment by clearwingMSV** [comment]
Hello,
my apologies, I did not check the video I sent you after trimming it to provide a sample (the entire video is too big to send). I have also rotated the trimmed version that I sent you without issues. Is it possible that there is a size limit for the videos that are to be rotated? Below is the detailed info from BORIS:

Operating system: Windows 10 10.0.22000 
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 10, GenuineIntel

Python 3.10.7 (64-bit) - Qt 5.15.2 - PyQt 5.15.7

Memory (RAM)  Total: 16192.05 Mb  Free: 7710.12 Mb

MPV media player
Library version: 1.109 file: C:\Users\MSV\BORIS\lib\site-packages\boris\misc\mpv-1.dll

FFmpeg
ffmpeg version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
Path: C:\Users\MSV\BORIS\Lib\site-packages\boris\misc\ffmpeg.exe
https://www.ffmpeg.org

Matplotlib
version 3.6.3
https://matplotlib.org

GraphViz
not installed
https://www.graphviz.org/

**Comment by olivierfriard** [comment]
Can you try the v. 8.9.19 just released and let me know if it works?
see https://github.com/olivierfriard/BORIS/releases/tag/v8.9.19

If your issue is not fixed please send me the error message.

**Comment by clearwingMSV** [comment]
Dear Olivier,
I tried with the new version, unfortunately it's still not working. Here is the error messagge:

C0010.MP4:   [mov,mp4,m4a,3gp,3g2,mj2 @ 0000018b7970d500] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000018b7970d500] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
C0010.MP4:   Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:/Users/MSV/Desktop/C0010.MP4':
  Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2022-12-15T09:19:59.000000Z
  Duration: 00:00:35.04, start: 0.000000, bitrate: 96720 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 94223 kb/s, 25 fps, 25 tbr, 25k tbn (default)
    Metadata:
      creation_time   : 2022-12-15T09:19:59.000000Z
      handler_name    : Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2022-12-15T09:19:59.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (rtmd / 0x646D7472), 204 kb/s (default)
    Metadata:
      creation_time   : 2022-12-15T09:19:59.000000Z
      handler_name    : Timed Metadata Media Handler
      timecode        : 01:46:12:09
C0010.MP4:   Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
C0010.MP4:   Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted
Error initializing output stream 0:0 -- 
C0010.MP4:   Conversion failed!

**Comment by olivierfriard** [comment]
Hi,
I do not understand the error you obtained.
Try to re-encode/resize your video before rotating it
See Tools > Media file > Re-encode/resize video

**Comment by clearwingMSV** [comment]
Hello, it works if I re-encode/resize the video first - thank you for your time and advice.
