### ISSUE TITLE
Issues with displaying spectrogram/waveform for .wav files

### ISSUE THREAD

**Issue by SeleneCN** [olivierfriard/BORIS#566]
Hi Oliver! 
I'm a big fan of BORIS and have been using it for various projects. I was excited about version 8 with the improved video, so I updated and am very happy with how much smoother the coding works. For one project however, I have seperated audio and video files that I synchronize and play at the same time in every observation. For the audio, I need a spectrogram, so I select it as player 1 and choose the 'Visualize spectrogram' option. In the previous version 7 this worked perfectly fine, but for some reason I can't get it to work in version 8. I hope that you are able to help with this.

**Describe the bug**
BORIS v. 8.9.14 does not create waveforms or spectrograms for .wav files selected for player 1 in an observation. If trying to create a spectrogram, the error message 'The media file _media file.wav_ does not have an audio track' is shown. However, when clicking 'ok' and starting the observation, the audio from the .wav file is played normally.

**To Reproduce**
1. Go to 'Observation'
2. Click on 'New Observation'
3. Create new observation, select .wav file for player 1 and .mp4 file without audio for player 2
4. Select 'Visualize sound spectrogram for the player 1'
5. Start observation

**Expected behavior**
In v. 7, a spectrogram was shown for the .wav file in player 1 in an external window. I expected v8 to do the same: showing a sound spectrogram while having a blank window for the video

**Desktop:**
 - OS: Windows 10
 - BORIS Version v. 8.9.14

Cheers!
Selene

**Comment by olivierfriard** [comment]
Thank you for reporting this issue.
I will fix it as soon as possible

Olivier

**Comment by olivierfriard** [comment]
This issue should be fixed in v. 8.9.17.
See http://www.boris.unito.it/pages/download.html

Can you confirm this?

Thank you for your collaboration

**Comment by SeleneCN** [comment]
Yes, can confirm, works as it used to now.
Thank you so much for your fast help Olivier!
