### ISSUE TITLE
Support uncompressed .tiff files

### ISSUE THREAD

**Issue by compiaffe** [olivierfriard/BORIS#569]
**Describe the function you'd like to be added to BORIS**

I would like BORIS to support `.tiff` files for Observations from pictures. It is (yet) another image format.
For us it has the benefit, that it can be written significantly faster that png. At least when exporting data from a video file using GSstreamer. (I do know that BORIS can also load videos directly)

Pillow supports `uncompressed` .tiff files out of the box and if the system has libtiff installed even various forms of compressed .tiff files. So I assume implementation should be rather straight forward. I'm happy to do a MR, but would love to have some pointers at where in the code base I should start.

**Comment by olivierfriard** [comment]
Hi,

the v. 8.10 should support TIFF (*.tiff, *.tif) and WEPB (*.webp) images.
Please test it and let me know.
See https://github.com/olivierfriard/BORIS/releases/tag/v8.10

**Comment by compiaffe** [comment]
Amazing! I can confirm this works.
Thanks for the quick implementation.
