### ISSUE TITLE
Extract sequences from media files not completing

### ISSUE THREAD

**Issue by jplaney** [olivierfriard/BORIS#575]
**Describe the bug**
I have used this feature in previous versions successfully (I believe  8.9.11 was the last time I utilized it). In the newest version (8.9.19) when I run the "extract sequences from media files" I get a completion message, but no files are extracted.

**To Reproduce**
1. Open Boris project
2. Go to "observations" menu
3. Select "extract sequences from media files"
4. Select observations
5. Select behaviors
6. Set time interval (5 seconds)
7. Select tracks for export (Video and audio)
8. Choose output directory
9. Boris status message says "Media sequences extracted to: (directory) but no files are present

**Expected behavior**
I am expecting the clips to be exported to my designated directory. I have successfully extracted sequences from this project file and observations before.

**Desktop (please complete the following information):**
 - OS: Windows 10, build 19045
 - BORIS Version 8.9.19

**Comment by jplaney** [comment]
I uninstalled version 8.9.19 and then tried each version back until I was able to extract sequences again. Version 8.9.6 allows me to extract sequences again.

**Comment by olivierfriard** [comment]
Hi,
I cannot reproduce this issue on my system.
Could you send me  (by email, check the web site) a minimal project file in order to reproduce the problem?

**Comment by olivierfriard** [comment]
The issue should be fixed in v. 8.21.8.
Please try and let me know
