### ISSUE TITLE
Importing data with video bug

### ISSUE THREAD

**Issue by koreypickering** [olivierfriard/BORIS#577]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - BORIS Version

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

Hi, 
When trying to import and plot with a media file, BORIS continues to throw "impossible to plot: an integer is required" The line causing the issue is in the utilities.py in the text2np function, in one of the last trys. In the np.load text call, skiprows=has_header. Has_header is a boolean, and there seems to be an type check in numpy that is seeing it as not an integer. If it is instead changed to skiprows=1, it works perfectly. I belive there should be a check on has_header, if then skiprows=1 else 0.

Thanks

**Comment by olivierfriard** [comment]
Hi,

can you send me a sample of your external data file?
Thank you for your collaboration

**Comment by koreypickering** [comment]
Sure. 

This is what the data file looks like. It is simply a comma separated text file. 
[02-09-2023-Fluffy.txt](https://github.com/olivierfriard/BORIS/files/10770524/02-09-2023-Fluffy.txt)

This is a picture of how the software reacts when trying to plot it. 
![borisprob](https://user-images.githubusercontent.com/58117034/219763717-7fdf00d1-d94e-4258-8c5b-71f15949a9d3.png)

This is a picture of me reproducing the error with boris' txt2np function located in utilities:
![before result](https://user-images.githubusercontent.com/58117034/219764409-c9e77e27-6cbb-4414-86e1-acfea04714ec.png)

This is a picture of the code showing has_header being assigned a boolean value and being sent to the np loadtext function in the skiprows argument:
![before](https://user-images.githubusercontent.com/58117034/219764888-7fcc4b6a-8114-4f84-9102-7815eb938872.png)

This is a picture of the numpy documentation stating skiprows is an integer:
![documentation](https://user-images.githubusercontent.com/58117034/219765751-0dbb3edb-2d0c-41f0-a388-81aaa5555526.png)

This is a picture of skiprows argument being changed to 1 instead of a boolean value:
![after](https://user-images.githubusercontent.com/58117034/219765887-2ddee167-3cac-45a7-8389-90bb34557e05.png)

This is a picture of it working:
![result](https://user-images.githubusercontent.com/58117034/219765969-963d979f-8b4b-46d4-a2eb-e8305c6b9ee9.png)

Hope this helps.

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.11 just released.
See https://github.com/olivierfriard/BORIS/releases/tag/v8.11

Could you confirm this?
Thank you for your collaboration

**Comment by koreypickering** [comment]
Awesome, it works perfectly. Thanks!
