### ISSUE TITLE
Can't add media file to an observation on version 8.10

### ISSUE THREAD

**Issue by tbortolini** [olivierfriard/BORIS#578]
Hi, first of all, I would like to congratulate and thank you for the great software you have developed!

**Describe the bug**
I have just updated from version 8.9.9 to version 8.10, and there is an error when I try to add the media file to a new observation. The same files work perfectly with version 8.9.9.

**To Reproduce**
1. Go to 'New observation'
2. Click on 'Observation from media file(s)'
3. Click on 'Add media' and 'with absolute path'
4. No files show up for selection (even when changing the options in step 3)

**Expected behavior**
Files should show up to be selected

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.19044
 - BORIS version 8.10 release date: 2023-02-10

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

13:37:20,764  core l.153 INFO BORIS started
13:37:20,764  core l.154 INFO BORIS version 8.10 release date: 2023-02-10
13:37:20,826  core l.155 INFO Operating system: Windows 10 10.0.19044
13:37:20,826  core l.156 INFO CPU: AMD64 Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
13:37:20,826  core l.157 INFO Python 3.11.1 (64-bit)
13:37:20,826  core l.158 INFO Qt 5.15.2 - PyQt 5.15.9
13:37:21,311  core l.162 INFO Memory (RAM)  Total: 16282.33 Mb  Free: 6644.12 Mb
13:37:22,452  utilities l.935 DEBUG test ffmpeg path output: b'ffmpeg version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers\r\nbuilt with gcc 12.1.0 (Rev2, Built by MSYS2 project)\r\nconfiguration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband\r\nlibavutil      57. 28.100 / 57. 28.100\r\nlibavcodec     59. 37.100 / 59. 37.100\r\nlibavformat    59. 27.100 / 59. 27.100\r\nlibavdevice    59.  7.100 / 59.  7.100\r\nlibavfilter     8. 44.100 /  8. 44.100\r\nlibswscale      6.  7.100 /  6.  7.100\r\nlibswresample   4.  7.100 /  4.  7.100\r\nlibpostproc    56.  6.100 / 56.  6.100\r\n'
13:37:22,452  utilities l.936 DEBUG test ffmpeg path error: b''
13:37:23,218  menu_options l.52 DEBUG function: menu_options
13:37:23,218  menu_options l.202 DEBUG function: menu_options finished
13:37:23,218  config_file l.45 DEBUG read config file: C:\Users\tbort\.boris
13:37:23,218  config_file l.68 DEBUG restore geometry
13:37:23,421  config_file l.79 DEBUG saved state: b'\x00\x00\x00\xff\x00\x00\x00\x00\xfd\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x01\x16\x00\x00\x03\x8c\xfc\x02\x00\x00\x00\x02\xfb\x00\x00\x00\x14\x00d\x00w\x00E\x00t\x00h\x00o\x00g\x00r\x00a\x00m\x01\x00\x00\x00B\x00\x00\x02\xa8\x00\x00\x00\x87\x00\xff\xff\xff\xfb\x00\x00\x00\x14\x00d\x00w\x00S\x00u\x00b\x00j\x00e\x00c\x00t\x00s\x01\x00\x00\x02\xef\x00\x00\x00\xdf\x00\x00\x00\x87\x00\xff\xff\xff\x00\x00\x00\x01\x00\x00\x01w\x00\x00\x03\x8c\xfc\x02\x00\x00\x00\x01\xfb\x00\x00\x00\x10\x00d\x00w\x00E\x00v\x00e\x00n\x00t\x00s\x01\x00\x00\x00B\x00\x00\x03\x8c\x00\x00\x00\x87\x00\xff\xff\xff\x00\x00\x00\x02\x00\x00\x07\x80\x00\x00\x00\x84\xfc\x01\x00\x00\x00\x01\xfb\x00\x00\x00\x0e\x00p\x00l\x00a\x00y\x00e\x00r\x001\x03\x00\x00\x00\xe7\x00\x00\x00?\x00\x00\x05\xa4\x00\x00\x03\xbd\x00\x00\x04\xe9\x00\x00\x03\x8c\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x08\xfc\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x0e\x00t\x00o\x00o\x00l\x00B\x00a\x00r\x01\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00'
13:37:23,421  config_file l.87 DEBUG time format: hh:mm:ss
13:37:23,421  config_file l.95 DEBUG Time/fast_forward_speed: 10
13:37:23,421  config_file l.103 DEBUG Time/Repositioning_time_offset: 0
13:37:23,421  config_file l.111 DEBUG Time/play_rate_step: 0.1
13:37:23,421  config_file l.125 DEBUG Autosave: 0
13:37:23,421  config_file l.135 DEBUG behavioural_strings_separator: |
13:37:23,421  config_file l.143 DEBUG close_the_same_current_event: False
13:37:23,421  config_file l.151 DEBUG confirm_sound: False
13:37:23,421  config_file l.158 DEBUG alert_nosubject: False
13:37:23,421  config_file l.164 DEBUG beep_every: 0
13:37:23,421  config_file l.171 DEBUG tracking_cursor_above_event: False
13:37:23,421  config_file l.193 DEBUG check_for_new_version: True
13:37:23,421  config_file l.202 DEBUG pause_before_addevent: False
13:37:23,421  config_file l.210 DEBUG last_check_for_new_version: 1676895282
13:37:23,421  config_file l.219 DEBUG ffmpeg_cache_dir: 
13:37:23,421  config_file l.228 DEBUG frame_bitmap_format: JPG
13:37:23,421  config_file l.309 INFO read recent projects
13:37:23,421  core l.5139 DEBUG args: []
13:37:31,703  project_functions l.1206 DEBUG open project: D:\ProjectPath.boris
13:37:31,703  core l.2466 DEBUG initialize new project...
13:37:31,719  menu_options l.52 DEBUG function: menu_options
13:37:31,719  menu_options l.202 DEBUG function: menu_options finished
13:38:11,495  dialog l.146 CRITICAL BORIS version: 8.10
OS: Windows 10 10.0.19044
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
Python 3.11.1 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-02-20 13:38

Traceback (most recent call last):
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\observation.py", line 139, in <lambda>
    menu.triggered.connect(lambda x: self.add_media(mode=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\observation.py", line 1002, in add_media
    (error, msg) = self.check_media(file_path, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\observation.py", line 924, in check_media
    media_info = util.accurate_media_analysis(self.ffmpeg_bin, file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\utilities.py", line 1130, in accurate_media_analysis
    ffprobe_results = ffprobe_media_analysis(ffmpeg_bin, file_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\utilities.py", line 1039, in ffprobe_media_analysis
    return {"error": error.decode("utf-8")}
                     ^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 70: invalid continuation byte

Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\core.py", line 372, in excepthook
    dialog.global_error_message(exception_type, exception_value, traceback_object)
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\dialog.py", line 149, in global_error_message
    with open(pl.Path("~").expanduser() / "boris.log", "a") as f_out:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\tbort\\boris.log'

Original exception was:
Traceback (most recent call last):
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\observation.py", line 139, in <lambda>
    menu.triggered.connect(lambda x: self.add_media(mode=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\observation.py", line 1002, in add_media
    (error, msg) = self.check_media(file_path, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\observation.py", line 924, in check_media
    media_info = util.accurate_media_analysis(self.ffmpeg_bin, file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\utilities.py", line 1130, in accurate_media_analysis
    ffprobe_results = ffprobe_media_analysis(ffmpeg_bin, file_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\boris-8.10\Lib\site-packages\boris\utilities.py", line 1039, in ffprobe_media_analysis
    return {"error": error.decode("utf-8")}
                     ^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 70: invalid continuation byte
13:38:26,536  core l.4869 DEBUG function: closeEvent
13:38:26,536  config_file l.331 DEBUG save config file: C:\Users\tbort\.boris
13:38:26,536  config_file l.373 DEBUG save recent projects
13:38:27,130  core l.1864 DEBUG function: close_tool_windows
13:38:27,130  core l.1971 DEBUG function: close_tool_windows finished
D:\Downloads\boris-8.10\Lib\site-packages\boris\misc\mpv-1.dll

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.11 just released.
See https://github.com/olivierfriard/BORIS/releases/tag/v8.11

Could you confirm this?
Thank you for your collaboration

**Comment by tbortolini** [comment]
Hi! I have just finished coding a video on version 8.9.9 and saw your reply :)

I have tested v. 8.11 and this bug seems to be fixed! I haven't tested all functions, but I'll do it in the next days and let you know if something else appears :)

Thanks again for the great work
