### ISSUE TITLE
How to retrieve last observations 

### ISSUE THREAD

**Issue by wissamfloriane** [olivierfriard/BORIS#584]
I was working on my project, saved my project and few time after Boris crashed. I was forced to quit Boris. When i re-opened the app, my last observations from the day were gone. Is it possible to retrieve these observations ? 

I am working on the last version available on MacOS.

**Comment by olivierfriard** [comment]
Hi,
I need more details.
What version of BORIS are you using? What OS? etc...
If BORIS crashed please send the boris.log file (see http://www.boris.unito.it/pages/report_a_bug.html)
Thank you for your collaboration
