### ISSUE TITLE
Can't change the transparency of overlay

### ISSUE THREAD

**Issue by LytanaLecuyer** [olivierfriard/BORIS#588]
BORIS version : v. 8.11.2 2023-02-28

When I try to load a png image as an overlay on a video, I can't set the transparency. It's automatically set to 0 (meaning it's invisible).

**To Reproduce**
1. Create an observation with a media file with absolute path
2. Click on Start
3. Go to Playback --> Image overlay on video --> Add
4. From there, the transparency option is not accessible, even when browsing a png image and setting the image's position. It's also automatically set to 0, meaning it's fully transparent and invisible.

![image](https://user-images.githubusercontent.com/126804554/222492383-19613517-2e1f-4994-a211-b0ff8d387e50.png)

 - OS: [windows 10]
 - Type of BORIS installation : setup from the file [boris-8.11.2-win64-setup.exe]

**Comment by olivierfriard** [comment]
Hi,
the image overlay function was improved in v. 8.11.4.
Now you can set transparency. If your image does not have a transparency layer I suggest setting transparency to 95-98. Otherwise, you can leave it to 0

Please let me know

**Comment by LytanaLecuyer** [comment]
Hi! It's now working, thanks a lot!
