### ISSUE TITLE
BORIS crashes when trying to add a modifier

### ISSUE THREAD

**Issue by SeleneCN** [olivierfriard/BORIS#593]
**Version of BORIS**
BORIS V8.12.2 setup

**Describe the bug**
When trying to create modifiers for a new behavior, an error message occurs.

**To Reproduce**
1. Create new project
2. Add new behavior to ethogram
3. Doubleclick on 'Modifiers'
4. Try to type something into 'Description'
5. See error

[boris_error.log](https://github.com/olivierfriard/BORIS/files/10987615/boris_error.log)
[boris.log](https://github.com/olivierfriard/BORIS/files/10987616/boris.log)

**Comment by olivierfriard** [comment]
Hi,

this issue should be fixed in v. 8.13 which was just released.
Can you confirm that?

Thank you for your collaboration

**Comment by SeleneCN** [comment]
Thank you a lot Oliver! I can confirm.
