### ISSUE TITLE
Issue with interlacing

### ISSUE THREAD

**Issue by RIersel** [olivierfriard/BORIS#596]
Using BORIS v. 8.14 - 2023-03-20

**Bug issue**
When watching videos any rapid movement causes interlacing. The issue seems to be tied to the new MPV player (last year I used BORIS based on VLC). Videos are .MTS format, and playback works fine using VLC, but not with MPV. Videos played outside of BORIS using MPV are also interlaced, however, within MPV this is resolved by pressing the "d" button on the keyboard (Shortcut to enable de-interlacing, which is immediate). 

Side note: Using BORIS last year was a huge boost to productivity, thank you for developing this tool.

Here is the BORIS - Media file information report:
MPV information
Video format: h264
Number of media in media list: 1
Current time position: 6.12
duration: 2889.62
FPS: 25.0
Video size: 1440x1080
Aspect ratio: 1.333

ffprobe analysis
File path: C:\Users\xxxx\OneDrive - xxxx\xxx\xxx\xxx\xxx\xxx\K1C_15_05_22\00105.MTS **anonymised file path**

Duration: 2888.896 seconds (2888.896)
Resolution: 1440x1080
Number of frames: 260058600
Bitrate: 5.4 Mb 
FPS: 50.0
Has video: True
Has audio: True
File size: 2.1 Gb
Video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Audio codec: ATSC A/52A (AC-3)

Total duration: 2888.896 (2888.896)

**To Reproduce**
Hard to say how to reproduce the error. I simply:
1. Create a new project (adjust none of the settings)
2. Add a new observation, with video based on absolute file path
3. Play video

**Expected behavior**
Either automatic de-interlacing, or the ability to toggle de-interlacing (as is the case in MPV) would be much appreciated. I am not sure why this is an issue using my videos, as I see no other remarks about it. I have used multiple computers, using different videos (but all recorded/saved in the same way) all resulting in the same results. Hence the video type may be the culprit?

**Screenshot**
![example](https://user-images.githubusercontent.com/128491102/226625257-c6b12722-7f2c-46b6-8f53-97427fb195e3.png)

**Desktop**
 - OS: windows 10
 - Type of BORIS: Setup

**Comment by olivierfriard** [comment]
Hi,
I will add an option for deinterlacing as soon as possible
Thank you for your collaboration

**Comment by olivierfriard** [comment]
Hi,
an option for deinterlacing video was added in v. 8.15
See the playback menu

Please try and let me know

**Comment by RIersel** [comment]
Thank you very much for the speedy reply and fix. I did not have my files at hand so couldn't test earlier, it works perfectly and instantly!
