### ISSUE TITLE
Issues related to data export

### ISSUE THREAD

**Issue by Avianalh** [olivierfriard/BORIS#597]
Dear Professor, I would like to ask a question about the extraction of data after Boris collected it. My collection method is "individual 1" when performing certain behaviors, and there is a temporal overlap in the behavior of "individual 2". What about the percentage of "individual 2" in the behavior of "individual 1" in time when I export the sample data?

**Comment by behaviorengineer** [comment]
Thank you very much for your help!!

**Comment by behaviorengineer** [comment]
hello
I tried using the feature you recommended, However, there is a question about the role of the two logical operators "OR" and "AND". Does "OR" mean that the selected behavior of subject 1 occurs simultaneously with the selected behavior of subject 2? Or is it the time remaining after the selected behavior of subject 2 is removed from the selected behavior of subject 1 within the selected behavior occurrence time of subject 1? If I want to set "subject 1 I eat" (subject 2 I eat, subject 3 I eat, subject 4 I eat) The behaviors of these three subjects each take up the time of subject 1I eat. How should logical operators be used.

**Comment by olivierfriard** [comment]
Hello,
OR means a subject-behavior combination or another one in the same time interval (or the 2 combinations together)
AND means a subject-behavior and another one in the same time interval

My advice is to make a toy observation with all your cases and play with this tool to understand if it can be usefull
