### ISSUE TITLE
Double click zoom tool

### ISSUE THREAD

**Issue by rafaelathaler** [olivierfriard/BORIS#601]
Hello!
Is there a possibility to download version 7.12.2?
I would like this version, because in the most current version I can't zoom in on specific locations, the zoom is always in the center of the video. Thanks!

**Comment by olivierfriard** [comment]
Hello,
all previous versions of BORIS are available.
Check the **Previous versions** section of the Download page of the BORIS website

I am working to improve the zoom tool of the version 8

**Comment by olivierfriard** [comment]
Hi,
I  improved the zoom function in v. 8.17 (https://github.com/olivierfriard/BORIS/releases/tag/v8.17).

Now you can:
zoom in with `CTRL` + `+`
zoom out with `CTRL` + `-`
set no zoom with `CTRL` + `0` or by clicking the mouse right button on the video

and move (pan) the picture in the video using:
`CTRL` + `LEFT ARROW`, `CTRL` + `RIGHT ARROW`, `CTRL` + `UP ARROW` and `CTRL` + `DOWN ARROW`, 

If you have n observation with many media you will have to select the video by a left-click before.
