### ISSUE TITLE
BORIS won't launch! **URGENT**

### ISSUE THREAD

**Issue by miserable-occupant** [olivierfriard/BORIS#605]
VERSION: BORIS for Windows 64-bit Setup v.8.16.3

DESCRIPTION OF BUG:
The app won't launch. It opens the Windows Command Prompt for about a minute and then it closes and nothing happens.
I tried to look over past issues here but I didn't find the answer to this problem. 
Sometimes, before the Windows Command Prompt opens there is a pop-up that says that the program runs in compatibility mode. I tried to turn of the compatibility mode but there is no tab to do that (in properties).  

Can you please help? It's kind of urgent. Thank you!

INFORMATION ON DEVICE:
Windows 10, Intel(R) Celeron(R) CPU  N2820  @ 2.13GHz   2.13 GHz
RAM 4,00 GB (3,89 GB usable)
64-bit operating system, x64-based processor
Type of BORIS installation: setup

**Comment by olivierfriard** [comment]
Hi,
I need the boris.log file.
See the web site on how to report a bug.
