### ISSUE TITLE
Need help recovering my observations!!

### ISSUE THREAD

**Issue by izzi10** [olivierfriard/BORIS#606]
I am working on a Lenovo laptop, using windows 10 and BORIS for Windows Setup v.8.16.3. 

I was working on my data, had just finished an observation, clicked close observation, and went to go back to my observation list when BORIS crashed. Below is the screenshot of what popped up when I opened BORIS again. Although I pressed save on my file earlier, I only have data from many days ago. I'd appreciate any help in recovering anything because almost all of my data has disappeared.
 
<img width="859" alt="image" src="https://user-images.githubusercontent.com/99898651/231125166-b1eeadbf-d31b-4a9d-acb7-fbe18e6e6b8a.png">

**Comment by olivierfriard** [comment]
Hi,
I need the boris.log file to understand the cause of the crash.
Is your project file corrupted or observations are missing?

Remember to do backups frequently!
