### ISSUE TITLE
IRR Coefficent Calculation (e.g., Cohen's Kappa)

### ISSUE THREAD

**Issue by jamiahuswalton** [olivierfriard/BORIS#61]
Hello, 

I recommend adding the ability for one to calculate an IRR coefficient.  I was able to do this based on the data BORIS produces (export events). I was able to put the data into R (open-source) and then calculate Cohen's Kappa.

If this is something that you seriously want to consider, please let me know and I will be happy to explain, with more details, how I calculated the IRR. 

Thanks!

**Comment by olivierfriard** [comment]
IRR coefficient was added in v. 4.1.1
