### ISSUE TITLE
Boris crashes when starting observation

### ISSUE THREAD

**Issue by aschakowski** [olivierfriard/BORIS#613]
Since updating to the newest version (v. 8.17.1) Boris crashes whenever I start a new observation. Viewing/Editing an older observation works fine.

I am using Boris setup on Windows 10, logfile attached. 

[borislog.txt](https://github.com/olivierfriard/BORIS/files/11330168/borislog.txt)

**Comment by olivierfriard** [comment]
Hello,

can you please give me more details?
Please send me the boris.log file just after the crash (before restarting BORIS)

**Comment by aschakowski** [comment]
Thanks for the quick reply! 
This is what the boris.log file looks after crashing/before restarting.

**Comment by olivierfriard** [comment]
The boris.log file does not contain any crash information.
Can you give me a detailed procedure to reproduce the crash?
If it is possible send me your project file via email (see the about page of BORIS web site).

**Comment by aschakowski** [comment]
This crash happens whenever I load an .mp4 file (did not try different video formats) into a project (even if this project is created in the new updated Boris version, so it probably is not a problem of the project file) and click on "start observation". Normally at this point the player should show the video, but the GUI just closes itself. I just tried it on a different computer, and there everything works fine.

**Comment by olivierfriard** [comment]
Try to set the MPV player hardware video decoding to **no** 
See Project > Preferences > Project > MPV player hardware video decoding

Can you play your video with MPV (https://mpv.io)?

**Comment by olivierfriard** [comment]
I will add this in the user guide and on the FAQ session of the web site
