### ISSUE TITLE
Same video file keeps getting corrupted

### ISSUE THREAD

**Issue by Lianvv** [olivierfriard/BORIS#615]
We are coding video's and every time for the same video the file keeps getting corrupted after which the file size is 0kb, so data is lost. During coding there are no crashes and it just happens when we want to continue the next day. 

Can the source of the problem be in the recording that we made? Other video's from the same recording devices are not giving problems. Or can the problem be something else? 

Thanks for getting back to me!

**Comment by olivierfriard** [comment]
Hi,
I need more details.
BORIS version, info about your video (use Tools > media file info), etc
In order to reproduce the issue I need the video that corrupts the BORIS project file (if it is possible you can use WeTransfer) and the detailed procedure you ar following to code.

**Comment by Lianvv** [comment]
Hi! 

We use BORIS 7.2.12 and on Windows 11.
This is the media file information: 
VLC analysis
State: State.Paused
Media Resource Location: file://storage.fss.uu.nl/cdj_researchdata%24/Leerstoel%20Lubbers/Project%20Blok/26/Video%20Data/2613_W1_01.MTS
File name: 2613_W1_01.MTS
Track: 4113/2
Number of media in media list: 2
get time: 0
duration: 00:58:17.513
Position: 0.0 %
FPS: 25.0
Rate: 1.0
Video size: (1920, 1080)
Scale: 0.0
Aspect ratio: None
is seekable? Yes
has_vout? Yes

FFmpeg analysis
File path: \\storage.fss.uu.nl\cdj_researchdata$\Leerstoel Lubbers\Project Blok\26\Video Data\2613_W1_01.MTS
Duration: 00:58:17.310
Bitrate: 8462k
FPS: 25
Has video: True
Has audio: True

Total duration: 01:55:25.020 (hh:mm:ss.sss)File path: \\storage.fss.uu.nl\cdj_researchdata$\Leerstoel Lubbers\Project Blok\26\Video Data\2613_W1_02.MTS
Duration: 00:57:07.710
Bitrate: 8465k
FPS: 25
Has video: True
Has audio: True

Total duration: 01:55:25.020 (hh:mm:ss.sss)

We work with human participants (teacher-child interactions) so I cannot send the video GDPR wise because it is not anonymous data and I cannot share the video without legal documents of confidentiality etc.  

For coding we use subjects and behaviors, but not modifiers or anything else.

**Comment by olivierfriard** [comment]
Thank you for the information.
You are using a very old version of BORIS, my advice is to check if this issue is also present in the last version (8.17.1).
Please let me know.

**Comment by Lianvv** [comment]
We will try soon! First completing other open projects. 
I'll let you know if a new version works.
