### ISSUE TITLE
Video not playing (going black) on Macbook Pro All versions EXCEPT v7.9.6 which has other problems :'(

### ISSUE THREAD

**Issue by kittenbuns** [olivierfriard/BORIS#619]
**Indicate the version of BORIS**
I tried a number of versions, including the latest- the only version that the issue is not occurring in is v7.9.6 but the platform keeps hanging and I can't view my observations in the panel in this version
  
**Describe the bug**
When opening a new or existing observation in BORIS, video isn't running- the video screen just looks like a black box. The video works but poorly in the frame-by-frame version- the resolution is so bad that you can't analyse it.
Please help, I love BORIS too much.

**To Reproduce**
1. Go to 'Start Observation'
2. Click on 'Any observation'
3. See error- video does not open and there is just a black box there

**Expected behavior**
I expected the video to run on my Mac the way it is running in v7.9.6

**Screenshots**
If applicable, add screenshots to help explain your problem. SHOWING THE ISSUE WITH v7.9.6 here, the GUI is malfunctioning, can't view observations or record the, properly but the video is running smoothly in this version
<img width="1408" alt="Screenshot 2023-05-12 at 12 23 45" src="https://github.com/olivierfriard/BORIS/assets/133326261/c6ce01a5-9de9-4e66-a8a7-b31fcc8c98ce">

**Desktop (please complete the following information):**
 - OS: MacOsMonterey version 12.3.1
 - Type of BORIS instalaltion (setup or portable ...) Downloaded the latest version from the website

**Comment by olivierfriard** [comment]
Hi,
if you want to continue to use your Mac you have to switch to an alternative solution to run the last version of BORIS (currently 8.19.3), See http://www.boris.unito.it/pages/download_mac for details

**Comment by kittenbuns** [comment]
Thank you! Is this solution for all versions of BORIS? Or just the latest one? The issue I'm experiencing is occurring with all older versions as well. 
Looks like other people have also experienced it: https://github.com/olivierfriard/BORIS/issues/265

**Comment by olivierfriard** [comment]
It is the solution for using versions > 7.3.19 on MacOS

**Comment by kittenbuns** [comment]
Okay, great- thanks for the clarification :)
