### ISSUE TITLE
Find / Find and Replace Bug

### ISSUE THREAD

**Issue by jamiahuswalton** [olivierfriard/BORIS#62]
Hello, 

When I searched for a behavior to replace and BORIS does not find the behavior, it asks to search from the beginning as normal and begins the search again. However, if it does not find it a second time then it asks if I want to it to search again. This continues to happen until I say No. 

I recommend telling BORIS to stop after passing through every behavior. Not sure the technical way to go about that.

**Comment by olivierfriard** [comment]
improved the "Find events" function

**Comment by olivierfriard** [comment]
improved the "Find events" function in v. 6.1.2 released now
