### ISSUE TITLE
program is crashing when increasing speed 

### ISSUE THREAD

**Issue by laura20232023** [olivierfriard/BORIS#624]
**Indicate the version of BORIS**
 Verify you are using the last version (http://www.boris.unito.it/pages/download.html)
 BORIS for Windows Setup v.8.19.3.

**Describe the bug**
We are using the software to code videos and every time we increase the speed the program crashes or we are forced to close it because it is not responding anymore. This also happens when uploading new observations into the software. Could it be that the video files (MP4) are too big? Most of the time the program does not report an error code and is just closing itself. Sometimes, we do get an error code, so it depends. 

**To Reproduce**

**Expected behavior**
Everytime we upload a video file, and increase the speed of the videos to e.g. 6 or 7 (or higher) the program will not react anymore.

**Screenshots**

![fac24ff9-8c0b-4361-bddb-b9c3cfd74bda](https://github.com/olivierfriard/BORIS/assets/135323374/491f8b33-3789-42fd-b775-74127324822e)

**Desktop (please complete the following information):**
 - OS: [windows 10 10.0.19044]
 - Type of BORIS instalaltion (setup 8.17.1 but also with newer version)

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)

**Comment by olivierfriard** [comment]
Hi,
I am not able to reproduce the issue.
Can you set the **MPV player hardware video decoding** to **no** and test if the issue is still present?
See Project > Preferences
Another solution is to resize/re-encode your video.
Otherwise send me a sample of your video (if possible)

**Comment by laura20232023** [comment]
Hi,

thank you for your suggestions! Setting the MPV player hardware video decoding to no helped a lot and we are able to minimize the crashing when increasing the speed.

________________________________

**Comment by olivierfriard** [comment]
Hi,
can you send me information about your video (See Tools > Media information) ?
You can also try to resize / re-encode your video (See Tools > Resize / re-encode)
