### ISSUE TITLE
Boris freezes when using zoom

### ISSUE THREAD

**Issue by Viertelvor** [olivierfriard/BORIS#625]
**Indicate the version of BORIS**
Version 8.19.3

**Describe the bug**
Boris freezes when using the zoom.

**To Reproduce**
1. Open Observation
2. Click 'Ctr' + '+'
3. Click any button
4. "Boris stopped responding"

**Desktop (please complete the following information):**
Non-portable Boris

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)
[boris.log](https://github.com/olivierfriard/BORIS/files/11652779/boris.log)

**Comment by Viertelvor** [comment]
[boris.log] (https://github.com/olivierfriard/BORIS/files/11652786/boris.log)

**Comment by Viertelvor** [comment]
The problem persists in the newest version (8.20.3)

[boris.log](https://github.com/olivierfriard/BORIS/files/11655142/boris.log)

**Comment by olivierfriard** [comment]
Hi,
I am not able to reproduce this issue.

Can you change the **MPV player hardware video encoding** to **no** and check if the issue is still present?
If yes send me a sample of your video (if possible)
