### ISSUE TITLE
Request for Zoom In/Out Function

### ISSUE THREAD

**Issue by jcchen123** [olivierfriard/BORIS#629]
Hello, this software is very useful and has provided me with a lot of help in my research. I am currently engaged in observing the behavior of small insects such as aphids. In previous versions, I could easily zoom in and out using the left mouse button, but in the new version, I could only use ctri+/- to observe the target. However, this process was very inconvenient. Can you add the same function as before? I just need to click anywhere in the video to achieve the method and zoom out? Thank you.best wishes！

**Comment by olivierfriard** [comment]
I will try to implement this
o

**Comment by jcchen123** [comment]
Thank you very much for your reply, and I wish BORIS better and better!

**Comment by izzymolly** [comment]
Hi Olivier, 
I wanted to follow up on this thread and see if you have been able to implement the old zoom function into the newer version of BORIS? We love this software, but the new version of it has made it virtually impossible to efficiently view our videos.

**Comment by olivierfriard** [comment]
A new zoom function was implemented.
See https://www.boris.unito.it/user_guide/playback_menu/#zoom-level
