### ISSUE TITLE
Increased size for Coding Maps

### ISSUE THREAD

**Issue by BenCallisto** [olivierfriard/BORIS#635]
Hello, 

would it be possible to work with much larger coding map sizes? I tried to custom mix a zone map with a coding pad from a PNG file to have optimal screen usage and had to then settle on a different layout to accommodate the 640 pixel limit. My template was 1500 by 3600 pixels, working on a studio sized touch screen monitor (Surface Studio 2).

**Comment by olivierfriard** [comment]
Hi,
thank you for the suggestion.
The bitmap is no longer resized in v. 8.21.5
Please try and let me know
