### ISSUE TITLE
Crash upon using coding map (mouse as well as pen input)

### ISSUE THREAD

**Issue by BenCallisto** [olivierfriard/BORIS#636]
Below my attempt of a documentation and report, some background information here: I would like to code movement and behaviour of workers including a posture analysis, which results all together in 74 codes for 18 hours of video material, hence it would be favorable to not rely on modifiers. 

A coding map for position data and posture figures as well as behaviour keywords seemed reasonable. To my understanding, I would be limited by the amount of keys on my keyboard, hence the attempt of relying on zones on a code map (see picture below). I tried in this process key assigned and non key assigned codes with my code map, in the end all of them crashed upon the initial zone click. I tried both routes, assigning new codes to a code map, as well as assigning zones to existing codes. Have I misunderstood something in the setup?

Thank you very much!

Ben

**Indicate the version of BORIS**
8.20.4 WIN64 Setup

**Describe the bug**
Testing a behavior map setup resulted in a crash error message upon the second click on the same zone to close a state event

**To Reproduce**
1. Create a new project, no ethnogram yet
2.  Create a new behaviour map, add a test zone with proper name
3. Apply changes and save map, also assign map to project
4. Edit project ethnogram
5. Add new state event behaviour based on map
6. Add according code
7. Save changes and start new observation
8. Add coding map and start video playback
9. Click on zone to open event
10. Click again to close event, receive crash log below

**Expected behavior**

**Screenshots**
-/-

**Desktop (please complete the following information):**
 - OS: [windows 11 Pro]
 - Type of BORIS instalaltion (setup)

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
BORIS version: 8.20.4
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-08-01 14:26

Traceback (most recent call last):
  File "C:\Users\user\BORIS\Lib\site-packages\boris\core.py", line 3691, in click_signal_from_behaviors_coding_map
    write_event.write_event(self.event, self.getLaps())
TypeError: write_event() missing 1 required positional argument: 'mem_time'

System info:

Host Name:                 SURFACE_STUDIO
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          user
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA918
Original Install Date:     12/04/2023, 13:33:25
System Boot Time:          13/07/2023, 01:46:22
System Manufacturer:       Microsoft Corporation
System Model:              Surface Studio 2
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~2904 Mhz
BIOS Version:              Microsoft Corporation 536.645.768, 05/04/2015
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             de;German (Germany)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     32,725 MB
Available Physical Memory: 24,526 MB
Virtual Memory: Max Size:  34,773 MB
Virtual Memory: Available: 21,666 MB
Virtual Memory: In Use:    13,107 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\SURFACE_STUDIO
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5028851
                           [02]: KB5012170
                           [03]: KB5028185
                           [04]: KB5028320
Network Card(s):           5 NIC(s) Installed.
                           [01]: Xbox Wireless Adapter for Windows
                                 Connection Name: LAN-Verbindung
                                 DHCP Enabled:    No
                                 IP address(es)
                           [02]: Intel(R) Ethernet Connection (2) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Marvell AVASTAR Wireless-AC Network Controller
                                 Connection Name: WLAN
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.178.1
                                 IP address(es)
                                 [01]: 192.168.178.50
                                 [02]: fe80::b1e2:ccf3:2c37:e96e
                                 [03]: 2001:1c06:2711:6000:3a56:f874:30:e1b4
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth-Netzwerkverbindung
                                 Status:          Media disconnected
                           [05]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
![Coding Map 640](https://github.com/olivierfriard/BORIS/assets/141143791/2fec5682-9354-4a1b-a05c-dcdcd5522b01)

**Comment by BenCallisto** [comment]
I did a second run, creating a behaviour list with code keys first, and then a code map with assigned point events to zones. Again the program crashed instantly upon clicking the first time on the map, whereas state events via keycodes worked fine.
I can see the same error message in the Python readout, which is: TypeError: write_event() missing 1 required positional argument: 'mem_time'

Am I holding it wrong?

![image](https://github.com/olivierfriard/BORIS/assets/141143791/68aa7855-2533-4dd5-90ef-e17a2e5d4a33)

**Comment by BenCallisto** [comment]
I did a second run, creating a behaviour list with code keys first, and then a code map with assigned point events to zones. Again the program crashed instantly upon clicking the first time on the map, whereas state events via keycodes worked fine.
I can see the same error message in the Python readout, which is: TypeError: write_event() missing 1 required positional argument: 'mem_time'
![257565596-68aa7855-2533-4dd5-90ef-e17a2e5d4a33](https://github.com/olivierfriard/BORIS/assets/141143791/f1a046ca-48ca-4c55-ae9b-8f0a4a1b9234)

Am I holding it wrong?

**Comment by olivierfriard** [comment]
Hi,
Thank you for reporting this.
The issue should be fixed in v. 8.21.5
Please try and let me know
