### ISSUE TITLE
Failure to Load Time Converter

### ISSUE THREAD

**Issue by CKnau9** [olivierfriard/BORIS#640]
I was trying to load the time converter (ISO8601_to_seconds) from the BORIS repository and got the following error message. Originally I was on the last version of BORIS and nothing was happening, so I updated to the most recent version 8.20.4 and am now getting the error instead of nothing happening. I want to add data files to the project but need to convert the time. 

BORIS version: 8.20.4
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-08-03 11:41

Traceback (most recent call last):
  File "C:\Users\orego\BORIS\Lib\site-packages\boris\project.py", line 387, in <lambda>
    self.pb_load_from_repo.clicked.connect(lambda: converters.load_converters_from_file_repo(self, mode="repo"))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orego\BORIS\Lib\site-packages\boris\converters.py", line 328, in load_converters_from_file_repo
    function = self.code_2_func(converter_name, converters_from_file[converter]["code"])
               ^^^^^^^^^^^^^^^^
AttributeError: 'projectDialog' object has no attribute 'code_2_func'

System info:

Host Name:                 LAPTOP-SBUCGLIR
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          oregon93@comcast.net
Registered Organization:   N/A
Product ID:                00325-81462-86677-AAOEM
Original Install Date:     1/4/2023, 4:58:34 PM
System Boot Time:          7/15/2023, 4:19:21 AM
System Manufacturer:       LENOVO
System Model:              81SX
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              LENOVO BHCN42WW, 5/21/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,303 MB
Available Physical Memory: 5,868 MB
Virtual Memory: Max Size:  28,079 MB
Virtual Memory: Available: 9,061 MB
Virtual Memory: In Use:    19,018 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-SBUCGLIR
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5028851
                           [02]: KB5012170
                           [03]: KB5028185
                           [04]: KB5028320
Network Card(s):           4 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: TAP-Windows Adapter V9
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [03]: Intel(R) Wireless-AC 9560 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.119.1
                                 IP address(es)
                                 [01]: 192.168.119.84
                                 [02]: fe80::3862:9bef:33e3:6332
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
The issue should be fixed in v. 8.20.6 just released.
Please test and let me know
