### ISSUE TITLE
Create observations from media files

### ISSUE THREAD

**Issue by Asajoh** [olivierfriard/BORIS#643]
I have several 10 minute long videos and all relevant information for the observation can be found in the file name. It is quite time consuming to create individual observations manually for each file. Would it be possible to implement a feature where you select media files in a directory and Boris automatically creates an observation per file?

Alternatively, would it be possible to export data from one observation with several videos with a column specifying the video? I usually use the time budget function and that doesn't seem to have any functionality that allows data to be separated by video. I guess a work around would be to specify a modifier per video in the observation or perhaps a category?

**Comment by olivierfriard** [comment]
Hi,
I added this feature in v. 8.21.3 (see https://github.com/olivierfriard/BORIS/releases/tag/v8.21.3).
See Observations > Create observations
You will have to select a directory and some parameters for the newly created observations.

Please try it and let me know
