### ISSUE TITLE
Error in exporting subjects from project

### ISSUE THREAD

**Issue by TSacca** [olivierfriard/BORIS#647]
**Indicate the version of BORIS**
BORIS for Windows Setup v.8.20.6

**Describe the bug**
Tried to export subject from project and got error message.

**To Reproduce**
1. Go to 'Project'
2. Click on 'Edit Project'
3. Go to 'Subject tab'
4. Click on 'Export subjects'
6. See error
[Error_Export_Subjects.txt](https://github.com/olivierfriard/BORIS/files/12522374/Error_Export_Subjects.txt)

**Expected behavior**
To have a file in which the exports are listed, or any other prompt that is not an error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 11]

 - Type of BORIS instalaltion (setup)

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
The issue should be fixed in v. 8.20.7 just released.
Please try and let me know

**Comment by TSacca** [comment]
Hi,
After installing the new version it works, thank you!

**Comment by nplbrt** [comment]
Hi, I'm using version 8.21.5 and I'm having the same problem. I saved the project with the subjects but when I open the project later, the subject is not there.

**Comment by olivierfriard** [comment]
Hi,
what do you mean by "save the project with the subject"?
You are trying to export subjects?
Please send me a detailed procedure to reproduce the problem.
