### ISSUE TITLE
BORIS 8.21.5 has dependency that no longer exists in current Debian distributions

### ISSUE THREAD

**Issue by eebrandt** [olivierfriard/BORIS#652]
Issue installing BORIS Version 8.21.5 

I am unable to install the current version of BORIS due to an unresolved dependency. The package libmpv1 (https://packages.debian.org/search?keywords=libmpv1)  is required, but this package no longer exists in either unstable, testing or stable distributions of Debian. I can work around this issue by installing the package from older distributions, but this is not ideal. Suggestion to update BORIS dependencies accordingly. Thanks!

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
Can you try the boris-8.21.5-0_libmpv2.deb package and let me know if it works?
See https://github.com/olivierfriard/BORIS/releases/tag/v8.21.5

**Comment by eebrandt** [comment]
This seems to have fixed the install issue, thanks for getting to this so quickly!
