### ISSUE TITLE
Unable to install on windows 11

### ISSUE THREAD

**Issue by ceedmuva** [olivierfriard/BORIS#655]
**Boris 8.21.5-win64**
 
I have a new notebok with windows 11, but i'm unable to instal ( if I double click it send me to the microsft store). I checked online and read that the "S" version of W11 is unable to install 3r party apps, but I checked mine and is not currently at S mode.  So idk what to do.

My notebook is a Lenovo Ideapad Slim 5:
Procesador	13th Gen Intel(R) Core(TM) i7-13620H   2.40 GHz
RAM instalada	16,0 GB (15,7 GB usable)
Identificador de dispositivo	51784767-40DC-4343-ACED-05D182989DDC
Id. del producto	00342-42329-19484-AAOEM
Tipo de sistema	Sistema operativo de 64 bits, procesador basado en x64

**Comment by ceedmuva** [comment]
I run the program with the compatibility mote of windows  8 and I was abble to install the software

**Comment by olivierfriard** [comment]
Hi,
thank you for this info
