### ISSUE TITLE
String modifier type for state events

### ISSUE THREAD

**Issue by juaninachon** [olivierfriard/BORIS#656]
Dear Olivier,

Thank your for this beautiful piece of software.

I've been trying out BORIS for a week now and love it so far. I'm using it to code videos of child-parent play for my PhD. I came across it while looking for alternatives to Datavyu and ELAN, which sometimes can't handle multiple 1080p/60fps files simultaneously.   

I'm running v. 8.21.5 on Ubuntu 22.04.3 , Intel i7-7700 16gbRam.

At the moment, I'm trying to find a straightforward way to transcribe speech alongside non-verbal behavior, without having to rely on secondary software (e.g., ELAN, Praat). The waveform widget is a great tool to accurately get the onsets/offsets and I've noticed that one way to accomplish my goal is to use the numeric type modifier (which occasionally accepts non-numeric character inputs —screenshots below—, but I suspect this is not an intended feature). However, I randomly get the would-be-expected input type error when focusing on a subject or attempting to edit an already existing event. 

A consistent alternative, which I have chosen to compromise with, is to simply comment each event. But this requires editing preexisting events or adding a new ones with "ctrl+a" and then picking the corresponding code form the drop down list (I just set the label to "0_verbal" so that it becomes the alphabetical default, but it gets trickier when handling multiple codes). The ideal scenario in my head is being able to keep using keybindings for different codes, with an ad-hoc event or modifier type, specific for verbal behavior  (i.e., a state event which only gets a string modifier input prompt once, when creating the START event, so as not being forced to repeat the exact same input in order to get the STOP, else creating an additional —potentially undesired— START).

Please let me know if there's already another method conceived for doing this that I'm not seeing (and forgive me if that's the case). 

Kind regards,

Juan

![image](https://github.com/olivierfriard/BORIS/assets/51125660/fa1f835c-c3ca-41e5-b586-8db7673b6b42)
![image](https://github.com/olivierfriard/BORIS/assets/51125660/9c2fc754-0abc-44c7-ba5c-f5891624d4be)
![image](https://github.com/olivierfriard/BORIS/assets/51125660/40791d9f-3848-473b-9aa0-de73e8df43bd)
![image](https://github.com/olivierfriard/BORIS/assets/51125660/0156f543-820b-4c5f-9eb8-1035cb689821)
![image](https://github.com/olivierfriard/BORIS/assets/51125660/41a59407-205e-4181-9bc3-f7e4f18ffebf)

**Comment by olivierfriard** [comment]
Hi Juan,

thank you for reporting this.
What about adding an option to automatically trigger a comment dialog box when an event is added?

**Comment by juaninachon** [comment]
Sure, I guess that could work. Thanks for your reply!
