### ISSUE TITLE
Playback speed not changing

### ISSUE THREAD

**Issue by dmckinst** [olivierfriard/BORIS#663]
**Indicate the version of BORIS**
 v. 7.13.9

**Describe the bug**
I'm unable to increase or decrease the playback speed of videos. I played around with the step-value to see if increasing it to 5.0 would make a difference, but the video continues to play at normal speed when I click either of the (+) or (-) buttons in the toolbar to manipulate the speed.

**Desktop (please complete the following information):**
 Operating on a macOS Ventura 13.4

**Comment by olivierfriard** [comment]
Hi,
v. 7.13.9 is no longer supported.
See http://www.boris.unito.it/pages/download_mac to launch the last version on macOS
