### ISSUE TITLE
Plot events crashed

### ISSUE THREAD

**Issue by Philippe-s-Levi** [olivierfriard/BORIS#670]
Hi Olivier,

Crash after "Analyze" / "Plot" / "Plot events" 

Going normaly through the 2 windows ... running a few seconds and crashes.

Same with Plot events budget

(events ... tsv file renamed to be annexed)
[tsv.txt](https://github.com/olivierfriard/BORIS/files/13045187/tsv.txt)

[boris_error.log](https://github.com/olivierfriard/BORIS/files/13045128/boris_error.log)

deleted .boris, crash remains

Thanks

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
I need the content of the Help > About > Show details ... 

Can you send me your project file (by email) and a detailed procedure to reproduce this issue?

**Comment by Philippe-s-Levi** [comment]
to reproduce ... "Analysis" / "Plot" / "Plot events" nothing else !

**Comment by olivierfriard** [comment]
I am not able to reproduce this issue (even with your BORIS project file)

**Comment by Philippe-s-Levi** [comment]
solved!

I got two versions of matplotlib in boris directory ... may be because I did not uninstall BORIS before intalling the new version !

I uninstalled BORIS and reinstall and it works again.
