### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by Philippe-s-Levi** [olivierfriard/BORIS#672]
Hi Olivier,

just a suggestion ...

There is "Playback" and "Tools" / "Media file". Rotate video is repeated in both but, any way, it may be natural to move Media file to Playback ...

Philippe

**Comment by olivierfriard** [comment]
"Playback > Rotate video" rotates the video into the player (the media file is not modified)

"Tools > Media file > Rotate video" rotates the video file (with the embedded ffmpeg program)

I will change the last option in "Rotate video file" to be more precise

Thanks
