### ISSUE TITLE
unable to import ethogram from csv

### ISSUE THREAD

**Issue by azuckerwise** [olivierfriard/BORIS#678]
**BORIS version 8.21.8**

**Issue**
When I attempt to import an ethogram from a CSV file, BORIS stops responding for a minute and then generates an error. If I click "ignore," it will only upload the first behavior on the list. My CSV file has the following columns: Behavior type, Key, Behavior code, Behavioral category, Description, Excluded behaviors. The same occurs with an xlsx file. 

**Steps to reproduce the behavior**
1. Go to New Project or Edit Project, Ethogram tab
2. Click on Import ethogram from a text file
3. Select the CSV file with the ethogram

**Expected behavior**
I expected it to upload an ethogram from the CSV file so I don't have to enter them individually. 

**Desktop:**
 - OS: Windows
 - Type of BORIS installation: setup or portable 

**Error report**
BORIS version: 8.21.8
OS: Windows 10 10.0.19044
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-11-02 12:46

Traceback (most recent call last):
  File "C:\Users\ameliaz\BORIS\Lib\site-packages\boris\project.py", line 308, in <lambda>
    menu.triggered.connect(lambda x: self.import_ethogram(action=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameliaz\BORIS\Lib\site-packages\boris\project.py", line 460, in import_ethogram
    project_import_export.import_behaviors_from_text_file(self)
  File "C:\Users\ameliaz\BORIS\Lib\site-packages\boris\project_import_export.py", line 514, in import_behaviors_from_text_file
    load_dataframe_into_behaviors_tablewidget(self, df)
  File "C:\Users\ameliaz\BORIS\Lib\site-packages\boris\project_import_export.py", line 439, in load_dataframe_into_behaviors_tablewidget
    item = QTableWidgetItem(str(behavior[field_type]))
                                ~~~~~~~~^^^^^^^^^^^^
KeyError: 'color'

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this issue.
It should be fixed in v. 8.21.9 just released.
Can you check and let me know?

**Comment by azuckerwise** [comment]
I downloaded the new version and it works now, thank you.
