### ISSUE TITLE
Modifiers for modifiers

### ISSUE THREAD

**Issue by AlenaFis** [olivierfriard/BORIS#683]
Hi, 

I would like to ask you if it is possible to add modifiers for modifiers. For example, I have a bird that forages on a branch, but I need to choose another information for this branch. Now I need to have a long list of all modifiers for all different substrates and I have to be very careful not to forget any information. It would be really great if I could click on the branch and then just select the additional information, rather than having to select it from a long list of other modifiers unrelated to this one. 

Example: Branch - bark/no bark, small/big, 1 meter high/10 meters high

Thank you!

**Comment by beckyhansis** [comment]
Seconded. I also could use this feature.

**Comment by olivierfriard** [comment]
Hi,
I am sorry but I will not implement this feature.
Maybe it is possible to reorganize your ethogram to make coding simpler?

**Comment by beckyhansis** [comment]
I ended up making a subjects list with an ethogram that has each behavior
and potential modifier combo. It is not simple, but it works and uses no
modifers. For reference, the behavior was:

Bee touches* x* part of flower *y* with *z* body part.
