### ISSUE TITLE
Pause Key EDITED

### ISSUE THREAD

**Issue by kthmsu** [olivierfriard/BORIS#687]
I would appreciate a keyboard key shortcut to pause the media similar to the keys for jumping forward and back, changing playback speed, and changing the frame.

EDIT:
I have found that the spacebar does this action, however I would still like to request that this feature be explicitly mentioned in the section about special keyboard keys

**Comment by olivierfriard** [comment]
Hi,

thank you for your suggestion.
I will add this to the documentation.
