### ISSUE TITLE
FFmpeg is not available

### ISSUE THREAD

**Issue by HanneloreStr** [olivierfriard/BORIS#691]
Boris version 8.22.6

I installed BORIS and want to start the program via start_boris. However, I receive a popup message 'FFmpeg is not available. Go to ffmpeg.org to download it." I downloaded ad installed ffmpeg. I tried to place the folder in different folders, including the one from BORIS and in the folder Lib in BORIS. However, the message keeps appearing. Can someone help me? As long as the  popup appears, I am not able to open the program.

**Comment by olivierfriard** [comment]
Hi,

what is your operating system?

**Comment by HanneloreStr** [comment]
Hi, this morning I was able to solve the issue myself. BORIS suggested to be installed in the directory of my user. I reinstalled it on my C-drive and now the program is working. I have a Windows 10 operating system.

**Comment by olivierfriard** [comment]
It is a little bit strange because the ffmpeg and ffprobe programs are included in the Windows version of BORIS.
You should find them in the following directory:
C:\Users\YOUR_USER_NAME\BORIS\Lib\site-packages\boris\misc
