### ISSUE TITLE
Jump To Specific Time Error

### ISSUE THREAD

**Issue by gjgrah** [olivierfriard/BORIS#698]
**Indicate the version of BORIS**
I am using the latest version of BORIS

**Describe the bug**
After the most recent update (8.22.6) when trying to jump to a specific time in a video, the jump to a specific time feature in playback always causes an error. 

**To Reproduce**
1. Load video
2. Go to Playback
3. Click Jump to Specific time

**Expected behavior**
I would expect a popup that allows me to select a time to jump to. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of BORIS instalation: Setup 8.22. 
 
** Error **
BORIS version: 8.22.6
OS: Windows 10 10.0.19042
CPU: AMD64 Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-01-05 14:31

Traceback (most recent call last):
  File "C:\Users\ggraham4\BORIS\Lib\site-packages\boris\core.py", line 1491, in jump_to
    jt.time_widget.set_time(0)
  File "C:\Users\ggraham4\BORIS\Lib\site-packages\boris\duration_widget.py", line 188, in set_time
    if new_time.is_nan():
       ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'is_nan'

System info:

Host Name:                 DESKTOP-Q49ML0C
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00355-62735-67705-AAOEM
Original Install Date:     3/31/2022, 3:07:40 PM
System Boot Time:          1/3/2024, 11:15:07 AM
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 7090
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 165 Stepping 5 GenuineIntel ~2904 Mhz
BIOS Version:              Dell Inc. 1.7.0, 4/15/2022
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
Total Physical Memory:     48,885 MB
Available Physical Memory: 34,483 MB
Virtual Memory: Max Size:  56,053 MB
Virtual Memory: Available: 40,082 MB
Virtual Memory: In Use:    15,971 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-Q49ML0C
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB5013624
                           [02]: KB4534170
                           [03]: KB4537759
                           [04]: KB4545706
                           [05]: KB4562830
                           [06]: KB4598481
                           [07]: KB5014699
                           [08]: KB5014035
                           [09]: KB5005699
Network Card(s):           1 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (14) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.17.2.20
                                 IP address(es)
                                 [01]: 128.174.73.239
                                 [02]: fe80::dd3a:1b7b:ee7e:d3ff
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
Can you try the pre-release version 8.22.13 and check if the issue is still present?
https://github.com/olivierfriard/BORIS/releases/tag/v8.22.13

**Comment by gjgrah** [comment]
> Hi, thank you for reporting this. Can you try the pre-release version 8.22.13 and check if the issue is still present? https://github.com/olivierfriard/BORIS/releases/tag/v8.22.13

That fixed the problem, thanks :)
