### ISSUE TITLE
Photos Not Loading

### ISSUE THREAD

**Issue by dabkowskio** [olivierfriard/BORIS#702]
I am using version 8.22.16 of BORIS and when I try and start a new observation where the media files are photos, they don't load. The rest of the observation loads (ethogram, directory info, etc.) but none of the photos are displayed. 

I create a new observation and click the observation from pictures option. Then I create an absolute path to the folder containing all of the photos. Then I click start and I see the screen below: 

![image](https://github.com/olivierfriard/BORIS/assets/156737758/5a4ccc1d-793f-4d18-817b-2485303b868c)

Sometimes the images load. Most times they don't. I am using an HP computer running windows 11 version 22H2, OS build: 22621.3007. I have 8 GB RAM and a 64-bit operating system. I downloaded both the portable and Setup version of BORIS and had the same issue on both.

**Comment by olivierfriard** [comment]
Hi,
is it possible to access a dataset to reproduce this issue?
You can contact me by email olivier.friard@unito.it if you prefer

**Comment by dabkowskio** [comment]
Hey Olivier
I'm currently on Chatham island so will send a dataset when I can.

Owen

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by olivierfriard** [comment]
Hi,
I received you dataset and the pictures are loading without problem.
