### ISSUE TITLE
Limit Observation to Time Interval

### ISSUE THREAD

**Issue by veronawildcats** [olivierfriard/BORIS#705]
Version 8.22.14 (2023-01-06)

When I add a new observation, I check the box that says 'Limit Observation to Time Interval'. I then try to set the time using the hh:mm:ss:ms option. When I type the minute and the second, it changes it to hour and minute.

1. Go to observations
2. Click on new observation
3. Check the box that says 'Limit Observation to Time Interval'
4. Use the hh:mm:ss:ms option and type in a random value for minute and second
5. Do it again for the end time
6. Click save and you should see that it changes to hour and minute

I expect the minute and seconds to stay as minutes and seconds and not change to hours and minutes.

![Start time](https://github.com/olivierfriard/BORIS/assets/157421531/4efda8a3-1179-490b-934b-4d1a8b7ecf84)
![End time](https://github.com/olivierfriard/BORIS/assets/157421531/c6609bd2-9e0e-4e51-8a60-33220ab61f6c)
![End result](https://github.com/olivierfriard/BORIS/assets/157421531/d654ae71-a0af-485a-9e91-21a469ac20bc)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - BORIS for Windows Setup v.8.22.14

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
This issue should be fixed in v. 8.22.17 just released.
Please let me know

**Comment by veronawildcats** [comment]
It's fixed thank you.
