### ISSUE TITLE
New live observation not allowing start

### ISSUE THREAD

**Issue by eltingrosalee** [olivierfriard/BORIS#707]
**Indicate the version of BORIS**
Version 8.22.17

**Describe the bug**
When starting a live observation, an error occurs after pressing start. 

**To Reproduce**
1. Open existing project 
2. Observations > New observation. Observation type: live observation >  start from current time > day time 
3. Press start
4. error window appears 

**Expected behavior**
Expected main window to reflect what is in the user manual here: https://boris.readthedocs.io/en/latest/#live-observations, with a timer. 

**Error from step 4 above**

An error has occured

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.22.17
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-01-24 15:31

Traceback (most recent call last):
  File "C:\Program Files (x86)\boris-8.22.17-win64\Lib\site-packages\boris\connections.py", line 88, in 
    self.actionOpen_observation.triggered.connect(lambda: observation_operations.open_observation(self, mode=cfg.OBS_START))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\boris-8.22.17-win64\Lib\site-packages\boris\observation_operations.py", line 176, in open_observation
    return load_observation(self, selected_observations[0], mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\boris-8.22.17-win64\Lib\site-packages\boris\observation_operations.py", line 215, in load_observation
    initialize_new_live_observation(self)
  File "C:\Program Files (x86)\boris-8.22.17-win64\Lib\site-packages\boris\observation_operations.py", line 2137, in initialize_new_live_observation
    current_time = util.seconds_of_day(dt.datetime.now())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\boris-8.22.17-win64\Lib\site-packages\boris\utilities.py", line 762, in seconds_of_day
    return dec((timestamp - dt.datetime.combine(dt.date(), dt.time(0))).total_seconds()).quantize(dec("0.001"))
                                                ^^^^^^^^^
TypeError: function missing required argument 'year' (pos 1)

System info

Host Name:                 ROSALEE_LAPTOP
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          rosalee.elting@gmail.com
Registered Organization:   N/A
Product ID:                00355-60992-96699-AAOEM
Original Install Date:     8/22/2023, 4:35:01 PM
System Boot Time:          1/18/2024, 2:46:35 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 5470
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 154 Stepping 3 GenuineIntel ~2300 Mhz
BIOS Version:              Dell Inc. 1.18.0, 11/13/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-07:00) Mountain Time (US & Canada)
Total Physical Memory:     15,991 MB
Available Physical Memory: 4,963 MB
Virtual Memory: Max Size:  21,261 MB
Virtual Memory: Available: 4,230 MB
Virtual Memory: In Use:    17,031 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\ROSALEE_LAPTOP
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5033920
                           [02]: KB5012170
                           [03]: KB5029517
                           [04]: KB5034123
                           [05]: KB5032393
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.10.40.74
                                 IP address(es)
                                 [01]: 10.17.156.154
                                 [02]: fe80::9ee5:1fd2:9a5b:7f17
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this issue.
The problem should be fixed in v. 8.22.20 just released.

**Comment by eltingrosalee** [comment]
Thank you so much for the resolution. This works well now!


Best,

Rosalee



________________________________
