### ISSUE TITLE
Error when commenting on event

### ISSUE THREAD

**Issue by JoxerJ** [olivierfriard/BORIS#710]
**Indicate the version of BORIS**
 Verify you are using the last version (http://www.boris.unito.it/pages/download.html)

**Describe the bug**
I am not allowed to comment on behaviors
[comment error.txt](https://github.com/olivierfriard/BORIS/files/14122837/comment.error.txt)

**To Reproduce**
Note Event
Edit selected event
Add comment
Ok
Couple seconds later an error pops up and no comment was made

**Desktop (please complete the following information):**
 Windows 11
 BORIS program (v. 8.22.16 2024-01-12)

**Comment by olivierfriard** [comment]
Hi,
can you reproduce this issue with the version 8.24 just released?
