### ISSUE TITLE
It is not possible to open my project

### ISSUE THREAD

**Issue by MarisolParadaS** [olivierfriard/BORIS#716]
An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.22.22
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\mpsar\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-02-09 09:05

Traceback (most recent call last):
  File "C:\Users\mpsar\BORIS\Lib\site-packages\boris\core.py", line 2915, in open_project_activated
    ) = project_functions.open_project_json(file_name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mpsar\BORIS\Lib\site-packages\boris\project_functions.py", line 1308, in open_project_json
    pj = util.convert_time_to_decimal(pj)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mpsar\BORIS\Lib\site-packages\boris\utilities.py", line 268, in convert_time_to_decimal
    pj[cfg.OBSERVATIONS][obs_id][cfg.TIME_OFFSET] = dec(str(pj[cfg.OBSERVATIONS][obs_id][cfg.TIME_OFFSET]))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

System info
===========

Host Name:                 NBC-LAP-MPSAR
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          vetadmin
Registered Organization:   
Product ID:                00355-62924-00915-AAOEM
Original Install Date:     7/6/2022, 11:06:27 AM
System Boot Time:          2/9/2024, 7:49:54 AM
System Manufacturer:       Dell Inc.
System Model:              Latitude 3520
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~1382 Mhz
BIOS Version:              Dell Inc. 1.20.0, 7/12/2022
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,123 MB
Available Physical Memory: 6,842 MB
Virtual Memory: Max Size:  18,555 MB
Virtual Memory: Available: 6,237 MB
Virtual Memory: In Use:    12,318 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    vet.upenn.edu
Logon Server:              \\DC66
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB5030650
                           [02]: KB5030842
                           [03]: KB5010690
                           [04]: KB5011048
                           [05]: KB5012170
                           [06]: KB5031358
                           [07]: KB5031591
Network Card(s):           3 NIC(s) Installed.
                           [01]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [02]: Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.113
                                 [02]: fe80::30d9:a56e:ddfc:55fa
                           [03]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
can you repeat this issue with the last version (8.24)?
Thank you

**Comment by MarisolParadaS** [comment]
The error happened when creating a new observation: I selected the option _Time Offset_ (I forgot to add a _Time value_), and at the saving moment, some pop window said something about decimals. 
After that error, I could not open the project again. 
I think this is the problem because, in the previous observations, I did not forget to add the _Time value_, and the project was always opening.
Thank you
--Marisol

**Comment by olivierfriard** [comment]
Thank for the details.
I will fix it as soon as possible.
o

**Comment by olivierfriard** [comment]
Hi,
the version 8.24.1 should fix this issue.
See https://github.com/olivierfriard/BORIS/releases/tag/v8.24.1
Please try and let me know
Thank you for your collaboration

**Comment by MarisolParadaS** [comment]
Hi,
Thank you! It is solved. 
Thank you very much :) My project opened again.
--Marisol
PS. How often do you look at the discussions tab?

**Comment by olivierfriard** [comment]
> PS. How often do you look at the discussions tab?

Not so much...
