### ISSUE TITLE
Better/Configurable Hotkeys

### ISSUE THREAD

**Issue by larvasapiens** [olivierfriard/BORIS#72]
When making an observation, I currently have to move my mouse over the buttons/menus to do practically anything (like changing the playback speed, opening a new observation, etc.). Having shortcuts for the frequently used commands would boost productivity, specially because I already need my hands on the keyboard to annotate the behaviours. Static shortcuts could work but a configuration menu in the software preferences would be ideal.
Some ideas for the defaults:

* \>, < and = to make the speed faster, slower or normal (based on the youtube shortcuts)
* Alt+\<letter\> to reach the menus. For example: Alt+F -> File menu, Alt+O -> Observations menu. This is rather standard.

By the way, I could help on this --I don't know if you accept pull requests, or adding me as a member of the team. 

Thanks in advance.

**Comment by olivierfriard** [comment]
Hello,
thank you for your suggestion.
> < = can be used as keys for behaviors so I can not use them as player shortkeys...
I will try to activate combinations of keys (Alt + letter)

Tipically the CTRL key is used in combination for menu (for example Ctrl + O will open a project).
I will add more menu shortcuts.

**Comment by olivierfriard** [comment]
Shortcuts were added in v. 4:

"New observation" (CTRL+N)
"Open observation" (CTRL+O)
"Edit observation" (CTRL+E)
"Observations list" (CTRL+L)
"Close observation" (CTRL+Q)
"Jump forward" (CTRL+F)
"Jump Backward" (CTRL+B)
"Save project" (CTRL+S)
