### ISSUE TITLE
Compiling Data 

### ISSUE THREAD

**Issue by kchung123** [olivierfriard/BORIS#726]
When exporting all the data, is there a function that states the compiled data? For example, if an observation had multiple "action 1" coded throughout, is there a function that would compile ALL "action 1" in the observation and say Action 1 was shown for a total of ____ minutes/seconds? 

This may come off unclear, so I apologize in advance!

**Comment by olivierfriard** [comment]
Hi,

check the time budget function in the user guide:
http://www.boris.unito.it/user_guide/analysis/
