### ISSUE TITLE
Web page 404

### ISSUE THREAD

**Issue by igutermes** [olivierfriard/BORIS#733]
I am sorry to open a issue on github, but I didn't know how could I get in touch with you. Many pages at https://www.boris.unito.it are 404. I am not sure what is going on...

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
I just updated the web site this afternoon (CET) and it is working for me.
Can you send me an example of page that does not display correctly?

**Comment by igutermes** [comment]
Thank you for the quick reply. 

Well, would you look at that... The pages that were 404 are now working just fine... Have you done anything since I reported?

But anyway, here are some of the ones that weren't working:


https://www.boris.unito.it/run_source_code/

https://www.boris.unito.it/user_guide/install/

**Comment by olivierfriard** [comment]
The web site should work fine now.
Thank you
