### ISSUE TITLE
Corrupted file - Loss of all data ?

### ISSUE THREAD

**Issue by dhuzard** [olivierfriard/BORIS#734]
Boris v8.23 (2024.01.29), Windows Standalone

Recent bug in the lab; during a scoring session, after moving the screen of the laptop, Boris started 'loading' (with light grey background) and, being afraid to lose the non saved data, the scorer did Ctrl + S ... Boris crashed, said the file was corrupted (I don't know the exact error message), but the .boris file is now completely empty... 
Any chance to recover any previous version ?

Thanks in advance,
Damien

**Comment by olivierfriard** [comment]
Hi Damien,

if the project file is empty there is no chance to recover some data.
I hope you have made some backup

Cheers
