### ISSUE TITLE
exclusion matrix point event

### ISSUE THREAD

**Issue by fvdrvc** [olivierfriard/BORIS#744]
Hi, i'm using the 8.25.4 boris verison
I set the matrix exclusion as stated in the manual, however all of a sudden state behaviours are stopped when i add a point event. I don't want the point events included in the exclusion matrix though. When i was asked if i wanted the point event included in the exlusion matrix i clicked NO. I don't know why, since the first time i set this feature it was working correctly, when i reopened the project after i saved it, i had this kind of problem. Could you please help me? Did i do sometthing wrong? thank you so much, Kind regards :)

**Comment by fvdrvc** [comment]
Thank you for your help, I resolved the issue by myself. Have a nice day.

**Comment by olivierfriard** [comment]
Hi,
Is it an issue that can be fixed in the program?
