### ISSUE TITLE
Skipping frames when transitioning between video files in same observation

### ISSUE THREAD

**Issue by Th225sa** [olivierfriard/BORIS#748]
Hi there, 

When transitioning from one video clip to the next in an observation, the software seems to skip around 36/37 frames from the start of the next clip and does not allow me to scroll back into those frame. I may have the same issue at the start of each video clip.

Any help would be greatly appreciated

Thanks,
Tom

**Indicate the version of BORIS**
Version up to date

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Type of BORIS instalaltion - setup

**Comment by olivierfriard** [comment]
Hi,
please indicate the version of BORIS

**Comment by olivierfriard** [comment]
Hi,
did you try to re-encode your video?
See Tools > Media file > Re-encode / resize video

**Comment by Th225sa** [comment]
Hi Oliver,

I have tried this but it didn't change anything. I tried using a different file convert (Adobe media encoder - rather than VCL). This solved the problem but now that I have swapped the newly converted the files in to the observation, I now have an issue where the second video starts 0.740 seconds (37 frames) before video 1 ends - resulting in a glitch that means that I'm scoring the same seconds twice. Everything from the first video aligns perfectly with the newly converted file but I now have quite a major issue with all the the observations from the second video being out of sync and the transition between the two clips being very problematic. Sorry if I have explained this poorly.

All the best,
Tom

**Comment by Th225sa** [comment]
Hi Oliver,

My apologies. I have managed to fix it by manually deleting the video files from the observation and then re-uploaded them to the project. Still some syncing issues to sort but the time signature glitch seems to have sorted itself out.

Thanks,
Tom
