### ISSUE TITLE
Duration changes after the current observation ends or is paused.

### ISSUE THREAD

**Issue by arpitt21** [olivierfriard/BORIS#75]
While coding an observation, when the video file ends, the current duration of the video some times codes as being more than the total duration of the video.  If the last coded event is coded at the end of the video, its duration will be coded as longer than the duration of the video. E.g. If the video is 2.34 minutes, the last coded point event will have an onset of 2.40 minutes. 
How do I fix this?

Thank you.

**Comment by olivierfriard** [comment]
What video format are you using?
I never noticed this kind of problem.

**Comment by arpitt21** [comment]
Hi Olivier, 

I am using .mp4 format. I converted these videos from .mts to .mp4. 

Thanks.
Arpit
