### ISSUE TITLE
Playback Speed Shortcuts / Time Budget Binning

### ISSUE THREAD

**Issue by jamesrhyde** [olivierfriard/BORIS#77]
We have found that BORIS works very well for behavioral scoring, but have found two features that would be useful additions.  Keyboard shortcuts to increase/decrease media playback speed would make scoring more efficient.  Another useful addition would be the ability to automatically subdivide the time budget analysis into smaller time bins.  

Thanks!

**Comment by olivierfriard** [comment]
Hi,
this feature request was added long time ago...
Speed shortcuts were added (Home for increasing, End for decreasing) 
I will not add the binned time budget option
Thanks
