### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by chocamoofin** [olivierfriard/BORIS#771]
Currently I am unable to download the BORIS software onto my windows laptop using either the portable or setup link. Once I click on the download link from the BORIS website I receive an error page as pictured below
<img width="360" alt="image" src="https://github.com/user-attachments/assets/c4832c40-6657-4a4e-9746-30e83b6ec389">

I am wondering if the link is under construction or something else? I have tried to access it on three computers but receive the same error message so I decided to post here just in case.

Any help is appreciated!

**Comment by olivierfriard** [comment]
I cannot reproduce this issue.
Maybe it was a temporary failure
