### ISSUE TITLE
Error: Cannot import ethogram from previous BORIS project

### ISSUE THREAD

**Issue by vansteynr** [olivierfriard/BORIS#781]
Cannot import ethogram from another BORIS project. Error message as follows:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.27.1
OS: Linux 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024
CPU: x86_64 x86_64
Python 3.10.12 (64-bit)
Qt 5.15.3 - PyQt 5.15.6
MPV library version: 1.109
MPV library file path: libmpv.so.1

Error succeded at 2024-08-07 15:16

Traceback (most recent call last):
  File "/opt/boris/boris/project.py", line 1848, in pbOK_clicked
    r = dict(self.check_ethogram())
  File "/opt/boris/boris/project.py", line 1706, in check_ethogram
    row["modifiers"] = json.loads(row["modifiers"]) if row["modifiers"] else {}
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

System info
===========

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.3
DISTRIB_CODENAME=virginia
DISTRIB_DESCRIPTION="Linux Mint 21.3 Virginia"
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy
cat: /etc/upstream-release: Is a directory
Linux SnyderCServer 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by olivierfriard** [comment]
Hi,
I cannot reproduce this issue.
Is it possible to access the project file from which you want to import the ethogram?

**Comment by olivierfriard** [comment]
Now I can reproduce the issue.
Please forget my previous comment.
I will fix it as soon as possible
Thank you for reporting this

**Comment by olivierfriard** [comment]
The v. 8.27.3 should fix this issue.
Please try and let me know:
https://github.com/olivierfriard/BORIS/releases/tag/v8.27.3

**Comment by vansteynr** [comment]
Could you provide me with instructions on updating my software to this new version? Thank you.


Raymond J. Van Steyn, MA

Doctoral Candidate

Cognitive & Comparative Psychology Program, CUNY Graduate Center

Reiss Laboratory of Cetacean cognition & communication

Dept. of Psychology, Hunter College

Lab: 212-772-4322

________________________________
From: Olivier Friard ***@***.***>
Sent: Monday, August 19, 2024 4:48 PM
To: olivierfriard/BORIS ***@***.***>
Cc: Raymond Vansteyn ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [olivierfriard/BORIS] Error: Cannot import ethogram from previous BORIS project (Issue #781)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


The v. 8.27.3 should fix this issue.
Please try and let me know:
https://github.com/olivierfriard/BORIS/releases/tag/v8.27.3

**Comment by olivierfriard** [comment]
Sure, 

* go to https://github.com/olivierfriard/BORIS/releases/tag/v8.27.3
* download the  boris_8.27.3-0.deb file
* install it with your package manager

thank you for your collaboration

**Comment by vansteynr** [comment]
The issue appears to be fixed. Thank you for your prompt response.

Be well,

Raymond J. Van Steyn, MA

Doctoral Candidate

Cognitive & Comparative Psychology Program, CUNY Graduate Center

Reiss Laboratory of Cetacean cognition & communication

Dept. of Psychology, Hunter College

Lab: 212-772-4322

________________________________
From: Olivier Friard ***@***.***>
Sent: Tuesday, August 20, 2024 8:54 AM
To: olivierfriard/BORIS ***@***.***>
Cc: Raymond Vansteyn ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [olivierfriard/BORIS] Error: Cannot import ethogram from previous BORIS project (Issue #781)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Sure,

  *   go to https://github.com/olivierfriard/BORIS/releases/tag/v8.27.3
  *   download the boris_8.27.3-0.deb file
  *   install it with your package manager

thank you for your collaboration
