### ISSUE TITLE
BORIS V 4.1.3 not compatible with projects made from BORIS V 2.981?

### ISSUE THREAD

**Issue by aimop95** [olivierfriard/BORIS#79]
Hello!

I just thought I'd report this weird bug/interaction. So I have some files that were made on the BORIS V 2.981, but upon updating my own BORIS program separately, those files no longer open. Instead, they create a new file that has "_Old_version" attached to the name. Thing is, BORIS (updated program) still won't open the file that it supposedly updated (not the "_Old_version" file). It just keeps saying that it has updated my file. Opening the file with the "Old_version" ending simply makes another file with the exact same name (bringing up total files to 3, the "updated" one and 2 "old version" ones.

Any advice on how to open files made by an older version of BORIS?

Sincerely,

Michael

**Comment by olivierfriard** [comment]
Hi,
this bug should be fixed in v. 4.1.4 just released.
Can you confirm that?

**Comment by aimop95** [comment]
Works like a charm!

Thank you so much!
