### ISSUE TITLE
Instantaneous Groups Scans

### ISSUE THREAD

**Issue by dbwood08** [olivierfriard/BORIS#791]
Instantaneous groups scans is a common form of data collection for wild life biologists. Often performed during focal follows, groups scans allow for data to be collected on the position and activity of all visible individuals not merely the focal. 

I request a feature to be added to BORRIS that would allow me to set a timer (say every 4 minutes) that would pause the video and prompt the user to code the individual, behavior, and distance from the focal using a different ethogram (or a modified ethogram, certainly coded with different codes in the output). 

Thanks.

**Comment by olivierfriard** [comment]
See the user guide:
https://www.boris.unito.it/user_guide/observations/#scan-sampling-live-and-media-observation

**Comment by dbwood08** [comment]
This feature makes it so that I can only collect data for the interval specified in the time interval, but that's not what I need.

I would like to be able to do continuous focal follow sampling, and then every 4 minutes I want the video to pause and I want to be prompted to record the activity and distance from the focal of all visible groups members. Once I have made those observations, I would like to restart the video where it left off and continue with the focal follow.
Is this possible in BORRIS? Is there any work around to achieve something similar?

**Comment by dbwood08** [comment]
You're correct, the functionality was already there, I was just having trouble finding the right box. 
For those confused like me, here's another description:
When generating a new observation from a media file, underneath the box that appears after you click the circle labeled "Observation from media file(s)" there is the option to define the interval for scan sampling. Its right above the very last box you can click that asks if you want to "Stop ongoing state events between successive media files".
