### ISSUE TITLE
Pasting copied events doesn't always work

### ISSUE THREAD

**Issue by SirWilksBoothDaThird** [olivierfriard/BORIS#796]
Version: 8.27.8 (latest)

Additional versions tested:
8.27.1
8.25.4
7.4
7.1

Project integrity check: No issues found

Bug:
Copying an event with a specific time position, frame index, subject, code, and modifiers rarely allows for pasting in the events table. The bug is present for both POINT and STATE events, as well as for events without any modifiers or subject added. 

The event may be pasted into a text editor or other application 100% of the time from clipboard. I've had about 2 or 3 instances where pasting actually worked over the last

***No crashes ever occur when trying to paste event data, and no errors related to this issue are ever logged to the boris.log file.

This could be a formatting issue with columns and how they are incompatible with pasting into BORIS' events table, however, the copying and pasting is being done in the same BORIS version, instance, and session, so I assume that the format is unified as I am not playing with multiple BORIS instances or anything.

Steps to reproduce:
1. Add one or multiple successive STATE or POINT events with a specified subject and modifier into the events table in BORIS 8.27.8
2. Right-click any STATE or POINT event and choose command 'Copy events'
3. Jump or search forward any amount of time along the 'Media position' timeline
4. Within the events table, right-click any empty area or any specific row/column and choose command 'Paste events'
5. Observe that no extra rows with the copied event(s) have been added, nor have any existing event rows been replaced with the copied data

Expected behavior:

Upon right-clicking in the empty area or a specific event row within events table, and choosing the command 'Paste events', there should be extra row(s) added with the copied event data.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Build 19045 (v10.0.19045)
 - Full BORIS 8.27.8 (Both Portable and Full/Local installations have been tested)

Thank you for your help Olivier and the BORIS team for their research.
I hope to hear from you soon.

**Comment by olivierfriard** [comment]
Hi,

you cannot paste a copied event if this event already exists in the events table (same time, same subject, same behavior).
I will add an error message when this situation will occur in the next release.
Let me know if I have answered the question.

**Comment by SirWilksBoothDaThird** [comment]
Hi Olivier, 

Thank you very much for clarifying this. 
This poses the next logical question, what is the 'Paste events' option for? 

I pasted a copied event into Notepad, changed the timestamp, then tried pasting this "new" event back into the events table in BORIS, only to get an error that the format needs to be 6 columns, separated by a TAB character.

Why not take out this paste option altogether, or does it actually have a function?

Also, would it be worth modifying a previous feature request that I made about having a working "Copy/Paste events" function to request the ability to input a custom time position (similar to the "Fix unpaired events" function)?

Thanks again for your help.

**Comment by SirWilksBoothDaThird** [comment]
Olivier, thank you again for replying to my original question.

Should I make another question?

My follow-up question is basically: what is the "Paste events" option for in the newest BORIS version, if modifying timestamps in a copied event still doesn't seem to allow pasting back into the events table?

Thank you in advance.
