### ISSUE TITLE
handling of file paths

### ISSUE THREAD

**Issue by jpresern** [olivierfriard/BORIS#90]
I believe this is not really a bug, but the issue could be avoided.

The issue crops up because mounting point (of external USB) differs between Mac and Linux. For example, I have BORIS project in a folder on portable disk. Same folder contains subfolders with media files. If I create an observation on Linux, Mac will complain that media cannot be found when I open the same observation. I assume it is searching the wrong path. Same happens also the way around - starting observation on Mac and reopening it on Linux.

I know I could solve this issue by providing symlinks or different mount points via terminal, but this is clumsy for an ordinary user.

Could this problem be avoided somehow to provide relative paths? So the media files in the observation would be refered by path like "./subfolder/mediafile.mp4"?

**Comment by olivierfriard** [comment]
This feature was added in v.6.1.1

See http://boris.readthedocs.io/en/latest/#media-based-observation for details and please report any bug
