### ISSUE TITLE
Discrepancies between event durations in events list and time budgets + avoiding ''unpaired' issue

### ISSUE THREAD

**Issue by DanBrierley** [olivierfriard/BORIS#98]
(Already posted this on google group)

Hi,

I'm coding some preliminary short observations to validate ethograms and IRR prior to coding mouse behavioural satiety sequences. As such, I've selected a random 10 minute section of a single 2 hour video to code, and coded the 10 min duration using only mutually exclusive state events. Therefore, when exporting data as either time budget analysis (limited to the 10 minute time interval coded) or list of events, the duration of all behaviours combined should be exactly 10 minutes. From the exported events, this is indeed the case (actually 15ms less which I assume is due to rounding / transitions). However, when I add the durations from the time budget analysis (either original or synthetic analyses) the total is far higher, at ~684s and the total number of 1 particular behaviour is higher (i.e. it says there were 8 instances when only 7 in actual list). I have coded the same 10 minute section 3 times, and all 3 observations have this issue, however the extra duration is not consistent. Any explanation for this?

I also have a related query to this, which is somewhat less urgent and contingent on the time budget analysis data being accurate:

Is there a way to get around the issue of state events being 'unpaired' when generating time budget analyses from a limited interval within a coded observation? Specifically, our aim is to code 1 hour of mutually exclusive state events, then to analyse the percentage duration of each behaviour during 12 x 5 minute time bins. In theory this should be simple, as we could just export individual time budget analyses from 0-5 minutes, 5-10 minutes intervals etc. However as these time bins do not coincide with the start and stop times of state events at the beginning and end of the 5 minute intervals, these events will be unpaired, and thus the entire behaviour is excluded from the time budget analysis. Is there another way to conduct the time bin analysis as described, or otherwise to add in a function during TBA of specified intervals that effectively adds an artificial start and stop to ongoing behaviours at each end of the interval to get round this issue?

Thanks in advance, and for creating this very useful piece of software!

**Comment by olivierfriard** [comment]
Hi Dan,

1) What version of BORIS are you using?
can you send me your project file by email (check BORIS web site for
address)? I will try to reproduce your problem.

2) This problem should be fixed in v. 5.1.0
Please try a time budget analysis (from 0:00:10 to 0:00:25) on the
observation in the attached BORIS project.

Olivier


> --
University of Torino
Life Sciences and Systems Biology department
Via dell'Accademia Albertina, 13 10123 TORINO (Italy)
tel: +39 011 6704542
http://www.di.unito.it/~friard/
http://orcid.org/0000-0002-0374-9872

**Comment by olivierfriard** [comment]
fixed in v. 5.1.3
